<?php

namespace Database\Seeders;

use App\Models\ContrapartidaPUC;
use App\Models\PUC; // To lookup parent PUC ID
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\Log; // For logging if parent PUC not found

class ContrapartidaPUCActivoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cuentasContrapartida = [
            ['contpuc_codigo' => '110505', 'contpuc_descripcion' => 'Caja general', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1105'],
            ['contpuc_codigo' => '110510', 'contpuc_descripcion' => 'Cajas menores', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1105'],
            ['contpuc_codigo' => '110515', 'contpuc_descripcion' => 'Moneda extranjera', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1105'],
            ['contpuc_codigo' => '111005', 'contpuc_descripcion' => 'Moneda nacional', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1110'],
            ['contpuc_codigo' => '111010', 'contpuc_descripcion' => 'Moneda extranjera', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1110'],
            ['contpuc_codigo' => '111505', 'contpuc_descripcion' => 'Moneda nacional', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1115'],
            ['contpuc_codigo' => '111510', 'contpuc_descripcion' => 'Moneda extranjera', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1115'],
            ['contpuc_codigo' => '112005', 'contpuc_descripcion' => 'Bancos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1120'],
            ['contpuc_codigo' => '112010', 'contpuc_descripcion' => 'Corporaciones de ahorro y vivienda', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1120'],
            ['contpuc_codigo' => '112015', 'contpuc_descripcion' => 'Organismos cooperativos financieros', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1120'],
            ['contpuc_codigo' => '112505', 'contpuc_descripcion' => 'Rotatorios moneda nacional', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1125'],
            ['contpuc_codigo' => '112510', 'contpuc_descripcion' => 'Rotatorios moneda extranjera', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1125'],
            ['contpuc_codigo' => '112515', 'contpuc_descripcion' => 'Especiales moneda nacional', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1125'],
            ['contpuc_codigo' => '112520', 'contpuc_descripcion' => 'Especiales moneda extranjera', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1125'],
            ['contpuc_codigo' => '112525', 'contpuc_descripcion' => 'De amortización moneda nacional', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1125'],
            ['contpuc_codigo' => '112530', 'contpuc_descripcion' => 'De amortización moneda extranjera', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1125'],
            ['contpuc_codigo' => '120505', 'contpuc_descripcion' => 'Agricultura, ganadería, caza y silvicultura', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1205'],
            ['contpuc_codigo' => '120510', 'contpuc_descripcion' => 'Pesca', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1205'],
            ['contpuc_codigo' => '120515', 'contpuc_descripcion' => 'Explotación de minas y canteras', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1205'],
            ['contpuc_codigo' => '120520', 'contpuc_descripcion' => 'Industria manufacturera', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1205'],
            ['contpuc_codigo' => '120525', 'contpuc_descripcion' => 'Suministro de electricidad, gas y agua', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1205'],
            ['contpuc_codigo' => '120530', 'contpuc_descripcion' => 'Construcción', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1205'],
            ['contpuc_codigo' => '120535', 'contpuc_descripcion' => 'Comercio al por mayor y al por menor', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1205'],
            ['contpuc_codigo' => '120540', 'contpuc_descripcion' => 'Hoteles y restaurantes', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1205'],
            ['contpuc_codigo' => '120545', 'contpuc_descripcion' => 'Transporte, almacenamiento y comunicaciones', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1205'],
            ['contpuc_codigo' => '120550', 'contpuc_descripcion' => 'Actividad financiera', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1205'],
            ['contpuc_codigo' => '120555', 'contpuc_descripcion' => 'Actividades inmobiliarias, empresariales y de alquiler', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1205'],
            ['contpuc_codigo' => '120560', 'contpuc_descripcion' => 'Enseñanza', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1205'],
            ['contpuc_codigo' => '120565', 'contpuc_descripcion' => 'Servicios sociales y de salud', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1205'],
            ['contpuc_codigo' => '120570', 'contpuc_descripcion' => 'Otras actividades de servicios comunitarios, sociales y personales', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1205'],
            ['contpuc_codigo' => '120599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1205'],
            ['contpuc_codigo' => '121005', 'contpuc_descripcion' => 'Agricultura, ganadería, caza y silvicultura', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1210'],
            ['contpuc_codigo' => '121010', 'contpuc_descripcion' => 'Pesca', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1210'],
            ['contpuc_codigo' => '121015', 'contpuc_descripcion' => 'Explotación de minas y canteras', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1210'],
            ['contpuc_codigo' => '121020', 'contpuc_descripcion' => 'Industria manufacturera', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1210'],
            ['contpuc_codigo' => '121025', 'contpuc_descripcion' => 'Suministro de electricidad, gas y agua', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1210'],
            ['contpuc_codigo' => '121030', 'contpuc_descripcion' => 'Construcción', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1210'],
            ['contpuc_codigo' => '121035', 'contpuc_descripcion' => 'Comercio al por mayor y al por menor', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1210'],
            ['contpuc_codigo' => '121040', 'contpuc_descripcion' => 'Hoteles y restaurantes', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1210'],
            ['contpuc_codigo' => '121045', 'contpuc_descripcion' => 'Transporte, almacenamiento y comunicaciones', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1210'],
            ['contpuc_codigo' => '121050', 'contpuc_descripcion' => 'Actividad financiera', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1210'],
            ['contpuc_codigo' => '121055', 'contpuc_descripcion' => 'Actividades inmobiliarias, empresariales y de alquiler', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1210'],
            ['contpuc_codigo' => '121060', 'contpuc_descripcion' => 'Enseñanza', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1210'],
            ['contpuc_codigo' => '121065', 'contpuc_descripcion' => 'Servicios sociales y de salud', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1210'],
            ['contpuc_codigo' => '121070', 'contpuc_descripcion' => 'Otras actividades de servicios comunitarios, sociales y personales', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1210'],
            ['contpuc_codigo' => '121099', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1210'],
            ['contpuc_codigo' => '121505', 'contpuc_descripcion' => 'Bonos públicos moneda nacional', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1215'],
            ['contpuc_codigo' => '121510', 'contpuc_descripcion' => 'Bonos públicos moneda extranjera', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1215'],
            ['contpuc_codigo' => '121515', 'contpuc_descripcion' => 'Bonos ordinarios', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1215'],
            ['contpuc_codigo' => '121520', 'contpuc_descripcion' => 'Bonos convertibles en acciones', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1215'],
            ['contpuc_codigo' => '121595', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1215'],
            ['contpuc_codigo' => '122005', 'contpuc_descripcion' => 'Cédulas de capitalización', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1220'],
            ['contpuc_codigo' => '122010', 'contpuc_descripcion' => 'Cédulas hipotecarias', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1220'],
            ['contpuc_codigo' => '122015', 'contpuc_descripcion' => 'Cédulas de inversión', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1220'],
            ['contpuc_codigo' => '122095', 'contpuc_descripcion' => 'Otras', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1220'],
            ['contpuc_codigo' => '122505', 'contpuc_descripcion' => 'Certificados de depósito a término (CDT)', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1225'],
            ['contpuc_codigo' => '122510', 'contpuc_descripcion' => 'Certificados de depósito de ahorro', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1225'],
            ['contpuc_codigo' => '122515', 'contpuc_descripcion' => 'Certificados de ahorro de valor constante (CAVC)', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1225'],
            ['contpuc_codigo' => '122520', 'contpuc_descripcion' => 'Certificados de cambio', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1225'],
            ['contpuc_codigo' => '122525', 'contpuc_descripcion' => 'Certificados cafeteros valorizables', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1225'],
            ['contpuc_codigo' => '122530', 'contpuc_descripcion' => 'Certificados eléctricos valorizables (CEV)', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1225'],
            ['contpuc_codigo' => '122535', 'contpuc_descripcion' => 'Certificados de reembolso tributario (CERT)', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1225'],
            ['contpuc_codigo' => '122540', 'contpuc_descripcion' => 'Certificados de desarrollo turístico', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1225'],
            ['contpuc_codigo' => '122545', 'contpuc_descripcion' => 'Certificados de inversión forestal (CIF)', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1225'],
            ['contpuc_codigo' => '122595', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1225'],
            ['contpuc_codigo' => '123005', 'contpuc_descripcion' => 'Empresas comerciales', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1230'],
            ['contpuc_codigo' => '123010', 'contpuc_descripcion' => 'Empresas industriales', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1230'],
            ['contpuc_codigo' => '123015', 'contpuc_descripcion' => 'Empresas de servicios', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1230'],
            ['contpuc_codigo' => '123505', 'contpuc_descripcion' => 'Títulos de desarrollo agropecuario', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1235'],
            ['contpuc_codigo' => '123510', 'contpuc_descripcion' => 'Títulos canjeables por certificados de cambio', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1235'],
            ['contpuc_codigo' => '123515', 'contpuc_descripcion' => 'Títulos de tesorería (TES)', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1235'],
            ['contpuc_codigo' => '123520', 'contpuc_descripcion' => 'Títulos de participación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1235'],
            ['contpuc_codigo' => '123525', 'contpuc_descripcion' => 'Títulos de crédito de fomento', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1235'],
            ['contpuc_codigo' => '123530', 'contpuc_descripcion' => 'Títulos financieros agroindustriales (TFA)', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1235'],
            ['contpuc_codigo' => '123535', 'contpuc_descripcion' => 'Títulos de ahorro cafetero (TAC)', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1235'],
            ['contpuc_codigo' => '123540', 'contpuc_descripcion' => 'Títulos de ahorro nacional (TAN)', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1235'],
            ['contpuc_codigo' => '123545', 'contpuc_descripcion' => 'Títulos energéticos de rentabilidad creciente (TER)', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1235'],
            ['contpuc_codigo' => '123550', 'contpuc_descripcion' => 'Títulos de ahorro educativo (TAE)', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1235'],
            ['contpuc_codigo' => '123555', 'contpuc_descripcion' => 'Títulos financieros industriales y comerciales', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1235'],
            ['contpuc_codigo' => '123560', 'contpuc_descripcion' => 'Tesoros', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1235'],
            ['contpuc_codigo' => '123565', 'contpuc_descripcion' => 'Títulos de devolución de impuestos nacionales (TIDIS)', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1235'],
            ['contpuc_codigo' => '123570', 'contpuc_descripcion' => 'Títulos inmobiliarios', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1235'],
            ['contpuc_codigo' => '123595', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1235'],
            ['contpuc_codigo' => '124005', 'contpuc_descripcion' => 'Bancos comerciales', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1240'],
            ['contpuc_codigo' => '124010', 'contpuc_descripcion' => 'Compañías de financiamiento comercial', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1240'],
            ['contpuc_codigo' => '124015', 'contpuc_descripcion' => 'Corporaciones financieras', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1240'],
            ['contpuc_codigo' => '124095', 'contpuc_descripcion' => 'Otras', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1240'],
            ['contpuc_codigo' => '124505', 'contpuc_descripcion' => 'Fideicomisos de inversión moneda nacional', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1245'],
            ['contpuc_codigo' => '124510', 'contpuc_descripcion' => 'Fideicomisos de inversión moneda extranjera', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1245'],
            ['contpuc_codigo' => '125005', 'contpuc_descripcion' => 'Acciones', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1250'],
            ['contpuc_codigo' => '125010', 'contpuc_descripcion' => 'Cuotas o partes de interés social', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1250'],
            ['contpuc_codigo' => '125015', 'contpuc_descripcion' => 'Bonos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1250'],
            ['contpuc_codigo' => '125020', 'contpuc_descripcion' => 'Cédulas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1250'],
            ['contpuc_codigo' => '125025', 'contpuc_descripcion' => 'Certificados', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1250'],
            ['contpuc_codigo' => '125030', 'contpuc_descripcion' => 'Papeles comerciales', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1250'],
            ['contpuc_codigo' => '125035', 'contpuc_descripcion' => 'Títulos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1250'],
            ['contpuc_codigo' => '125040', 'contpuc_descripcion' => 'Aceptaciones bancarias o financieras', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1250'],
            ['contpuc_codigo' => '125095', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1250'],
            ['contpuc_codigo' => '125099', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1250'],
            ['contpuc_codigo' => '125505', 'contpuc_descripcion' => 'Bonos de financiamiento especial', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1255'],
            ['contpuc_codigo' => '125510', 'contpuc_descripcion' => 'Bonos de financiamiento presupuestal', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1255'],
            ['contpuc_codigo' => '125515', 'contpuc_descripcion' => 'Bonos para desarrollo social y seguridad interna (BDSI)', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1255'],
            ['contpuc_codigo' => '125595', 'contpuc_descripcion' => 'Otras', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1255'],
            ['contpuc_codigo' => '126099', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1260'],
            ['contpuc_codigo' => '129505', 'contpuc_descripcion' => 'Aportes en cooperativas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1295'],
            ['contpuc_codigo' => '129510', 'contpuc_descripcion' => 'Derechos en clubes sociales', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1295'],
            ['contpuc_codigo' => '129515', 'contpuc_descripcion' => 'Acciones o derechos en clubes deportivos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1295'],
            ['contpuc_codigo' => '129520', 'contpuc_descripcion' => 'Bonos en colegios', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1295'],
            ['contpuc_codigo' => '129595', 'contpuc_descripcion' => 'Diversas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1295'],
            ['contpuc_codigo' => '129599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1295'],
            ['contpuc_codigo' => '129905', 'contpuc_descripcion' => 'Acciones', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1299'],
            ['contpuc_codigo' => '129910', 'contpuc_descripcion' => 'Cuotas o partes de interés social', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1299'],
            ['contpuc_codigo' => '129915', 'contpuc_descripcion' => 'Bonos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1299'],
            ['contpuc_codigo' => '129920', 'contpuc_descripcion' => 'Cédulas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1299'],
            ['contpuc_codigo' => '129925', 'contpuc_descripcion' => 'Certificados', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1299'],
            ['contpuc_codigo' => '129930', 'contpuc_descripcion' => 'Papeles comerciales', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1299'],
            ['contpuc_codigo' => '129935', 'contpuc_descripcion' => 'Títulos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1299'],
            ['contpuc_codigo' => '129940', 'contpuc_descripcion' => 'Aceptaciones bancarias o financieras', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1299'],
            ['contpuc_codigo' => '129945', 'contpuc_descripcion' => 'Derechos fiduciarios', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1299'],
            ['contpuc_codigo' => '129950', 'contpuc_descripcion' => 'Derechos de recompra de inversiones negociadas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1299'],
            ['contpuc_codigo' => '129955', 'contpuc_descripcion' => 'Obligatorias', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1299'],
            ['contpuc_codigo' => '129960', 'contpuc_descripcion' => 'Cuentas en participación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1299'],
            ['contpuc_codigo' => '129995', 'contpuc_descripcion' => 'Otras inversiones', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1299'],
            ['contpuc_codigo' => '130505', 'contpuc_descripcion' => 'Nacionales', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1305'],
            ['contpuc_codigo' => '130510', 'contpuc_descripcion' => 'Del exterior', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1305'],
            ['contpuc_codigo' => '130515', 'contpuc_descripcion' => 'Deudores del sistema', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1305'],
            ['contpuc_codigo' => '131005', 'contpuc_descripcion' => 'Casa matriz', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1310'],
            ['contpuc_codigo' => '131010', 'contpuc_descripcion' => 'Compañías vinculadas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1310'],
            ['contpuc_codigo' => '131015', 'contpuc_descripcion' => 'Accionistas o socios', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1310'],
            ['contpuc_codigo' => '131020', 'contpuc_descripcion' => 'Particulares', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1310'],
            ['contpuc_codigo' => '131095', 'contpuc_descripcion' => 'Otras', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1310'],
            ['contpuc_codigo' => '131505', 'contpuc_descripcion' => 'Ventas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1315'],
            ['contpuc_codigo' => '131510', 'contpuc_descripcion' => 'Pagos a nombre de casa matriz', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1315'],
            ['contpuc_codigo' => '131515', 'contpuc_descripcion' => 'Valores recibidos por casa matriz', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1315'],
            ['contpuc_codigo' => '131520', 'contpuc_descripcion' => 'Préstamos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1315'],
            ['contpuc_codigo' => '132005', 'contpuc_descripcion' => 'Filiales', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1320'],
            ['contpuc_codigo' => '132010', 'contpuc_descripcion' => 'Subsidiarias', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1320'],
            ['contpuc_codigo' => '132015', 'contpuc_descripcion' => 'Sucursales', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1320'],
            ['contpuc_codigo' => '132505', 'contpuc_descripcion' => 'A socios', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1325'],
            ['contpuc_codigo' => '132510', 'contpuc_descripcion' => 'A accionistas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1325'],
            ['contpuc_codigo' => '133005', 'contpuc_descripcion' => 'A proveedores', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1330'],
            ['contpuc_codigo' => '133010', 'contpuc_descripcion' => 'A contratistas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1330'],
            ['contpuc_codigo' => '133015', 'contpuc_descripcion' => 'A trabajadores', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1330'],
            ['contpuc_codigo' => '133020', 'contpuc_descripcion' => 'A agentes', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1330'],
            ['contpuc_codigo' => '133025', 'contpuc_descripcion' => 'A concesionarios', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1330'],
            ['contpuc_codigo' => '133030', 'contpuc_descripcion' => 'De adjudicaciones', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1330'],
            ['contpuc_codigo' => '133095', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1330'],
            ['contpuc_codigo' => '133099', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1330'],
            ['contpuc_codigo' => '133505', 'contpuc_descripcion' => 'Para importaciones', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1335'],
            ['contpuc_codigo' => '133510', 'contpuc_descripcion' => 'Para servicios', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1335'],
            ['contpuc_codigo' => '133515', 'contpuc_descripcion' => 'Para contratos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1335'],
            ['contpuc_codigo' => '133520', 'contpuc_descripcion' => 'Para responsabilidades', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1335'],
            ['contpuc_codigo' => '133525', 'contpuc_descripcion' => 'Para juicios ejecutivos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1335'],
            ['contpuc_codigo' => '133530', 'contpuc_descripcion' => 'Para adquisición de acciones, cuotas o derechos sociales', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1335'],
            ['contpuc_codigo' => '133535', 'contpuc_descripcion' => 'En garantía', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1335'],
            ['contpuc_codigo' => '133595', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1335'],
            ['contpuc_codigo' => '134005', 'contpuc_descripcion' => 'De bienes raíces', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1340'],
            ['contpuc_codigo' => '134010', 'contpuc_descripcion' => 'De maquinaria y equipo', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1340'],
            ['contpuc_codigo' => '134015', 'contpuc_descripcion' => 'De flota y equipo de transporte', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1340'],
            ['contpuc_codigo' => '134020', 'contpuc_descripcion' => 'De flota y equipo aéreo', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1340'],
            ['contpuc_codigo' => '134025', 'contpuc_descripcion' => 'De flota y equipo férreo', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1340'],
            ['contpuc_codigo' => '134030', 'contpuc_descripcion' => 'De flota y equipo  fluvial y/o marítimo', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1340'],
            ['contpuc_codigo' => '134035', 'contpuc_descripcion' => 'De semovientes', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1340'],
            ['contpuc_codigo' => '134095', 'contpuc_descripcion' => 'De otros bienes', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1340'],
            ['contpuc_codigo' => '134505', 'contpuc_descripcion' => 'Dividendos y/o participaciones', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1345'],
            ['contpuc_codigo' => '134510', 'contpuc_descripcion' => 'Intereses', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1345'],
            ['contpuc_codigo' => '134515', 'contpuc_descripcion' => 'Comisiones', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1345'],
            ['contpuc_codigo' => '134520', 'contpuc_descripcion' => 'Honorarios', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1345'],
            ['contpuc_codigo' => '134525', 'contpuc_descripcion' => 'Servicios', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1345'],
            ['contpuc_codigo' => '134530', 'contpuc_descripcion' => 'Arrendamientos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1345'],
            ['contpuc_codigo' => '134535', 'contpuc_descripcion' => 'CERT por cobrar', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1345'],
            ['contpuc_codigo' => '134595', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1345'],
            ['contpuc_codigo' => '135005', 'contpuc_descripcion' => 'De construcción', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1350'],
            ['contpuc_codigo' => '135010', 'contpuc_descripcion' => 'De prestación de servicios', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1350'],
            ['contpuc_codigo' => '135095', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1350'],
            ['contpuc_codigo' => '135505', 'contpuc_descripcion' => 'Anticipo de impuestos de renta y complementarios', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1355'],
            ['contpuc_codigo' => '135510', 'contpuc_descripcion' => 'Anticipo de impuestos de industria y comercio', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1355'],
            ['contpuc_codigo' => '135515', 'contpuc_descripcion' => 'Retención en la fuente', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1355'],
            ['contpuc_codigo' => '135517', 'contpuc_descripcion' => 'Impuesto a las ventas retenido', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1355'],
            ['contpuc_codigo' => '135518', 'contpuc_descripcion' => 'Impuesto de industria y comercio retenido', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1355'],
            ['contpuc_codigo' => '135520', 'contpuc_descripcion' => 'Sobrantes en liquidación privada de impuestos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1355'],
            ['contpuc_codigo' => '135525', 'contpuc_descripcion' => 'Contribuciones', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1355'],
            ['contpuc_codigo' => '135530', 'contpuc_descripcion' => 'Impuestos descontables', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1355'],
            ['contpuc_codigo' => '135595', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1355'],
            ['contpuc_codigo' => '136005', 'contpuc_descripcion' => 'A compañías aseguradoras', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1360'],
            ['contpuc_codigo' => '136010', 'contpuc_descripcion' => 'A transportadores', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1360'],
            ['contpuc_codigo' => '136015', 'contpuc_descripcion' => 'Por tiquetes aéreos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1360'],
            ['contpuc_codigo' => '136095', 'contpuc_descripcion' => 'Otras', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1360'],
            ['contpuc_codigo' => '136505', 'contpuc_descripcion' => 'Vivienda', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1365'],
            ['contpuc_codigo' => '136510', 'contpuc_descripcion' => 'Vehículos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1365'],
            ['contpuc_codigo' => '136515', 'contpuc_descripcion' => 'Educación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1365'],
            ['contpuc_codigo' => '136520', 'contpuc_descripcion' => 'Médicos, odontológicos y similares', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1365'],
            ['contpuc_codigo' => '136525', 'contpuc_descripcion' => 'Calamidad doméstica', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1365'],
            ['contpuc_codigo' => '136530', 'contpuc_descripcion' => 'Responsabilidades', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1365'],
            ['contpuc_codigo' => '136595', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1365'],
            ['contpuc_codigo' => '137005', 'contpuc_descripcion' => 'Con garantía real', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1370'],
            ['contpuc_codigo' => '137010', 'contpuc_descripcion' => 'Con garantía personal', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1370'],
            ['contpuc_codigo' => '138005', 'contpuc_descripcion' => 'Depositarios', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1380'],
            ['contpuc_codigo' => '138010', 'contpuc_descripcion' => 'Comisionistas de bolsas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1380'],
            ['contpuc_codigo' => '138015', 'contpuc_descripcion' => 'Fondo de inversión', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1380'],
            ['contpuc_codigo' => '138020', 'contpuc_descripcion' => 'Cuentas por cobrar de terceros', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1380'],
            ['contpuc_codigo' => '138025', 'contpuc_descripcion' => 'Pagos por cuenta de terceros', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1380'],
            ['contpuc_codigo' => '138030', 'contpuc_descripcion' => 'Fondos de inversión social', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1380'],
            ['contpuc_codigo' => '138095', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1380'],
            ['contpuc_codigo' => '139905', 'contpuc_descripcion' => 'Clientes', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1399'],
            ['contpuc_codigo' => '139910', 'contpuc_descripcion' => 'Cuentas corrientes comerciales', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1399'],
            ['contpuc_codigo' => '139915', 'contpuc_descripcion' => 'Cuentas por cobrar a casa matriz', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1399'],
            ['contpuc_codigo' => '139920', 'contpuc_descripcion' => 'Cuentas por cobrar a vinculados económicos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1399'],
            ['contpuc_codigo' => '139925', 'contpuc_descripcion' => 'Cuentas por cobrar a socios y accionistas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1399'],
            ['contpuc_codigo' => '139930', 'contpuc_descripcion' => 'Anticipos y avances', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1399'],
            ['contpuc_codigo' => '139932', 'contpuc_descripcion' => 'Cuentas de operación conjunta', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1399'],
            ['contpuc_codigo' => '139935', 'contpuc_descripcion' => 'Depósitos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1399'],
            ['contpuc_codigo' => '139940', 'contpuc_descripcion' => 'Promesas de compraventa', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1399'],
            ['contpuc_codigo' => '139945', 'contpuc_descripcion' => 'Ingresos por cobrar', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1399'],
            ['contpuc_codigo' => '139950', 'contpuc_descripcion' => 'Retención sobre contratos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1399'],
            ['contpuc_codigo' => '139955', 'contpuc_descripcion' => 'Reclamaciones', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1399'],
            ['contpuc_codigo' => '139960', 'contpuc_descripcion' => 'Cuentas por cobrar a trabajadores', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1399'],
            ['contpuc_codigo' => '139965', 'contpuc_descripcion' => 'Préstamos a particulares', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1399'],
            ['contpuc_codigo' => '139975', 'contpuc_descripcion' => 'Deudores varios', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1399'],
            ['contpuc_codigo' => '139980', 'contpuc_descripcion' => 'Derechos de recompra de cartera negociada', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1399'],
            ['contpuc_codigo' => '140599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1405'],
            ['contpuc_codigo' => '141099', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1410'],
            ['contpuc_codigo' => '141599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1415'],
            ['contpuc_codigo' => '141799', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1417'],
            ['contpuc_codigo' => '142099', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1420'],
            ['contpuc_codigo' => '142599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1425'],
            ['contpuc_codigo' => '142899', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1428'],
            ['contpuc_codigo' => '143005', 'contpuc_descripcion' => 'Productos manufacturados', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1430'],
            ['contpuc_codigo' => '143010', 'contpuc_descripcion' => 'Productos extraídos y/o procesados', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1430'],
            ['contpuc_codigo' => '143015', 'contpuc_descripcion' => 'Productos agrícolas y forestales', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1430'],
            ['contpuc_codigo' => '143020', 'contpuc_descripcion' => 'Subproductos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1430'],
            ['contpuc_codigo' => '143025', 'contpuc_descripcion' => 'Productos de pesca', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1430'],
            ['contpuc_codigo' => '143099', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1430'],
            ['contpuc_codigo' => '143599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1435'],
            ['contpuc_codigo' => '144099', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1440'],
            ['contpuc_codigo' => '144599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1445'],
            ['contpuc_codigo' => '145005', 'contpuc_descripcion' => 'Por urbanizar', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1450'],
            ['contpuc_codigo' => '145010', 'contpuc_descripcion' => 'Urbanizados por construir', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1450'],
            ['contpuc_codigo' => '145099', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1450'],
            ['contpuc_codigo' => '145599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1455'],
            ['contpuc_codigo' => '146099', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1460'],
            ['contpuc_codigo' => '146599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1465'],
            ['contpuc_codigo' => '149905', 'contpuc_descripcion' => 'Para obsolescencia', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1499'],
            ['contpuc_codigo' => '149910', 'contpuc_descripcion' => 'Para diferencia de inventario físico', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1499'],
            ['contpuc_codigo' => '149915', 'contpuc_descripcion' => 'Para pérdidas de inventarios', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1499'],
            ['contpuc_codigo' => '149920', 'contpuc_descripcion' => 'Lifo', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1499'],
            ['contpuc_codigo' => '150405', 'contpuc_descripcion' => 'Urbanos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1504'],
            ['contpuc_codigo' => '150410', 'contpuc_descripcion' => 'Rurales', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1504'],
            ['contpuc_codigo' => '150499', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1504'],
            ['contpuc_codigo' => '150605', 'contpuc_descripcion' => 'Tuberías y equipo', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1506'],
            ['contpuc_codigo' => '150610', 'contpuc_descripcion' => 'Costos de importación materiales', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1506'],
            ['contpuc_codigo' => '150615', 'contpuc_descripcion' => 'Proyectos de construcción', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1506'],
            ['contpuc_codigo' => '150699', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1506'],
            ['contpuc_codigo' => '150805', 'contpuc_descripcion' => 'Construcciones y edificaciones', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1508'],
            ['contpuc_codigo' => '150810', 'contpuc_descripcion' => 'Acueductos, plantas y redes', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1508'],
            ['contpuc_codigo' => '150815', 'contpuc_descripcion' => 'Vías de comunicación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1508'],
            ['contpuc_codigo' => '150820', 'contpuc_descripcion' => 'Pozos artesianos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1508'],
            ['contpuc_codigo' => '150825', 'contpuc_descripcion' => 'Proyectos de exploración', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1508'],
            ['contpuc_codigo' => '150830', 'contpuc_descripcion' => 'Proyectos de desarrollo', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1508'],
            ['contpuc_codigo' => '150899', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1508'],
            ['contpuc_codigo' => '151205', 'contpuc_descripcion' => 'Maquinaria y equipo', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1512'],
            ['contpuc_codigo' => '151210', 'contpuc_descripcion' => 'Equipo de oficina', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1512'],
            ['contpuc_codigo' => '151215', 'contpuc_descripcion' => 'Equipo de computación y comunicación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1512'],
            ['contpuc_codigo' => '151220', 'contpuc_descripcion' => 'Equipo médico-científico', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1512'],
            ['contpuc_codigo' => '151225', 'contpuc_descripcion' => 'Equipo de hoteles y restaurantes', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1512'],
            ['contpuc_codigo' => '151230', 'contpuc_descripcion' => 'Flota y equipo de transporte', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1512'],
            ['contpuc_codigo' => '151235', 'contpuc_descripcion' => 'Flota y equipo fluvial y/o marítimo', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1512'],
            ['contpuc_codigo' => '151240', 'contpuc_descripcion' => 'Flota y equipo aéreo', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1512'],
            ['contpuc_codigo' => '151245', 'contpuc_descripcion' => 'Flota y equipo férreo', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1512'],
            ['contpuc_codigo' => '151250', 'contpuc_descripcion' => 'Plantas y redes', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1512'],
            ['contpuc_codigo' => '151299', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1512'],
            ['contpuc_codigo' => '151605', 'contpuc_descripcion' => 'Edificios', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1516'],
            ['contpuc_codigo' => '151610', 'contpuc_descripcion' => 'Oficinas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1516'],
            ['contpuc_codigo' => '151615', 'contpuc_descripcion' => 'Almacenes', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1516'],
            ['contpuc_codigo' => '151620', 'contpuc_descripcion' => 'Fábricas y plantas industriales', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1516'],
            ['contpuc_codigo' => '151625', 'contpuc_descripcion' => 'Salas de exhibición y ventas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1516'],
            ['contpuc_codigo' => '151630', 'contpuc_descripcion' => 'Cafetería y casinos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1516'],
            ['contpuc_codigo' => '151635', 'contpuc_descripcion' => 'Silos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1516'],
            ['contpuc_codigo' => '151640', 'contpuc_descripcion' => 'Invernaderos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1516'],
            ['contpuc_codigo' => '151645', 'contpuc_descripcion' => 'Casetas y campamentos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1516'],
            ['contpuc_codigo' => '151650', 'contpuc_descripcion' => 'Instalaciones agropecuarias', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1516'],
            ['contpuc_codigo' => '151655', 'contpuc_descripcion' => 'Viviendas para empleados y obreros', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1516'],
            ['contpuc_codigo' => '151660', 'contpuc_descripcion' => 'Terminal de buses y taxis', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1516'],
            ['contpuc_codigo' => '151663', 'contpuc_descripcion' => 'Terminal marítimo', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1516'],
            ['contpuc_codigo' => '151665', 'contpuc_descripcion' => 'Terminal férreo', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1516'],
            ['contpuc_codigo' => '151670', 'contpuc_descripcion' => 'Parqueaderos, garajes y depósitos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1516'],
            ['contpuc_codigo' => '151675', 'contpuc_descripcion' => 'Hangares', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1516'],
            ['contpuc_codigo' => '151680', 'contpuc_descripcion' => 'Bodegas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1516'],
            ['contpuc_codigo' => '151695', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1516'],
            ['contpuc_codigo' => '151699', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1516'],
            ['contpuc_codigo' => '152099', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1520'],
            ['contpuc_codigo' => '152405', 'contpuc_descripcion' => 'Muebles y enseres', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1524'],
            ['contpuc_codigo' => '152410', 'contpuc_descripcion' => 'Equipos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1524'],
            ['contpuc_codigo' => '152495', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1524'],
            ['contpuc_codigo' => '152499', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1524'],
            ['contpuc_codigo' => '152805', 'contpuc_descripcion' => 'Equipos de procesamiento de datos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1528'],
            ['contpuc_codigo' => '152810', 'contpuc_descripcion' => 'Equipos de telecomunicaciones', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1528'],
            ['contpuc_codigo' => '152815', 'contpuc_descripcion' => 'Equipos de radio', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1528'],
            ['contpuc_codigo' => '152820', 'contpuc_descripcion' => 'Satélites y antenas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1528'],
            ['contpuc_codigo' => '152825', 'contpuc_descripcion' => 'Líneas telefónicas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1528'],
            ['contpuc_codigo' => '152895', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1528'],
            ['contpuc_codigo' => '152899', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1528'],
            ['contpuc_codigo' => '153205', 'contpuc_descripcion' => 'Médico', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1532'],
            ['contpuc_codigo' => '153210', 'contpuc_descripcion' => 'Odontológico', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1532'],
            ['contpuc_codigo' => '153215', 'contpuc_descripcion' => 'Laboratorio', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1532'],
            ['contpuc_codigo' => '153220', 'contpuc_descripcion' => 'Instrumental', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1532'],
            ['contpuc_codigo' => '153295', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1532'],
            ['contpuc_codigo' => '153299', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1532'],
            ['contpuc_codigo' => '153605', 'contpuc_descripcion' => 'De habitaciones', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1536'],
            ['contpuc_codigo' => '153610', 'contpuc_descripcion' => 'De comestibles y bebidas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1536'],
            ['contpuc_codigo' => '153695', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1536'],
            ['contpuc_codigo' => '153699', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1536'],
            ['contpuc_codigo' => '154005', 'contpuc_descripcion' => 'Autos, camionetas y camperos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1540'],
            ['contpuc_codigo' => '154008', 'contpuc_descripcion' => 'Camiones, volquetas y furgones', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1540'],
            ['contpuc_codigo' => '154010', 'contpuc_descripcion' => 'Tractomulas y remolques', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1540'],
            ['contpuc_codigo' => '154015', 'contpuc_descripcion' => 'Buses y busetas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1540'],
            ['contpuc_codigo' => '154017', 'contpuc_descripcion' => 'Recolectores y contenedores', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1540'],
            ['contpuc_codigo' => '154020', 'contpuc_descripcion' => 'Montacargas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1540'],
            ['contpuc_codigo' => '154025', 'contpuc_descripcion' => 'Palas y grúas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1540'],
            ['contpuc_codigo' => '154030', 'contpuc_descripcion' => 'Motocicletas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1540'],
            ['contpuc_codigo' => '154035', 'contpuc_descripcion' => 'Bicicletas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1540'],
            ['contpuc_codigo' => '154040', 'contpuc_descripcion' => 'Estibas y carretas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1540'],
            ['contpuc_codigo' => '154045', 'contpuc_descripcion' => 'Bandas transportadoras', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1540'],
            ['contpuc_codigo' => '154095', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1540'],
            ['contpuc_codigo' => '154099', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1540'],
            ['contpuc_codigo' => '154405', 'contpuc_descripcion' => 'Buques', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1544'],
            ['contpuc_codigo' => '154410', 'contpuc_descripcion' => 'Lanchas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1544'],
            ['contpuc_codigo' => '154415', 'contpuc_descripcion' => 'Remolcadoras', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1544'],
            ['contpuc_codigo' => '154420', 'contpuc_descripcion' => 'Botes', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1544'],
            ['contpuc_codigo' => '154425', 'contpuc_descripcion' => 'Boyas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1544'],
            ['contpuc_codigo' => '154430', 'contpuc_descripcion' => 'Amarres', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1544'],
            ['contpuc_codigo' => '154435', 'contpuc_descripcion' => 'Contenedores y chasises', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1544'],
            ['contpuc_codigo' => '154440', 'contpuc_descripcion' => 'Gabarras', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1544'],
            ['contpuc_codigo' => '154495', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1544'],
            ['contpuc_codigo' => '154499', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1544'],
            ['contpuc_codigo' => '154805', 'contpuc_descripcion' => 'Aviones', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1548'],
            ['contpuc_codigo' => '154810', 'contpuc_descripcion' => 'Avionetas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1548'],
            ['contpuc_codigo' => '154815', 'contpuc_descripcion' => 'Helicópteros', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1548'],
            ['contpuc_codigo' => '154820', 'contpuc_descripcion' => 'Turbinas y motores', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1548'],
            ['contpuc_codigo' => '154825', 'contpuc_descripcion' => 'Manuales de entrenamiento personal técnico', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1548'],
            ['contpuc_codigo' => '154830', 'contpuc_descripcion' => 'Equipos de vuelo', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1548'],
            ['contpuc_codigo' => '154895', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1548'],
            ['contpuc_codigo' => '154899', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1548'],
            ['contpuc_codigo' => '155205', 'contpuc_descripcion' => 'Locomotoras', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1552'],
            ['contpuc_codigo' => '155210', 'contpuc_descripcion' => 'Vagones', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1552'],
            ['contpuc_codigo' => '155215', 'contpuc_descripcion' => 'Redes férreas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1552'],
            ['contpuc_codigo' => '155295', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1552'],
            ['contpuc_codigo' => '155299', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1552'],
            ['contpuc_codigo' => '155605', 'contpuc_descripcion' => 'Instalaciones para agua y energía', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1556'],
            ['contpuc_codigo' => '155610', 'contpuc_descripcion' => 'Acueducto, acequias y canalizaciones', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1556'],
            ['contpuc_codigo' => '155615', 'contpuc_descripcion' => 'Plantas de generación hidráulica', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1556'],
            ['contpuc_codigo' => '155620', 'contpuc_descripcion' => 'Plantas de generación térmica', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1556'],
            ['contpuc_codigo' => '155625', 'contpuc_descripcion' => 'Plantas de generación a gas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1556'],
            ['contpuc_codigo' => '155628', 'contpuc_descripcion' => 'Plantas de generación diesel, gasolina y petróleo', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1556'],
            ['contpuc_codigo' => '155630', 'contpuc_descripcion' => 'Plantas de distribución', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1556'],
            ['contpuc_codigo' => '155635', 'contpuc_descripcion' => 'Plantas de transmisión y subestaciones', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1556'],
            ['contpuc_codigo' => '155640', 'contpuc_descripcion' => 'Oleoductos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1556'],
            ['contpuc_codigo' => '155645', 'contpuc_descripcion' => 'Gasoductos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1556'],
            ['contpuc_codigo' => '155647', 'contpuc_descripcion' => 'Poliductos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1556'],
            ['contpuc_codigo' => '155650', 'contpuc_descripcion' => 'Redes de distribución', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1556'],
            ['contpuc_codigo' => '155655', 'contpuc_descripcion' => 'Plantas de tratamiento', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1556'],
            ['contpuc_codigo' => '155660', 'contpuc_descripcion' => 'Redes de recolección de aguas negras', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1556'],
            ['contpuc_codigo' => '155665', 'contpuc_descripcion' => 'Instalaciones y equipo de bombeo', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1556'],
            ['contpuc_codigo' => '155670', 'contpuc_descripcion' => 'Redes de distribución de vapor', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1556'],
            ['contpuc_codigo' => '155675', 'contpuc_descripcion' => 'Redes de aire', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1556'],
            ['contpuc_codigo' => '155680', 'contpuc_descripcion' => 'Redes alimentación de gas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1556'],
            ['contpuc_codigo' => '155682', 'contpuc_descripcion' => 'Redes externas de telefonía', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1556'],
            ['contpuc_codigo' => '155685', 'contpuc_descripcion' => 'Plantas deshidratadoras', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1556'],
            ['contpuc_codigo' => '155695', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1556'],
            ['contpuc_codigo' => '155699', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1556'],
            ['contpuc_codigo' => '156099', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1560'],
            ['contpuc_codigo' => '156299', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1562'],
            ['contpuc_codigo' => '156405', 'contpuc_descripcion' => 'Cultivos en desarrollo', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1564'],
            ['contpuc_codigo' => '156410', 'contpuc_descripcion' => 'Cultivos amortizables', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1564'],
            ['contpuc_codigo' => '156499', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1564'],
            ['contpuc_codigo' => '156805', 'contpuc_descripcion' => 'Pavimentación y patios', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1568'],
            ['contpuc_codigo' => '156810', 'contpuc_descripcion' => 'Vías', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1568'],
            ['contpuc_codigo' => '156815', 'contpuc_descripcion' => 'Puentes', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1568'],
            ['contpuc_codigo' => '156820', 'contpuc_descripcion' => 'Calles', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1568'],
            ['contpuc_codigo' => '156825', 'contpuc_descripcion' => 'Aeródromos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1568'],
            ['contpuc_codigo' => '156895', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1568'],
            ['contpuc_codigo' => '156899', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1568'],
            ['contpuc_codigo' => '157205', 'contpuc_descripcion' => 'Minas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1572'],
            ['contpuc_codigo' => '157210', 'contpuc_descripcion' => 'Canteras', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1572'],
            ['contpuc_codigo' => '157299', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1572'],
            ['contpuc_codigo' => '157699', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1576'],
            ['contpuc_codigo' => '158099', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1580'],
            ['contpuc_codigo' => '158499', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1584'],
            ['contpuc_codigo' => '158805', 'contpuc_descripcion' => 'Maquinaria y equipo', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1588'],
            ['contpuc_codigo' => '158810', 'contpuc_descripcion' => 'Equipo de oficina', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1588'],
            ['contpuc_codigo' => '158815', 'contpuc_descripcion' => 'Equipo de computación y comunicación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1588'],
            ['contpuc_codigo' => '158820', 'contpuc_descripcion' => 'Equipo médico-científico', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1588'],
            ['contpuc_codigo' => '158825', 'contpuc_descripcion' => 'Equipo de hoteles y restaurantes', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1588'],
            ['contpuc_codigo' => '158830', 'contpuc_descripcion' => 'Flota y equipo de transporte', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1588'],
            ['contpuc_codigo' => '158835', 'contpuc_descripcion' => 'Flota y equipo fluvial y/o marítimo', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1588'],
            ['contpuc_codigo' => '158840', 'contpuc_descripcion' => 'Flota y equipo aéreo', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1588'],
            ['contpuc_codigo' => '158845', 'contpuc_descripcion' => 'Flota y equipo férreo', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1588'],
            ['contpuc_codigo' => '158850', 'contpuc_descripcion' => 'Plantas y redes', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1588'],
            ['contpuc_codigo' => '158855', 'contpuc_descripcion' => 'Armamento de vigilancia', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1588'],
            ['contpuc_codigo' => '158860', 'contpuc_descripcion' => 'Semovientes', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1588'],
            ['contpuc_codigo' => '158865', 'contpuc_descripcion' => 'Envases y empaques', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1588'],
            ['contpuc_codigo' => '158899', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1588'],
            ['contpuc_codigo' => '159205', 'contpuc_descripcion' => 'Construcciones y edificaciones', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1592'],
            ['contpuc_codigo' => '159210', 'contpuc_descripcion' => 'Maquinaria y equipo', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1592'],
            ['contpuc_codigo' => '159215', 'contpuc_descripcion' => 'Equipo de oficina', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1592'],
            ['contpuc_codigo' => '159220', 'contpuc_descripcion' => 'Equipo de computación y comunicación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1592'],
            ['contpuc_codigo' => '159225', 'contpuc_descripcion' => 'Equipo médico-científico', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1592'],
            ['contpuc_codigo' => '159230', 'contpuc_descripcion' => 'Equipo de hoteles y restaurantes', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1592'],
            ['contpuc_codigo' => '159235', 'contpuc_descripcion' => 'Flota y equipo de transporte', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1592'],
            ['contpuc_codigo' => '159240', 'contpuc_descripcion' => 'Flota y equipo fluvial y/o marítimo', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1592'],
            ['contpuc_codigo' => '159245', 'contpuc_descripcion' => 'Flota y equipo aéreo', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1592'],
            ['contpuc_codigo' => '159250', 'contpuc_descripcion' => 'Flota y equipo férreo', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1592'],
            ['contpuc_codigo' => '159255', 'contpuc_descripcion' => 'Acueductos, plantas y redes', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1592'],
            ['contpuc_codigo' => '159260', 'contpuc_descripcion' => 'Armamento de vigilancia', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1592'],
            ['contpuc_codigo' => '159265', 'contpuc_descripcion' => 'Envases y empaques', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1592'],
            ['contpuc_codigo' => '159299', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1592'],
            ['contpuc_codigo' => '159605', 'contpuc_descripcion' => 'Exceso fiscal sobre la contable', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1596'],
            ['contpuc_codigo' => '159610', 'contpuc_descripcion' => 'Defecto fiscal sobre la contable (CR)', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1596'],
            ['contpuc_codigo' => '159699', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1596'],
            ['contpuc_codigo' => '159705', 'contpuc_descripcion' => 'Plantaciones agrícolas y forestales', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1597'],
            ['contpuc_codigo' => '159710', 'contpuc_descripcion' => 'Vías de comunicación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1597'],
            ['contpuc_codigo' => '159715', 'contpuc_descripcion' => 'Semovientes', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1597'],
            ['contpuc_codigo' => '159799', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1597'],
            ['contpuc_codigo' => '159805', 'contpuc_descripcion' => 'Minas y canteras', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1598'],
            ['contpuc_codigo' => '159815', 'contpuc_descripcion' => 'Pozos artesianos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1598'],
            ['contpuc_codigo' => '159820', 'contpuc_descripcion' => 'Yacimientos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1598'],
            ['contpuc_codigo' => '159899', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1598'],
            ['contpuc_codigo' => '159904', 'contpuc_descripcion' => 'Terrenos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1599'],
            ['contpuc_codigo' => '159906', 'contpuc_descripcion' => 'Materiales proyectos petroleros', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1599'],
            ['contpuc_codigo' => '159908', 'contpuc_descripcion' => 'Construcciones en curso', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1599'],
            ['contpuc_codigo' => '159912', 'contpuc_descripcion' => 'Maquinaria en montaje', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1599'],
            ['contpuc_codigo' => '159916', 'contpuc_descripcion' => 'Construcciones y edificaciones', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1599'],
            ['contpuc_codigo' => '159920', 'contpuc_descripcion' => 'Maquinaria y equipo', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1599'],
            ['contpuc_codigo' => '159924', 'contpuc_descripcion' => 'Equipo de oficina', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1599'],
            ['contpuc_codigo' => '159928', 'contpuc_descripcion' => 'Equipo de computación y comunicación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1599'],
            ['contpuc_codigo' => '159932', 'contpuc_descripcion' => 'Equipo médico-científico', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1599'],
            ['contpuc_codigo' => '159936', 'contpuc_descripcion' => 'Equipo de hoteles y restaurantes', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1599'],
            ['contpuc_codigo' => '159940', 'contpuc_descripcion' => 'Flota y equipo de transporte', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1599'],
            ['contpuc_codigo' => '159944', 'contpuc_descripcion' => 'Flota y equipo fluvial y/o marítimo', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1599'],
            ['contpuc_codigo' => '159948', 'contpuc_descripcion' => 'Flota y equipo aéreo', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1599'],
            ['contpuc_codigo' => '159952', 'contpuc_descripcion' => 'Flota y equipo férreo', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1599'],
            ['contpuc_codigo' => '159956', 'contpuc_descripcion' => 'Acueductos, plantas y redes', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1599'],
            ['contpuc_codigo' => '159960', 'contpuc_descripcion' => 'Armamento de vigilancia', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1599'],
            ['contpuc_codigo' => '159962', 'contpuc_descripcion' => 'Envases y empaques', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1599'],
            ['contpuc_codigo' => '159964', 'contpuc_descripcion' => 'Plantaciones agrícolas y forestales', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1599'],
            ['contpuc_codigo' => '159968', 'contpuc_descripcion' => 'Vías de comunicación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1599'],
            ['contpuc_codigo' => '159972', 'contpuc_descripcion' => 'Minas y canteras', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1599'],
            ['contpuc_codigo' => '159980', 'contpuc_descripcion' => 'Pozos artesianos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1599'],
            ['contpuc_codigo' => '159984', 'contpuc_descripcion' => 'Yacimientos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1599'],
            ['contpuc_codigo' => '159988', 'contpuc_descripcion' => 'Semovientes', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1599'],
            ['contpuc_codigo' => '159992', 'contpuc_descripcion' => 'Propiedades, planta y equipo en tránsito', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1599'],
            ['contpuc_codigo' => '160505', 'contpuc_descripcion' => 'Formado o estimado', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1605'],
            ['contpuc_codigo' => '160510', 'contpuc_descripcion' => 'Adquirido o comprado', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1605'],
            ['contpuc_codigo' => '160599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1605'],
            ['contpuc_codigo' => '161005', 'contpuc_descripcion' => 'Adquiridas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1610'],
            ['contpuc_codigo' => '161010', 'contpuc_descripcion' => 'Formadas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1610'],
            ['contpuc_codigo' => '161099', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1610'],
            ['contpuc_codigo' => '161505', 'contpuc_descripcion' => 'Adquiridas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1615'],
            ['contpuc_codigo' => '161510', 'contpuc_descripcion' => 'Formadas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1615'],
            ['contpuc_codigo' => '161599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1615'],
            ['contpuc_codigo' => '162005', 'contpuc_descripcion' => 'Concesiones', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1620'],
            ['contpuc_codigo' => '162010', 'contpuc_descripcion' => 'Franquicias', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1620'],
            ['contpuc_codigo' => '162099', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1620'],
            ['contpuc_codigo' => '162505', 'contpuc_descripcion' => 'Derechos de autor', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1625'],
            ['contpuc_codigo' => '162510', 'contpuc_descripcion' => 'Puesto de bolsa', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1625'],
            ['contpuc_codigo' => '162515', 'contpuc_descripcion' => 'En fideicomisos inmobiliarios', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1625'],
            ['contpuc_codigo' => '162520', 'contpuc_descripcion' => 'En fideicomisos de garantía', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1625'],
            ['contpuc_codigo' => '162525', 'contpuc_descripcion' => 'En fideicomisos de administración', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1625'],
            ['contpuc_codigo' => '162530', 'contpuc_descripcion' => 'De exhibición - películas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1625'],
            ['contpuc_codigo' => '162535', 'contpuc_descripcion' => 'En bienes recibidos en arrendamiento financiero (leasing)', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1625'],
            ['contpuc_codigo' => '162595', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1625'],
            ['contpuc_codigo' => '162599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1625'],
            ['contpuc_codigo' => '163099', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1630'],
            ['contpuc_codigo' => '163599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1635'],
            ['contpuc_codigo' => '169805', 'contpuc_descripcion' => 'Crédito mercantil', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1698'],
            ['contpuc_codigo' => '169810', 'contpuc_descripcion' => 'Marcas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1698'],
            ['contpuc_codigo' => '169815', 'contpuc_descripcion' => 'Patentes', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1698'],
            ['contpuc_codigo' => '169820', 'contpuc_descripcion' => 'Concesiones y franquicias', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1698'],
            ['contpuc_codigo' => '169830', 'contpuc_descripcion' => 'Derechos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1698'],
            ['contpuc_codigo' => '169835', 'contpuc_descripcion' => 'Know how', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1698'],
            ['contpuc_codigo' => '169840', 'contpuc_descripcion' => 'Licencias', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1698'],
            ['contpuc_codigo' => '169899', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1698'],
            ['contpuc_codigo' => '170505', 'contpuc_descripcion' => 'Intereses', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1705'],
            ['contpuc_codigo' => '170510', 'contpuc_descripcion' => 'Honorarios', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1705'],
            ['contpuc_codigo' => '170515', 'contpuc_descripcion' => 'Comisiones', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1705'],
            ['contpuc_codigo' => '170520', 'contpuc_descripcion' => 'Seguros y fianzas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1705'],
            ['contpuc_codigo' => '170525', 'contpuc_descripcion' => 'Arrendamientos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1705'],
            ['contpuc_codigo' => '170530', 'contpuc_descripcion' => 'Bodegajes', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1705'],
            ['contpuc_codigo' => '170535', 'contpuc_descripcion' => 'Mantenimiento equipos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1705'],
            ['contpuc_codigo' => '170540', 'contpuc_descripcion' => 'Servicios', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1705'],
            ['contpuc_codigo' => '170545', 'contpuc_descripcion' => 'Suscripciones', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1705'],
            ['contpuc_codigo' => '170595', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1705'],
            ['contpuc_codigo' => '171004', 'contpuc_descripcion' => 'Organización y preoperativos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1710'],
            ['contpuc_codigo' => '171008', 'contpuc_descripcion' => 'Remodelaciones', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1710'],
            ['contpuc_codigo' => '171012', 'contpuc_descripcion' => 'Estudios, investigaciones y proyectos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1710'],
            ['contpuc_codigo' => '171016', 'contpuc_descripcion' => 'Programas para computador (software)', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1710'],
            ['contpuc_codigo' => '171020', 'contpuc_descripcion' => 'Útiles y papelería', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1710'],
            ['contpuc_codigo' => '171024', 'contpuc_descripcion' => 'Mejoras a propiedades ajenas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1710'],
            ['contpuc_codigo' => '171028', 'contpuc_descripcion' => 'Contribuciones y afiliaciones', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1710'],
            ['contpuc_codigo' => '171032', 'contpuc_descripcion' => 'Entrenamiento de personal', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1710'],
            ['contpuc_codigo' => '171036', 'contpuc_descripcion' => 'Ferias y exposiciones', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1710'],
            ['contpuc_codigo' => '171040', 'contpuc_descripcion' => 'Licencias', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1710'],
            ['contpuc_codigo' => '171044', 'contpuc_descripcion' => 'Publicidad, propaganda y promoción', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1710'],
            ['contpuc_codigo' => '171048', 'contpuc_descripcion' => 'Elementos de aseo y cafetería', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1710'],
            ['contpuc_codigo' => '171052', 'contpuc_descripcion' => 'Moldes y troqueles', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1710'],
            ['contpuc_codigo' => '171056', 'contpuc_descripcion' => 'Instrumental quirúrgico', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1710'],
            ['contpuc_codigo' => '171060', 'contpuc_descripcion' => 'Dotación y suministro a trabajadores', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1710'],
            ['contpuc_codigo' => '171064', 'contpuc_descripcion' => 'Elementos de ropería y lencería', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1710'],
            ['contpuc_codigo' => '171068', 'contpuc_descripcion' => 'Loza y cristalería', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1710'],
            ['contpuc_codigo' => '171069', 'contpuc_descripcion' => 'Platería', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1710'],
            ['contpuc_codigo' => '171070', 'contpuc_descripcion' => 'Cubiertería', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1710'],
            ['contpuc_codigo' => '171076', 'contpuc_descripcion' => 'Impuesto de renta diferido ?débitos? por diferencias temporales', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1710'],
            ['contpuc_codigo' => '171080', 'contpuc_descripcion' => 'Concursos y licitaciones', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1710'],
            ['contpuc_codigo' => '171095', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1710'],
            ['contpuc_codigo' => '171099', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1710'],
            ['contpuc_codigo' => '171505', 'contpuc_descripcion' => 'Pozos secos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1715'],
            ['contpuc_codigo' => '171510', 'contpuc_descripcion' => 'Pozos no comerciales', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1715'],
            ['contpuc_codigo' => '171515', 'contpuc_descripcion' => 'Otros costos de exploración', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1715'],
            ['contpuc_codigo' => '171599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1715'],
            ['contpuc_codigo' => '172005', 'contpuc_descripcion' => 'Perforación y explotación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1720'],
            ['contpuc_codigo' => '172010', 'contpuc_descripcion' => 'Perforaciones campos en desarrollo', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1720'],
            ['contpuc_codigo' => '172015', 'contpuc_descripcion' => 'Facilidades de producción', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1720'],
            ['contpuc_codigo' => '172020', 'contpuc_descripcion' => 'Servicio a pozos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1720'],
            ['contpuc_codigo' => '172099', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1720'],
            ['contpuc_codigo' => '179805', 'contpuc_descripcion' => 'Costos de exploración por amortizar', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1798'],
            ['contpuc_codigo' => '179810', 'contpuc_descripcion' => 'Costos de explotación y desarrollo', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1798'],
            ['contpuc_codigo' => '179899', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1798'],
            ['contpuc_codigo' => '180505', 'contpuc_descripcion' => 'Obras de arte', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1805'],
            ['contpuc_codigo' => '180510', 'contpuc_descripcion' => 'Bibliotecas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1805'],
            ['contpuc_codigo' => '180595', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1805'],
            ['contpuc_codigo' => '180599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1805'],
            ['contpuc_codigo' => '189505', 'contpuc_descripcion' => 'Máquinas porteadoras', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1895'],
            ['contpuc_codigo' => '189510', 'contpuc_descripcion' => 'Bienes entregados en comodato', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1895'],
            ['contpuc_codigo' => '189515', 'contpuc_descripcion' => 'Amortización acumulada de bienes entregados en comodato (CR)', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1895'],
            ['contpuc_codigo' => '189520', 'contpuc_descripcion' => 'Bienes recibidos en pago', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1895'],
            ['contpuc_codigo' => '189525', 'contpuc_descripcion' => 'Derechos sucesorales', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1895'],
            ['contpuc_codigo' => '189530', 'contpuc_descripcion' => 'Estampillas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1895'],
            ['contpuc_codigo' => '189595', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1895'],
            ['contpuc_codigo' => '189599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1895'],
            ['contpuc_codigo' => '189905', 'contpuc_descripcion' => 'Bienes de arte y cultura', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1899'],
            ['contpuc_codigo' => '189995', 'contpuc_descripcion' => 'Diversos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1899'],
            ['contpuc_codigo' => '190505', 'contpuc_descripcion' => 'Acciones', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1905'],
            ['contpuc_codigo' => '190510', 'contpuc_descripcion' => 'Cuotas o partes de interés social', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1905'],
            ['contpuc_codigo' => '190515', 'contpuc_descripcion' => 'Derechos fiduciarios', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1905'],
            ['contpuc_codigo' => '191004', 'contpuc_descripcion' => 'Terrenos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1910'],
            ['contpuc_codigo' => '191006', 'contpuc_descripcion' => 'Materiales proyectos petroleros', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1910'],
            ['contpuc_codigo' => '191008', 'contpuc_descripcion' => 'Construcciones y edificaciones', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1910'],
            ['contpuc_codigo' => '191012', 'contpuc_descripcion' => 'Maquinaria y equipo', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1910'],
            ['contpuc_codigo' => '191016', 'contpuc_descripcion' => 'Equipo de oficina', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1910'],
            ['contpuc_codigo' => '191020', 'contpuc_descripcion' => 'Equipo de computación y comunicación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1910'],
            ['contpuc_codigo' => '191024', 'contpuc_descripcion' => 'Equipo médico-científico', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1910'],
            ['contpuc_codigo' => '191028', 'contpuc_descripcion' => 'Equipo de hoteles y restaurantes', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1910'],
            ['contpuc_codigo' => '191032', 'contpuc_descripcion' => 'Flota y equipo de transporte', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1910'],
            ['contpuc_codigo' => '191036', 'contpuc_descripcion' => 'Flota y equipo fluvial y/o marítimo', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1910'],
            ['contpuc_codigo' => '191040', 'contpuc_descripcion' => 'Flota y equipo aéreo', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1910'],
            ['contpuc_codigo' => '191044', 'contpuc_descripcion' => 'Flota y equipo férreo', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1910'],
            ['contpuc_codigo' => '191048', 'contpuc_descripcion' => 'Acueductos, plantas y redes', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1910'],
            ['contpuc_codigo' => '191052', 'contpuc_descripcion' => 'Armamento de vigilancia', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1910'],
            ['contpuc_codigo' => '191056', 'contpuc_descripcion' => 'Envases y empaques', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1910'],
            ['contpuc_codigo' => '191060', 'contpuc_descripcion' => 'Plantaciones agrícolas y forestales', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1910'],
            ['contpuc_codigo' => '191064', 'contpuc_descripcion' => 'Vías de comunicación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1910'],
            ['contpuc_codigo' => '191068', 'contpuc_descripcion' => 'Minas y canteras', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1910'],
            ['contpuc_codigo' => '191072', 'contpuc_descripcion' => 'Pozos artesianos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1910'],
            ['contpuc_codigo' => '191076', 'contpuc_descripcion' => 'Yacimientos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1910'],
            ['contpuc_codigo' => '191080', 'contpuc_descripcion' => 'Semovientes', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1910'],
            ['contpuc_codigo' => '199505', 'contpuc_descripcion' => 'Bienes de arte y cultura', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1995'],
            ['contpuc_codigo' => '199510', 'contpuc_descripcion' => 'Bienes entregados en comodato', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1995'],
            ['contpuc_codigo' => '199515', 'contpuc_descripcion' => 'Bienes recibidos en pago', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1995'],
            ['contpuc_codigo' => '199520', 'contpuc_descripcion' => 'Inventario de semovientes', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '1995'],
        ];

        $fecha = Carbon::now();

        foreach ($cuentasContrapartida as $cuenta) {
            $parentPUC = PUC::where('puc_codigo', $cuenta['parent_puc_codigo'])->first();

            if (!$parentPUC) {
                Log::warning("Parent PUC with code " . $cuenta['parent_puc_codigo'] . " not found for contrapartida " . $cuenta['contpuc_codigo'] . ". Skipping.");
                $this->command->error("Parent PUC with code " . $cuenta['parent_puc_codigo'] . " not found for contrapartida " . $cuenta['contpuc_codigo'] . ". Skipping.");
                continue;
            }

            ContrapartidaPUC::firstOrCreate(
                ['contpuc_codigo' => $cuenta['contpuc_codigo']], // Check if already exists
                [
                    'contpuc_descripcion' => $cuenta['contpuc_descripcion'],
                    'contpuc_tipo' => $cuenta['contpuc_tipo'],
                    'puc_idpuc' => $parentPUC->idpuc,
                    'estado' => 'Activo',
                    'fecha_registro' => $fecha,
                ]
            );
        }

        $this->command->info('ContrapartidaPUC Seeder for Activo (Class 1) ran successfully!');
    }
}
