<?php

namespace Database\Seeders;

use App\Models\ContrapartidaPUC;
use App\Models\PUC; // To lookup parent PUC ID
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\Log; // For logging if parent PUC not found

class ContrapartidaPUCCostosDeVentaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cuentasContrapartida = [
            ['contpuc_codigo' => '610505', 'contpuc_descripcion' => 'Cultivo de cereales', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6105'],
            ['contpuc_codigo' => '610510', 'contpuc_descripcion' => 'Cultivos de hortalizas, legumbres y plantas ornamentales', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6105'],
            ['contpuc_codigo' => '610515', 'contpuc_descripcion' => 'Cultivos de frutas, nueces y plantas aromáticas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6105'],
            ['contpuc_codigo' => '610520', 'contpuc_descripcion' => 'Cultivo de café', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6105'],
            ['contpuc_codigo' => '610525', 'contpuc_descripcion' => 'Cultivo de flores', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6105'],
            ['contpuc_codigo' => '610530', 'contpuc_descripcion' => 'Cultivo de caña de azúcar', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6105'],
            ['contpuc_codigo' => '610535', 'contpuc_descripcion' => 'Cultivo de algodón y plantas para material textil', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6105'],
            ['contpuc_codigo' => '610540', 'contpuc_descripcion' => 'Cultivo de banano', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6105'],
            ['contpuc_codigo' => '610545', 'contpuc_descripcion' => 'Otros cultivos agrícolas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6105'],
            ['contpuc_codigo' => '610550', 'contpuc_descripcion' => 'Cría de ovejas, cabras, asnos, mulas y burdéganos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6105'],
            ['contpuc_codigo' => '610555', 'contpuc_descripcion' => 'Cría de ganado caballar y vacuno', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6105'],
            ['contpuc_codigo' => '610560', 'contpuc_descripcion' => 'Producción avícola', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6105'],
            ['contpuc_codigo' => '610565', 'contpuc_descripcion' => 'Cría de otros animales', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6105'],
            ['contpuc_codigo' => '610570', 'contpuc_descripcion' => 'Servicios agrícolas y ganaderos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6105'],
            ['contpuc_codigo' => '610575', 'contpuc_descripcion' => 'Actividad de caza', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6105'],
            ['contpuc_codigo' => '610580', 'contpuc_descripcion' => 'Actividad de silvicultura', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6105'],
            ['contpuc_codigo' => '610595', 'contpuc_descripcion' => 'Actividades conexas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6105'],
            ['contpuc_codigo' => '610599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6105'],
            ['contpuc_codigo' => '611005', 'contpuc_descripcion' => 'Actividad de pesca', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6110'],
            ['contpuc_codigo' => '611010', 'contpuc_descripcion' => 'Explotación de criaderos de peces', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6110'],
            ['contpuc_codigo' => '611095', 'contpuc_descripcion' => 'Actividades conexas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6110'],
            ['contpuc_codigo' => '611099', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6110'],
            ['contpuc_codigo' => '611505', 'contpuc_descripcion' => 'Carbón', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6115'],
            ['contpuc_codigo' => '611510', 'contpuc_descripcion' => 'Petróleo crudo', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6115'],
            ['contpuc_codigo' => '611512', 'contpuc_descripcion' => 'Gas natural', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6115'],
            ['contpuc_codigo' => '611514', 'contpuc_descripcion' => 'Servicios relacionados con extracción de petróleo y gas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6115'],
            ['contpuc_codigo' => '611515', 'contpuc_descripcion' => 'Minerales de hierro', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6115'],
            ['contpuc_codigo' => '611520', 'contpuc_descripcion' => 'Minerales metalíferos no ferrosos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6115'],
            ['contpuc_codigo' => '611525', 'contpuc_descripcion' => 'Piedra, arena y arcilla', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6115'],
            ['contpuc_codigo' => '611527', 'contpuc_descripcion' => 'Piedras preciosas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6115'],
            ['contpuc_codigo' => '611528', 'contpuc_descripcion' => 'Oro', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6115'],
            ['contpuc_codigo' => '611530', 'contpuc_descripcion' => 'Otras minas y canteras', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6115'],
            ['contpuc_codigo' => '611532', 'contpuc_descripcion' => 'Prestación de servicios sector minero', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6115'],
            ['contpuc_codigo' => '611595', 'contpuc_descripcion' => 'Actividades conexas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6115'],
            ['contpuc_codigo' => '611599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6115'],
            ['contpuc_codigo' => '612001', 'contpuc_descripcion' => 'Producción y procesamiento de carnes y productos cárnicos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612002', 'contpuc_descripcion' => 'Productos de pescado', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612003', 'contpuc_descripcion' => 'Productos de frutas, legumbres y hortalizas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612004', 'contpuc_descripcion' => 'Elaboración de aceites y grasas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612005', 'contpuc_descripcion' => 'Elaboración  de productos lácteos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612006', 'contpuc_descripcion' => 'Elaboración de productos de molinería', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612007', 'contpuc_descripcion' => 'Elaboración de almidones y derivados', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612008', 'contpuc_descripcion' => 'Elaboración de alimentos para animales', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612009', 'contpuc_descripcion' => 'Elaboración de productos para panadería', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612010', 'contpuc_descripcion' => 'Elaboración de azúcar y melazas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612011', 'contpuc_descripcion' => 'Elaboración de cacao, chocolate y confitería', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612012', 'contpuc_descripcion' => 'Elaboración  de pastas y productos farináceos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612013', 'contpuc_descripcion' => 'Elaboración de productos de café', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612014', 'contpuc_descripcion' => 'Elaboración de otros productos alimenticios', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612015', 'contpuc_descripcion' => 'Elaboración de bebidas alcohólicas y alcohol etílico', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612016', 'contpuc_descripcion' => 'Elaboración de vinos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612017', 'contpuc_descripcion' => 'Elaboración de bebidas malteadas y de malta', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612018', 'contpuc_descripcion' => 'Elaboración de bebidas no alcohólicas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612019', 'contpuc_descripcion' => 'Elaboración de productos de tabaco', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612020', 'contpuc_descripcion' => 'Preparación e hilatura de fibras textiles y tejeduría', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612021', 'contpuc_descripcion' => 'Acabado de productos textiles', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612022', 'contpuc_descripcion' => 'Elaboración de artículos de materiales textiles', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612023', 'contpuc_descripcion' => 'Elaboración de tapices y alfombras', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612024', 'contpuc_descripcion' => 'Elaboración de cuerdas, cordeles, bramantes y redes', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612025', 'contpuc_descripcion' => 'Elaboración de otros productos textiles', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612026', 'contpuc_descripcion' => 'Elaboración de tejidos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612027', 'contpuc_descripcion' => 'Elaboración de prendas de vestir', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612028', 'contpuc_descripcion' => 'Preparación, adobo y teñido de pieles', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612029', 'contpuc_descripcion' => 'Curtido, adobo o preparación de cuero', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612030', 'contpuc_descripcion' => 'Elaboración de maletas, bolsos y similares', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612031', 'contpuc_descripcion' => 'Elaboración de calzado', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612032', 'contpuc_descripcion' => 'Producción de madera, artículos de madera y corcho', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612033', 'contpuc_descripcion' => 'Elaboración de pasta y productos de madera, papel y cartón', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612034', 'contpuc_descripcion' => 'Ediciones y publicaciones', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612035', 'contpuc_descripcion' => 'Impresión', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612036', 'contpuc_descripcion' => 'Servicios relacionados con la edición y la impresión', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612037', 'contpuc_descripcion' => 'Reproducción de grabaciones', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612038', 'contpuc_descripcion' => 'Elaboración de productos de horno de coque', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612039', 'contpuc_descripcion' => 'Elaboración de productos de la refinación de petróleo', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612040', 'contpuc_descripcion' => 'Elaboración de sustancias químicas básicas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612041', 'contpuc_descripcion' => 'Elaboración de abonos y compuestos de nitrógeno', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612042', 'contpuc_descripcion' => 'Elaboración de plástico y caucho sintético', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612043', 'contpuc_descripcion' => 'Elaboración de productos químicos de uso agropecuario', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612044', 'contpuc_descripcion' => 'Elaboración de pinturas, tintas y masillas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612045', 'contpuc_descripcion' => 'Elaboración de productos farmacéuticos y botánicos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612046', 'contpuc_descripcion' => 'Elaboración de jabones, detergentes y preparados de tocador', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612047', 'contpuc_descripcion' => 'Elaboración de otros productos químicos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612048', 'contpuc_descripcion' => 'Elaboración de fibras', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612049', 'contpuc_descripcion' => 'Elaboración de otros productos de caucho', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612050', 'contpuc_descripcion' => 'Elaboración de productos de plástico', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612051', 'contpuc_descripcion' => 'Elaboración de vidrio y productos de vidrio', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612052', 'contpuc_descripcion' => 'Elaboración de productos de cerámica, loza, piedra, arcilla y porcelana', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612053', 'contpuc_descripcion' => 'Elaboración de cemento, cal y yeso', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612054', 'contpuc_descripcion' => 'Elaboración de artículos de hormigón, cemento y yeso', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612055', 'contpuc_descripcion' => 'Corte, tallado y acabado de la piedra', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612056', 'contpuc_descripcion' => 'Elaboración de otros productos minerales no metálicos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612057', 'contpuc_descripcion' => 'Industrias básicas y fundición de hierro y acero', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612058', 'contpuc_descripcion' => 'Productos primarios de metales preciosos y de metales no ferrosos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612059', 'contpuc_descripcion' => 'Fundición de metales no ferrosos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612060', 'contpuc_descripcion' => 'Fabricación de productos metálicos para uso estructural', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612061', 'contpuc_descripcion' => 'Forja, prensado, estampado, laminado de metal y pulvimetalurgia', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612062', 'contpuc_descripcion' => 'Revestimiento de metales y obras de ingeniería mecánica', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612063', 'contpuc_descripcion' => 'Fabricación de artículos de ferretería', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612064', 'contpuc_descripcion' => 'Elaboración de otros productos de metal', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612065', 'contpuc_descripcion' => 'Fabricación de maquinaria y equipo', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612066', 'contpuc_descripcion' => 'Fabricación de equipos de elevación y manipulación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612067', 'contpuc_descripcion' => 'Elaboración de aparatos de uso doméstico', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612068', 'contpuc_descripcion' => 'Elaboración de equipo de oficina', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612069', 'contpuc_descripcion' => 'Elaboración de pilas y baterías primarias', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612070', 'contpuc_descripcion' => 'Elaboración de equipo de iluminación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612071', 'contpuc_descripcion' => 'Elaboración de otros tipos de equipo eléctrico', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612072', 'contpuc_descripcion' => 'Fabricación de equipos de radio, televisión y comunicaciones', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612073', 'contpuc_descripcion' => 'Fabricación de aparatos e instrumentos médicos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612074', 'contpuc_descripcion' => 'Fabricación de instrumentos de medición y control', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612075', 'contpuc_descripcion' => 'Fabricación de instrumentos de óptica y equipo fotográfico', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612076', 'contpuc_descripcion' => 'Fabricación de relojes', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612077', 'contpuc_descripcion' => 'Fabricación de vehículos automotores', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612078', 'contpuc_descripcion' => 'Fabricación de carrocerías para automotores', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612079', 'contpuc_descripcion' => 'Fabricación de partes, piezas y accesorios para automotores', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612080', 'contpuc_descripcion' => 'Fabricación y reparación de buques y otras embarcaciones', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612081', 'contpuc_descripcion' => 'Fabricación de locomotoras y material rodante para ferrocarriles', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612082', 'contpuc_descripcion' => 'Fabricación de aeronaves', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612083', 'contpuc_descripcion' => 'Fabricación de motocicletas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612084', 'contpuc_descripcion' => 'Fabricación de bicicletas y sillas de ruedas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612085', 'contpuc_descripcion' => 'Fabricación de otros tipos de transporte', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612086', 'contpuc_descripcion' => 'Fabricación de muebles', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612087', 'contpuc_descripcion' => 'Fabricación de joyas y artículos conexos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612088', 'contpuc_descripcion' => 'Fabricación de instrumentos de música', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612089', 'contpuc_descripcion' => 'Fabricación de artículos y equipo para deporte', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612090', 'contpuc_descripcion' => 'Fabricación de juegos y juguetes', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612091', 'contpuc_descripcion' => 'Reciclamiento de desperdicios', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612095', 'contpuc_descripcion' => 'Productos de otras industrias manufactureras', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612099', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6120'],
            ['contpuc_codigo' => '612505', 'contpuc_descripcion' => 'Generación, captación y distribución de energía eléctrica', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6125'],
            ['contpuc_codigo' => '612510', 'contpuc_descripcion' => 'Fabricación de gas y distribución de combustibles gaseosos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6125'],
            ['contpuc_codigo' => '612515', 'contpuc_descripcion' => 'Captación, depuración y distribución de agua', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6125'],
            ['contpuc_codigo' => '612595', 'contpuc_descripcion' => 'Actividades conexas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6125'],
            ['contpuc_codigo' => '612599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6125'],
            ['contpuc_codigo' => '613005', 'contpuc_descripcion' => 'Preparación de terrenos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6130'],
            ['contpuc_codigo' => '613010', 'contpuc_descripcion' => 'Construcción de edificios y obras de ingeniería civil', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6130'],
            ['contpuc_codigo' => '613015', 'contpuc_descripcion' => 'Acondicionamiento de edificios', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6130'],
            ['contpuc_codigo' => '613020', 'contpuc_descripcion' => 'Terminación de edificaciones', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6130'],
            ['contpuc_codigo' => '613025', 'contpuc_descripcion' => 'Alquiler de equipo con operario', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6130'],
            ['contpuc_codigo' => '613095', 'contpuc_descripcion' => 'Actividades conexas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6130'],
            ['contpuc_codigo' => '613099', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6130'],
            ['contpuc_codigo' => '613502', 'contpuc_descripcion' => 'Venta de vehículos automotores', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6135'],
            ['contpuc_codigo' => '613504', 'contpuc_descripcion' => 'Mantenimiento, reparación y lavado de vehículos automotores', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6135'],
            ['contpuc_codigo' => '613506', 'contpuc_descripcion' => 'Venta de partes, piezas y accesorios de vehículos automotores', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6135'],
            ['contpuc_codigo' => '613508', 'contpuc_descripcion' => 'Venta  de combustibles sólidos, líquidos, gaseosos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6135'],
            ['contpuc_codigo' => '613510', 'contpuc_descripcion' => 'Venta de lubricantes, aditivos, llantas y lujos para automotores', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6135'],
            ['contpuc_codigo' => '613512', 'contpuc_descripcion' => 'Venta a cambio de retribución o por contrata', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6135'],
            ['contpuc_codigo' => '613514', 'contpuc_descripcion' => 'Venta de insumos, materias primas agropecuarias y flores', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6135'],
            ['contpuc_codigo' => '613516', 'contpuc_descripcion' => 'Venta de otros insumos y materias primas no agropecuarias', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6135'],
            ['contpuc_codigo' => '613518', 'contpuc_descripcion' => 'Venta de animales vivos y cueros', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6135'],
            ['contpuc_codigo' => '613520', 'contpuc_descripcion' => 'Venta de productos en almacenes no especializados', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6135'],
            ['contpuc_codigo' => '613522', 'contpuc_descripcion' => 'Venta de productos agropecuarios', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6135'],
            ['contpuc_codigo' => '613524', 'contpuc_descripcion' => 'Venta de productos textiles, de vestir, de cuero y calzado', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6135'],
            ['contpuc_codigo' => '613526', 'contpuc_descripcion' => 'Venta de papel y cartón', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6135'],
            ['contpuc_codigo' => '613528', 'contpuc_descripcion' => 'Venta de libros, revistas, elementos de papelería, útiles y textos escolares', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6135'],
            ['contpuc_codigo' => '613530', 'contpuc_descripcion' => 'Venta de juegos, juguetes y artículos deportivos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6135'],
            ['contpuc_codigo' => '613532', 'contpuc_descripcion' => 'Venta de instrumentos quirúrgicos y ortopédicos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6135'],
            ['contpuc_codigo' => '613534', 'contpuc_descripcion' => 'Venta de artículos en relojerías y joyerías', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6135'],
            ['contpuc_codigo' => '613536', 'contpuc_descripcion' => 'Venta de electrodomésticos y muebles', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6135'],
            ['contpuc_codigo' => '613538', 'contpuc_descripcion' => 'Venta de productos de aseo, farmacéuticos,  medicinales y artículos de tocador', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6135'],
            ['contpuc_codigo' => '613540', 'contpuc_descripcion' => 'Venta de cubiertos, vajillas, cristalería, porcelanas, cerámicas y otros artículos de uso doméstico', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6135'],
            ['contpuc_codigo' => '613542', 'contpuc_descripcion' => 'Venta de materiales de construcción, fontanería y calefacción', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6135'],
            ['contpuc_codigo' => '613544', 'contpuc_descripcion' => 'Venta de pinturas y lacas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6135'],
            ['contpuc_codigo' => '613546', 'contpuc_descripcion' => 'Venta de productos de vidrios y marquetería', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6135'],
            ['contpuc_codigo' => '613548', 'contpuc_descripcion' => 'Venta de herramientas y artículos de ferretería', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6135'],
            ['contpuc_codigo' => '613550', 'contpuc_descripcion' => 'Venta de químicos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6135'],
            ['contpuc_codigo' => '613552', 'contpuc_descripcion' => 'Venta de productos intermedios, desperdicios y desechos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6135'],
            ['contpuc_codigo' => '613554', 'contpuc_descripcion' => 'Venta de maquinaria, equipo de oficina y programas de computador', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6135'],
            ['contpuc_codigo' => '613556', 'contpuc_descripcion' => 'Venta de artículos en cacharrerías y misceláneas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6135'],
            ['contpuc_codigo' => '613558', 'contpuc_descripcion' => 'Venta de instrumentos musicales', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6135'],
            ['contpuc_codigo' => '613560', 'contpuc_descripcion' => 'Venta de artículos en casas de empeño y prenderías', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6135'],
            ['contpuc_codigo' => '613562', 'contpuc_descripcion' => 'Venta de equipo fotográfico', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6135'],
            ['contpuc_codigo' => '613564', 'contpuc_descripcion' => 'Venta de equipo óptico y de precisión', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6135'],
            ['contpuc_codigo' => '613566', 'contpuc_descripcion' => 'Venta de empaques', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6135'],
            ['contpuc_codigo' => '613568', 'contpuc_descripcion' => 'Venta de equipo profesional y científico', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6135'],
            ['contpuc_codigo' => '613570', 'contpuc_descripcion' => 'Venta de loterías, rifas, chance, apuestas y similares', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6135'],
            ['contpuc_codigo' => '613572', 'contpuc_descripcion' => 'Reparación de efectos personales y electrodomésticos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6135'],
            ['contpuc_codigo' => '613595', 'contpuc_descripcion' => 'Venta de otros productos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6135'],
            ['contpuc_codigo' => '613599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6135'],
            ['contpuc_codigo' => '614005', 'contpuc_descripcion' => 'Hotelería', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6140'],
            ['contpuc_codigo' => '614010', 'contpuc_descripcion' => 'Campamento y otros tipos de hospedaje', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6140'],
            ['contpuc_codigo' => '614015', 'contpuc_descripcion' => 'Restaurantes', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6140'],
            ['contpuc_codigo' => '614020', 'contpuc_descripcion' => 'Bares y cantinas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6140'],
            ['contpuc_codigo' => '614095', 'contpuc_descripcion' => 'Actividades conexas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6140'],
            ['contpuc_codigo' => '614099', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6140'],
            ['contpuc_codigo' => '614505', 'contpuc_descripcion' => 'Servicio de transporte por carretera', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6145'],
            ['contpuc_codigo' => '614510', 'contpuc_descripcion' => 'Servicio de transporte por vía férrea', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6145'],
            ['contpuc_codigo' => '614515', 'contpuc_descripcion' => 'Servicio de transporte por vía acuática', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6145'],
            ['contpuc_codigo' => '614520', 'contpuc_descripcion' => 'Servicio de transporte por vía aérea', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6145'],
            ['contpuc_codigo' => '614525', 'contpuc_descripcion' => 'Servicio de transporte por tuberías', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6145'],
            ['contpuc_codigo' => '614530', 'contpuc_descripcion' => 'Manipulación de carga', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6145'],
            ['contpuc_codigo' => '614535', 'contpuc_descripcion' => 'Almacenamiento y depósito', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6145'],
            ['contpuc_codigo' => '614540', 'contpuc_descripcion' => 'Servicios complementarios para el transporte', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6145'],
            ['contpuc_codigo' => '614545', 'contpuc_descripcion' => 'Agencias de viaje', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6145'],
            ['contpuc_codigo' => '614550', 'contpuc_descripcion' => 'Otras agencias de transporte', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6145'],
            ['contpuc_codigo' => '614555', 'contpuc_descripcion' => 'Servicio postal y de correo', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6145'],
            ['contpuc_codigo' => '614560', 'contpuc_descripcion' => 'Servicio telefónico', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6145'],
            ['contpuc_codigo' => '614565', 'contpuc_descripcion' => 'Servicio de telégrafo', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6145'],
            ['contpuc_codigo' => '614570', 'contpuc_descripcion' => 'Servicio de transmisión de datos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6145'],
            ['contpuc_codigo' => '614575', 'contpuc_descripcion' => 'Servicio de radio y televisión por cable', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6145'],
            ['contpuc_codigo' => '614580', 'contpuc_descripcion' => 'Transmisión de sonido e imágenes por contrato', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6145'],
            ['contpuc_codigo' => '614595', 'contpuc_descripcion' => 'Actividades conexas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6145'],
            ['contpuc_codigo' => '614599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6145'],
            ['contpuc_codigo' => '615005', 'contpuc_descripcion' => 'De inversiones', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6150'],
            ['contpuc_codigo' => '615010', 'contpuc_descripcion' => 'De servicio de bolsa', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6150'],
            ['contpuc_codigo' => '615099', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6150'],
            ['contpuc_codigo' => '615505', 'contpuc_descripcion' => 'Arrendamientos de bienes inmuebles', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6155'],
            ['contpuc_codigo' => '615510', 'contpuc_descripcion' => 'Inmobiliarias por retribución o contrata', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6155'],
            ['contpuc_codigo' => '615515', 'contpuc_descripcion' => 'Alquiler equipo de transporte', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6155'],
            ['contpuc_codigo' => '615520', 'contpuc_descripcion' => 'Alquiler maquinaria y equipo', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6155'],
            ['contpuc_codigo' => '615525', 'contpuc_descripcion' => 'Alquiler de efectos personales y enseres domésticos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6155'],
            ['contpuc_codigo' => '615530', 'contpuc_descripcion' => 'Consultoría en equipo y programas de informática', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6155'],
            ['contpuc_codigo' => '615535', 'contpuc_descripcion' => 'Procesamiento de datos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6155'],
            ['contpuc_codigo' => '615540', 'contpuc_descripcion' => 'Mantenimiento y reparación de maquinaria de oficina', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6155'],
            ['contpuc_codigo' => '615545', 'contpuc_descripcion' => 'Investigaciones científicas y de desarrollo', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6155'],
            ['contpuc_codigo' => '615550', 'contpuc_descripcion' => 'Actividades empresariales de consultoría', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6155'],
            ['contpuc_codigo' => '615555', 'contpuc_descripcion' => 'Publicidad', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6155'],
            ['contpuc_codigo' => '615560', 'contpuc_descripcion' => 'Dotación de personal', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6155'],
            ['contpuc_codigo' => '615565', 'contpuc_descripcion' => 'Investigación y seguridad', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6155'],
            ['contpuc_codigo' => '615570', 'contpuc_descripcion' => 'Limpieza de inmuebles', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6155'],
            ['contpuc_codigo' => '615575', 'contpuc_descripcion' => 'Fotografía', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6155'],
            ['contpuc_codigo' => '615580', 'contpuc_descripcion' => 'Envase y empaque', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6155'],
            ['contpuc_codigo' => '615585', 'contpuc_descripcion' => 'Fotocopiado', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6155'],
            ['contpuc_codigo' => '615590', 'contpuc_descripcion' => 'Mantenimiento y reparación de maquinaria y  equipo', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6155'],
            ['contpuc_codigo' => '615595', 'contpuc_descripcion' => 'Actividades conexas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6155'],
            ['contpuc_codigo' => '615599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6155'],
            ['contpuc_codigo' => '616005', 'contpuc_descripcion' => 'Actividades relacionadas con la educación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6160'],
            ['contpuc_codigo' => '616095', 'contpuc_descripcion' => 'Actividades conexas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6160'],
            ['contpuc_codigo' => '616099', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6160'],
            ['contpuc_codigo' => '616505', 'contpuc_descripcion' => 'Servicio hospitalario', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6165'],
            ['contpuc_codigo' => '616510', 'contpuc_descripcion' => 'Servicio médico', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6165'],
            ['contpuc_codigo' => '616515', 'contpuc_descripcion' => 'Servicio odontológico', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6165'],
            ['contpuc_codigo' => '616520', 'contpuc_descripcion' => 'Servicio de laboratorio', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6165'],
            ['contpuc_codigo' => '616525', 'contpuc_descripcion' => 'Actividades veterinarias', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6165'],
            ['contpuc_codigo' => '616530', 'contpuc_descripcion' => 'Actividades de servicios sociales', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6165'],
            ['contpuc_codigo' => '616595', 'contpuc_descripcion' => 'Actividades conexas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6165'],
            ['contpuc_codigo' => '616599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6165'],
            ['contpuc_codigo' => '617005', 'contpuc_descripcion' => 'Eliminación de desperdicios y aguas residuales', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6170'],
            ['contpuc_codigo' => '617010', 'contpuc_descripcion' => 'Actividades de asociación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6170'],
            ['contpuc_codigo' => '617015', 'contpuc_descripcion' => 'Producción y distribución de filmes y videocintas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6170'],
            ['contpuc_codigo' => '617020', 'contpuc_descripcion' => 'Exhibición de filmes y videocintas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6170'],
            ['contpuc_codigo' => '617025', 'contpuc_descripcion' => 'Actividad de radio y televisión', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6170'],
            ['contpuc_codigo' => '617030', 'contpuc_descripcion' => 'Actividad teatral, musical y artística', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6170'],
            ['contpuc_codigo' => '617035', 'contpuc_descripcion' => 'Grabación y producción de discos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6170'],
            ['contpuc_codigo' => '617040', 'contpuc_descripcion' => 'Entretenimiento y esparcimiento', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6170'],
            ['contpuc_codigo' => '617045', 'contpuc_descripcion' => 'Agencias de noticias', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6170'],
            ['contpuc_codigo' => '617050', 'contpuc_descripcion' => 'Lavanderías y similares', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6170'],
            ['contpuc_codigo' => '617055', 'contpuc_descripcion' => 'Peluquerías y similares', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6170'],
            ['contpuc_codigo' => '617060', 'contpuc_descripcion' => 'Servicios funerarios', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6170'],
            ['contpuc_codigo' => '617065', 'contpuc_descripcion' => 'Zonas francas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6170'],
            ['contpuc_codigo' => '617095', 'contpuc_descripcion' => 'Actividades conexas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6170'],
            ['contpuc_codigo' => '617099', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6170'],
            ['contpuc_codigo' => '620599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6205'],
            ['contpuc_codigo' => '621099', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6210'],
            ['contpuc_codigo' => '621599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6215'],
            ['contpuc_codigo' => '622099', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6220'],
            ['contpuc_codigo' => '622599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '6225'],
        ];

        $fecha = Carbon::now();

        foreach ($cuentasContrapartida as $cuenta) {
            $parentPUC = PUC::where('puc_codigo', $cuenta['parent_puc_codigo'])->first();

            if (!$parentPUC) {
                Log::warning("Parent PUC with code " . $cuenta['parent_puc_codigo'] . " not found for contrapartida " . $cuenta['contpuc_codigo'] . ". Skipping.");
                $this->command->error("Parent PUC with code " . $cuenta['parent_puc_codigo'] . " not found for contrapartida " . $cuenta['contpuc_codigo'] . ". Skipping.");
                continue;
            }

            ContrapartidaPUC::firstOrCreate(
                ['contpuc_codigo' => $cuenta['contpuc_codigo']], // Check if already exists
                [
                    'contpuc_descripcion' => $cuenta['contpuc_descripcion'],
                    'contpuc_tipo' => $cuenta['contpuc_tipo'],
                    'puc_idpuc' => $parentPUC->idpuc,
                    'estado' => 'Activo',
                    'fecha_registro' => $fecha,
                ]
            );
        }
        
        $this->command->info('ContrapartidaPUC Seeder for CostosDeVenta (Class 6) ran successfully!');
    }
}
