<?php

namespace Database\Seeders;

use App\Models\ContrapartidaPUC;
use App\Models\PUC; // To lookup parent PUC ID
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\Log; // For logging if parent PUC not found

class ContrapartidaPUCIngresosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cuentasContrapartida = [
            ['contpuc_codigo' => '410505', 'contpuc_descripcion' => 'Cultivo de cereales', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4105'],
            ['contpuc_codigo' => '410510', 'contpuc_descripcion' => 'Cultivos de hortalizas, legumbres y plantas ornamentales', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4105'],
            ['contpuc_codigo' => '410515', 'contpuc_descripcion' => 'Cultivos de frutas, nueces y plantas aromáticas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4105'],
            ['contpuc_codigo' => '410520', 'contpuc_descripcion' => 'Cultivo de café', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4105'],
            ['contpuc_codigo' => '410525', 'contpuc_descripcion' => 'Cultivo de flores', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4105'],
            ['contpuc_codigo' => '410530', 'contpuc_descripcion' => 'Cultivo de caña de azúcar', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4105'],
            ['contpuc_codigo' => '410535', 'contpuc_descripcion' => 'Cultivo de algodón y plantas para material textil', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4105'],
            ['contpuc_codigo' => '410540', 'contpuc_descripcion' => 'Cultivo de banano', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4105'],
            ['contpuc_codigo' => '410545', 'contpuc_descripcion' => 'Otros cultivos agrícolas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4105'],
            ['contpuc_codigo' => '410550', 'contpuc_descripcion' => 'Cría de ovejas, cabras, asnos, mulas y burdéganos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4105'],
            ['contpuc_codigo' => '410555', 'contpuc_descripcion' => 'Cría de ganado caballar y vacuno', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4105'],
            ['contpuc_codigo' => '410560', 'contpuc_descripcion' => 'Producción avícola', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4105'],
            ['contpuc_codigo' => '410565', 'contpuc_descripcion' => 'Cría de otros animales', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4105'],
            ['contpuc_codigo' => '410570', 'contpuc_descripcion' => 'Servicios agrícolas y ganaderos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4105'],
            ['contpuc_codigo' => '410575', 'contpuc_descripcion' => 'Actividad de caza', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4105'],
            ['contpuc_codigo' => '410580', 'contpuc_descripcion' => 'Actividad de silvicultura', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4105'],
            ['contpuc_codigo' => '410595', 'contpuc_descripcion' => 'Actividades conexas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4105'],
            ['contpuc_codigo' => '410599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4105'],
            ['contpuc_codigo' => '411005', 'contpuc_descripcion' => 'Actividad de pesca', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4110'],
            ['contpuc_codigo' => '411010', 'contpuc_descripcion' => 'Explotación de criaderos de peces', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4110'],
            ['contpuc_codigo' => '411095', 'contpuc_descripcion' => 'Actividades conexas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4110'],
            ['contpuc_codigo' => '411099', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4110'],
            ['contpuc_codigo' => '411505', 'contpuc_descripcion' => 'Carbón', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4115'],
            ['contpuc_codigo' => '411510', 'contpuc_descripcion' => 'Petróleo crudo', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4115'],
            ['contpuc_codigo' => '411512', 'contpuc_descripcion' => 'Gas natural', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4115'],
            ['contpuc_codigo' => '411514', 'contpuc_descripcion' => 'Servicios relacionados con extracción de petróleo y gas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4115'],
            ['contpuc_codigo' => '411515', 'contpuc_descripcion' => 'Minerales de hierro', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4115'],
            ['contpuc_codigo' => '411520', 'contpuc_descripcion' => 'Minerales metalíferos no ferrosos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4115'],
            ['contpuc_codigo' => '411525', 'contpuc_descripcion' => 'Piedra, arena y arcilla', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4115'],
            ['contpuc_codigo' => '411527', 'contpuc_descripcion' => 'Piedras preciosas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4115'],
            ['contpuc_codigo' => '411528', 'contpuc_descripcion' => 'Oro', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4115'],
            ['contpuc_codigo' => '411530', 'contpuc_descripcion' => 'Otras minas y canteras', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4115'],
            ['contpuc_codigo' => '411532', 'contpuc_descripcion' => 'Prestación de servicios sector minero', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4115'],
            ['contpuc_codigo' => '411595', 'contpuc_descripcion' => 'Actividades conexas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4115'],
            ['contpuc_codigo' => '411599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4115'],
            ['contpuc_codigo' => '412001', 'contpuc_descripcion' => 'Producción y procesamiento de carnes y productos cárnicos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412002', 'contpuc_descripcion' => 'Productos de pescado', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412003', 'contpuc_descripcion' => 'Productos de frutas, legumbres y hortalizas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412004', 'contpuc_descripcion' => 'Elaboración de aceites y grasas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412005', 'contpuc_descripcion' => 'Elaboración de productos lácteos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412006', 'contpuc_descripcion' => 'Elaboración de productos de molinería', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412007', 'contpuc_descripcion' => 'Elaboración de almidones y derivados', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412008', 'contpuc_descripcion' => 'Elaboración de alimentos para animales', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412009', 'contpuc_descripcion' => 'Elaboración de productos para panadería', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412010', 'contpuc_descripcion' => 'Elaboración de azúcar y melazas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412011', 'contpuc_descripcion' => 'Elaboración de cacao, chocolate y confitería', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412012', 'contpuc_descripcion' => 'Elaboración de pastas y productos farináceos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412013', 'contpuc_descripcion' => 'Elaboración de productos de café', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412014', 'contpuc_descripcion' => 'Elaboración de otros productos alimenticios', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412015', 'contpuc_descripcion' => 'Elaboración de bebidas alcohólicas y alcohol etílico', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412016', 'contpuc_descripcion' => 'Elaboración de vinos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412017', 'contpuc_descripcion' => 'Elaboración de bebidas malteadas y de malta', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412018', 'contpuc_descripcion' => 'Elaboración de bebidas no alcohólicas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412019', 'contpuc_descripcion' => 'Elaboración de productos de tabaco', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412020', 'contpuc_descripcion' => 'Preparación e hilatura de fibras textiles y tejeduría', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412021', 'contpuc_descripcion' => 'Acabado de productos textiles', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412022', 'contpuc_descripcion' => 'Elaboración de artículos de materiales textiles', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412023', 'contpuc_descripcion' => 'Elaboración de tapices y alfombras', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412024', 'contpuc_descripcion' => 'Elaboración de cuerdas, cordeles, bramantes y redes', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412025', 'contpuc_descripcion' => 'Elaboración de otros productos textiles', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412026', 'contpuc_descripcion' => 'Elaboración de tejidos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412027', 'contpuc_descripcion' => 'Elaboración de prendas de vestir', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412028', 'contpuc_descripcion' => 'Preparación, adobo y teñido de pieles', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412029', 'contpuc_descripcion' => 'Curtido, adobo o preparación de cuero', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412030', 'contpuc_descripcion' => 'Elaboración de maletas, bolsos y similares', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412031', 'contpuc_descripcion' => 'Elaboración de calzado', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412032', 'contpuc_descripcion' => 'Producción de madera, artículos de madera y corcho', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412033', 'contpuc_descripcion' => 'Elaboración de pasta y productos de madera, papel y cartón', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412034', 'contpuc_descripcion' => 'Ediciones y publicaciones', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412035', 'contpuc_descripcion' => 'Impresión', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412036', 'contpuc_descripcion' => 'Servicios relacionados con la edición y la impresión', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412037', 'contpuc_descripcion' => 'Reproducción de grabaciones', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412038', 'contpuc_descripcion' => 'Elaboración de productos de horno de coque', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412039', 'contpuc_descripcion' => 'Elaboración de productos de la refinación de petróleo', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412040', 'contpuc_descripcion' => 'Elaboración de sustancias químicas básicas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412041', 'contpuc_descripcion' => 'Elaboración de abonos y compuestos de nitrógeno', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412042', 'contpuc_descripcion' => 'Elaboración de plástico y caucho sintético', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412043', 'contpuc_descripcion' => 'Elaboración de productos químicos de uso agropecuario', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412044', 'contpuc_descripcion' => 'Elaboración de pinturas, tintas y masillas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412045', 'contpuc_descripcion' => 'Elaboración de productos farmacéuticos y botánicos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412046', 'contpuc_descripcion' => 'Elaboración de jabones, detergentes y preparados de tocador', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412047', 'contpuc_descripcion' => 'Elaboración de otros productos químicos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412048', 'contpuc_descripcion' => 'Elaboración de fibras', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412049', 'contpuc_descripcion' => 'Elaboración  de otros productos de caucho', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412050', 'contpuc_descripcion' => 'Elaboración  de productos de plástico', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412051', 'contpuc_descripcion' => 'Elaboración  de vidrio y productos de vidrio', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412052', 'contpuc_descripcion' => 'Elaboración  de productos de cerámica, loza, piedra, arcilla y porcelana', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412053', 'contpuc_descripcion' => 'Elaboración  de cemento, cal y yeso', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412054', 'contpuc_descripcion' => 'Elaboración  de artículos de hormigón, cemento y yeso', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412055', 'contpuc_descripcion' => 'Corte, tallado y acabado de la piedra', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412056', 'contpuc_descripcion' => 'Elaboración de otros productos minerales no metálicos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412057', 'contpuc_descripcion' => 'Industrias básicas y fundición de hierro y acero', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412058', 'contpuc_descripcion' => 'Productos primarios de metales preciosos y de metales no ferrosos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412059', 'contpuc_descripcion' => 'Fundición de metales no ferrosos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412060', 'contpuc_descripcion' => 'Fabricación de productos metálicos para uso estructural', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412061', 'contpuc_descripcion' => 'Forja, prensado, estampado, laminado de metal y pulvimetalurgia', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412062', 'contpuc_descripcion' => 'Revestimiento de metales y obras de ingeniería mecánica', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412063', 'contpuc_descripcion' => 'Fabricación de artículos de ferretería', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412064', 'contpuc_descripcion' => 'Elaboración de otros productos de metal', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412065', 'contpuc_descripcion' => 'Fabricación de maquinaria y equipo', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412066', 'contpuc_descripcion' => 'Fabricación de equipos de elevación y manipulación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412067', 'contpuc_descripcion' => 'Elaboración de aparatos de uso doméstico', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412068', 'contpuc_descripcion' => 'Elaboración de equipo de oficina', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412069', 'contpuc_descripcion' => 'Elaboración de pilas y baterías primarias', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412070', 'contpuc_descripcion' => 'Elaboración de equipo de iluminación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412071', 'contpuc_descripcion' => 'Elaboración de otros tipos de equipo eléctrico', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412072', 'contpuc_descripcion' => 'Fabricación de equipos de radio, televisión y comunicaciones', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412073', 'contpuc_descripcion' => 'Fabricación de aparatos e instrumentos médicos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412074', 'contpuc_descripcion' => 'Fabricación de instrumentos de medición y control', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412075', 'contpuc_descripcion' => 'Fabricación de instrumentos de óptica y equipo fotográfico', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412076', 'contpuc_descripcion' => 'Fabricación de relojes', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412077', 'contpuc_descripcion' => 'Fabricación de vehículos automotores', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412078', 'contpuc_descripcion' => 'Fabricación de carrocerías para automotores', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412079', 'contpuc_descripcion' => 'Fabricación de partes piezas y accesorios para automotores', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412080', 'contpuc_descripcion' => 'Fabricación y reparación de buques y otras embarcaciones', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412081', 'contpuc_descripcion' => 'Fabricación de locomotoras y material rodante para ferrocarriles', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412082', 'contpuc_descripcion' => 'Fabricación de aeronaves', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412083', 'contpuc_descripcion' => 'Fabricación de motocicletas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412084', 'contpuc_descripcion' => 'Fabricación de bicicletas y sillas de ruedas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412085', 'contpuc_descripcion' => 'Fabricación de otros tipos de transporte', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412086', 'contpuc_descripcion' => 'Fabricación de muebles', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412087', 'contpuc_descripcion' => 'Fabricación de joyas y artículos conexos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412088', 'contpuc_descripcion' => 'Fabricación de instrumentos de música', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412089', 'contpuc_descripcion' => 'Fabricación de artículos y equipo para deporte', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412090', 'contpuc_descripcion' => 'Fabricación de juegos y juguetes', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412091', 'contpuc_descripcion' => 'Reciclamiento de desperdicios', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412095', 'contpuc_descripcion' => 'Productos de otras industrias manufactureras', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412099', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4120'],
            ['contpuc_codigo' => '412505', 'contpuc_descripcion' => 'Generación, captación y distribución de energía eléctrica', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4125'],
            ['contpuc_codigo' => '412510', 'contpuc_descripcion' => 'Fabricación de gas y distribución de combustibles gaseosos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4125'],
            ['contpuc_codigo' => '412515', 'contpuc_descripcion' => 'Captación, depuración y distribución de agua', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4125'],
            ['contpuc_codigo' => '412595', 'contpuc_descripcion' => 'Actividades conexas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4125'],
            ['contpuc_codigo' => '412599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4125'],
            ['contpuc_codigo' => '413005', 'contpuc_descripcion' => 'Preparación de terrenos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4130'],
            ['contpuc_codigo' => '413010', 'contpuc_descripcion' => 'Construcción de edificios y obras de ingeniería civil', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4130'],
            ['contpuc_codigo' => '413015', 'contpuc_descripcion' => 'Acondicionamiento de edificios', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4130'],
            ['contpuc_codigo' => '413020', 'contpuc_descripcion' => 'Terminación de edificaciones', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4130'],
            ['contpuc_codigo' => '413025', 'contpuc_descripcion' => 'Alquiler de equipo con operarios', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4130'],
            ['contpuc_codigo' => '413095', 'contpuc_descripcion' => 'Actividades conexas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4130'],
            ['contpuc_codigo' => '413099', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4130'],
            ['contpuc_codigo' => '413502', 'contpuc_descripcion' => 'Venta de vehículos automotores', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4135'],
            ['contpuc_codigo' => '413504', 'contpuc_descripcion' => 'Mantenimiento, reparación y lavado de vehículos automotores', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4135'],
            ['contpuc_codigo' => '413506', 'contpuc_descripcion' => 'Venta de partes, piezas y accesorios de vehículos automotores', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4135'],
            ['contpuc_codigo' => '413508', 'contpuc_descripcion' => 'Venta de combustibles sólidos, líquidos, gaseosos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4135'],
            ['contpuc_codigo' => '413510', 'contpuc_descripcion' => 'Venta de lubricantes, aditivos, llantas y lujos para automotores', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4135'],
            ['contpuc_codigo' => '413512', 'contpuc_descripcion' => 'Venta a cambio de retribución o por contrata', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4135'],
            ['contpuc_codigo' => '413514', 'contpuc_descripcion' => 'Venta de insumos, materias primas agropecuarias y flores', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4135'],
            ['contpuc_codigo' => '413516', 'contpuc_descripcion' => 'Venta de otros insumos y materias primas no agropecuarias', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4135'],
            ['contpuc_codigo' => '413518', 'contpuc_descripcion' => 'Venta de animales vivos y cueros', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4135'],
            ['contpuc_codigo' => '413520', 'contpuc_descripcion' => 'Venta de productos en almacenes no especializados', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4135'],
            ['contpuc_codigo' => '413522', 'contpuc_descripcion' => 'Venta de productos agropecuarios', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4135'],
            ['contpuc_codigo' => '413524', 'contpuc_descripcion' => 'Venta de productos textiles, de vestir, de cuero y calzado', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4135'],
            ['contpuc_codigo' => '413526', 'contpuc_descripcion' => 'Venta de papel y cartón', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4135'],
            ['contpuc_codigo' => '413528', 'contpuc_descripcion' => 'Venta de libros, revistas, elementos de papelería, útiles y textos escolares', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4135'],
            ['contpuc_codigo' => '413530', 'contpuc_descripcion' => 'Venta de juegos, juguetes y artículos deportivos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4135'],
            ['contpuc_codigo' => '413532', 'contpuc_descripcion' => 'Venta de instrumentos quirúrgicos y ortopédicos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4135'],
            ['contpuc_codigo' => '413534', 'contpuc_descripcion' => 'Venta de artículos en relojerías y joyerías', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4135'],
            ['contpuc_codigo' => '413536', 'contpuc_descripcion' => 'Venta de electrodomésticos y muebles', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4135'],
            ['contpuc_codigo' => '413538', 'contpuc_descripcion' => 'Venta de productos de aseo, farmacéuticos, medicinales, y artículos de tocador', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4135'],
            ['contpuc_codigo' => '413540', 'contpuc_descripcion' => 'Venta de cubiertos, vajillas, cristalería, porcelanas, cerámicas y otros artículos de uso doméstico', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4135'],
            ['contpuc_codigo' => '413542', 'contpuc_descripcion' => 'Venta de materiales de construcción, fontanería y calefacción', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4135'],
            ['contpuc_codigo' => '413544', 'contpuc_descripcion' => 'Venta de pinturas y lacas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4135'],
            ['contpuc_codigo' => '413546', 'contpuc_descripcion' => 'Venta de productos de vidrios y marquetería', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4135'],
            ['contpuc_codigo' => '413548', 'contpuc_descripcion' => 'Venta de herramientas y artículos de ferretería', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4135'],
            ['contpuc_codigo' => '413550', 'contpuc_descripcion' => 'Venta de químicos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4135'],
            ['contpuc_codigo' => '413552', 'contpuc_descripcion' => 'Venta de productos intermedios, desperdicios y desechos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4135'],
            ['contpuc_codigo' => '413554', 'contpuc_descripcion' => 'Venta de maquinaria, equipo de oficina y programas de computador', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4135'],
            ['contpuc_codigo' => '413556', 'contpuc_descripcion' => 'Venta de artículos en cacharrerías y misceláneas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4135'],
            ['contpuc_codigo' => '413558', 'contpuc_descripcion' => 'Venta de instrumentos musicales', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4135'],
            ['contpuc_codigo' => '413560', 'contpuc_descripcion' => 'Venta de artículos en casas de empeño y prenderías', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4135'],
            ['contpuc_codigo' => '413562', 'contpuc_descripcion' => 'Venta de equipo fotográfico', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4135'],
            ['contpuc_codigo' => '413564', 'contpuc_descripcion' => 'Venta de equipo óptico y de precisión', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4135'],
            ['contpuc_codigo' => '413566', 'contpuc_descripcion' => 'Venta de empaques', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4135'],
            ['contpuc_codigo' => '413568', 'contpuc_descripcion' => 'Venta de equipo profesional y científico', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4135'],
            ['contpuc_codigo' => '413570', 'contpuc_descripcion' => 'Venta de loterías, rifas, chance, apuestas y similares', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4135'],
            ['contpuc_codigo' => '413572', 'contpuc_descripcion' => 'Reparación de efectos personales y electrodomésticos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4135'],
            ['contpuc_codigo' => '413595', 'contpuc_descripcion' => 'Venta de otros productos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4135'],
            ['contpuc_codigo' => '413599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4135'],
            ['contpuc_codigo' => '414005', 'contpuc_descripcion' => 'Hotelería', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4140'],
            ['contpuc_codigo' => '414010', 'contpuc_descripcion' => 'Campamento y otros tipos de hospedaje', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4140'],
            ['contpuc_codigo' => '414015', 'contpuc_descripcion' => 'Restaurantes', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4140'],
            ['contpuc_codigo' => '414020', 'contpuc_descripcion' => 'Bares y cantinas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4140'],
            ['contpuc_codigo' => '414095', 'contpuc_descripcion' => 'Actividades conexas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4140'],
            ['contpuc_codigo' => '414099', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4140'],
            ['contpuc_codigo' => '414505', 'contpuc_descripcion' => 'Servicio de transporte por carretera', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4145'],
            ['contpuc_codigo' => '414510', 'contpuc_descripcion' => 'Servicio de transporte por vía férrea', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4145'],
            ['contpuc_codigo' => '414515', 'contpuc_descripcion' => 'Servicio de transporte por vía acuática', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4145'],
            ['contpuc_codigo' => '414520', 'contpuc_descripcion' => 'Servicio de transporte por vía aérea', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4145'],
            ['contpuc_codigo' => '414525', 'contpuc_descripcion' => 'Servicio de transporte por tuberías', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4145'],
            ['contpuc_codigo' => '414530', 'contpuc_descripcion' => 'Manipulación de carga', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4145'],
            ['contpuc_codigo' => '414535', 'contpuc_descripcion' => 'Almacenamiento y depósito', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4145'],
            ['contpuc_codigo' => '414540', 'contpuc_descripcion' => 'Servicios complementarios para el transporte', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4145'],
            ['contpuc_codigo' => '414545', 'contpuc_descripcion' => 'Agencias de viaje', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4145'],
            ['contpuc_codigo' => '414550', 'contpuc_descripcion' => 'Otras agencias de transporte', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4145'],
            ['contpuc_codigo' => '414555', 'contpuc_descripcion' => 'Servicio postal y de correo', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4145'],
            ['contpuc_codigo' => '414560', 'contpuc_descripcion' => 'Servicio telefónico', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4145'],
            ['contpuc_codigo' => '414565', 'contpuc_descripcion' => 'Servicio de telégrafo', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4145'],
            ['contpuc_codigo' => '414570', 'contpuc_descripcion' => 'Servicio de transmisión de datos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4145'],
            ['contpuc_codigo' => '414575', 'contpuc_descripcion' => 'Servicio de radio y televisión por cable', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4145'],
            ['contpuc_codigo' => '414580', 'contpuc_descripcion' => 'Transmisión de sonido e imágenes por contrato', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4145'],
            ['contpuc_codigo' => '414595', 'contpuc_descripcion' => 'Actividades conexas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4145'],
            ['contpuc_codigo' => '414599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4145'],
            ['contpuc_codigo' => '415005', 'contpuc_descripcion' => 'Venta de inversiones', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4150'],
            ['contpuc_codigo' => '415010', 'contpuc_descripcion' => 'Dividendos de sociedades anónimas y/o asimiladas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4150'],
            ['contpuc_codigo' => '415015', 'contpuc_descripcion' => 'Participaciones de sociedades limitadas y/o asimiladas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4150'],
            ['contpuc_codigo' => '415020', 'contpuc_descripcion' => 'Intereses', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4150'],
            ['contpuc_codigo' => '415025', 'contpuc_descripcion' => 'Reajuste monetario-UPAC (hoy UVR)', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4150'],
            ['contpuc_codigo' => '415030', 'contpuc_descripcion' => 'Comisiones', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4150'],
            ['contpuc_codigo' => '415035', 'contpuc_descripcion' => 'Operaciones de descuento', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4150'],
            ['contpuc_codigo' => '415040', 'contpuc_descripcion' => 'Cuotas de inscripción-consorcios', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4150'],
            ['contpuc_codigo' => '415045', 'contpuc_descripcion' => 'Cuotas de administración-consorcios', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4150'],
            ['contpuc_codigo' => '415050', 'contpuc_descripcion' => 'Reajuste del sistema-consorcios', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4150'],
            ['contpuc_codigo' => '415055', 'contpuc_descripcion' => 'Eliminación de suscriptores-consorcios', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4150'],
            ['contpuc_codigo' => '415060', 'contpuc_descripcion' => 'Cuotas de ingreso o retiro-sociedad administradora', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4150'],
            ['contpuc_codigo' => '415065', 'contpuc_descripcion' => 'Servicios a comisionistas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4150'],
            ['contpuc_codigo' => '415070', 'contpuc_descripcion' => 'Inscripciones y cuotas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4150'],
            ['contpuc_codigo' => '415075', 'contpuc_descripcion' => 'Recuperación de garantías', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4150'],
            ['contpuc_codigo' => '415080', 'contpuc_descripcion' => 'Ingresos método de participación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4150'],
            ['contpuc_codigo' => '415095', 'contpuc_descripcion' => 'Actividades conexas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4150'],
            ['contpuc_codigo' => '415099', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4150'],
            ['contpuc_codigo' => '415505', 'contpuc_descripcion' => 'Arrendamientos de bienes inmuebles', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4155'],
            ['contpuc_codigo' => '415510', 'contpuc_descripcion' => 'Inmobiliarias por retribución o contrata', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4155'],
            ['contpuc_codigo' => '415515', 'contpuc_descripcion' => 'Alquiler equipo de transporte', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4155'],
            ['contpuc_codigo' => '415520', 'contpuc_descripcion' => 'Alquiler maquinaria y equipo', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4155'],
            ['contpuc_codigo' => '415525', 'contpuc_descripcion' => 'Alquiler de efectos personales y enseres domésticos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4155'],
            ['contpuc_codigo' => '415530', 'contpuc_descripcion' => 'Consultoría en equipo y programas de informática', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4155'],
            ['contpuc_codigo' => '415535', 'contpuc_descripcion' => 'Procesamiento de datos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4155'],
            ['contpuc_codigo' => '415540', 'contpuc_descripcion' => 'Mantenimiento y reparación de maquinaria de oficina', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4155'],
            ['contpuc_codigo' => '415545', 'contpuc_descripcion' => 'Investigaciones científicas y de desarrollo', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4155'],
            ['contpuc_codigo' => '415550', 'contpuc_descripcion' => 'Actividades empresariales de consultoría', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4155'],
            ['contpuc_codigo' => '415555', 'contpuc_descripcion' => 'Publicidad', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4155'],
            ['contpuc_codigo' => '415560', 'contpuc_descripcion' => 'Dotación de personal', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4155'],
            ['contpuc_codigo' => '415565', 'contpuc_descripcion' => 'Investigación y seguridad', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4155'],
            ['contpuc_codigo' => '415570', 'contpuc_descripcion' => 'Limpieza de inmuebles', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4155'],
            ['contpuc_codigo' => '415575', 'contpuc_descripcion' => 'Fotografía', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4155'],
            ['contpuc_codigo' => '415580', 'contpuc_descripcion' => 'Envase y empaque', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4155'],
            ['contpuc_codigo' => '415585', 'contpuc_descripcion' => 'Fotocopiado', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4155'],
            ['contpuc_codigo' => '415590', 'contpuc_descripcion' => 'Mantenimiento y reparación de maquinaria y equipo', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4155'],
            ['contpuc_codigo' => '415595', 'contpuc_descripcion' => 'Actividades conexas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4155'],
            ['contpuc_codigo' => '415599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4155'],
            ['contpuc_codigo' => '416005', 'contpuc_descripcion' => 'Actividades relacionadas con la educación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4160'],
            ['contpuc_codigo' => '416095', 'contpuc_descripcion' => 'Actividades conexas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4160'],
            ['contpuc_codigo' => '416099', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4160'],
            ['contpuc_codigo' => '416505', 'contpuc_descripcion' => 'Servicio hospitalario', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4165'],
            ['contpuc_codigo' => '416510', 'contpuc_descripcion' => 'Servicio médico', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4165'],
            ['contpuc_codigo' => '416515', 'contpuc_descripcion' => 'Servicio odontológico', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4165'],
            ['contpuc_codigo' => '416520', 'contpuc_descripcion' => 'Servicio de laboratorio', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4165'],
            ['contpuc_codigo' => '416525', 'contpuc_descripcion' => 'Actividades veterinarias', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4165'],
            ['contpuc_codigo' => '416530', 'contpuc_descripcion' => 'Actividades de servicios sociales', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4165'],
            ['contpuc_codigo' => '416595', 'contpuc_descripcion' => 'Actividades conexas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4165'],
            ['contpuc_codigo' => '416599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4165'],
            ['contpuc_codigo' => '417005', 'contpuc_descripcion' => 'Eliminación de desperdicios y aguas residuales', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4170'],
            ['contpuc_codigo' => '417010', 'contpuc_descripcion' => 'Actividades de asociación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4170'],
            ['contpuc_codigo' => '417015', 'contpuc_descripcion' => 'Producción y distribución de filmes y videocintas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4170'],
            ['contpuc_codigo' => '417020', 'contpuc_descripcion' => 'Exhibición de filmes y videocintas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4170'],
            ['contpuc_codigo' => '417025', 'contpuc_descripcion' => 'Actividad de radio y televisión', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4170'],
            ['contpuc_codigo' => '417030', 'contpuc_descripcion' => 'Actividad teatral, musical y artística', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4170'],
            ['contpuc_codigo' => '417035', 'contpuc_descripcion' => 'Grabación y producción de discos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4170'],
            ['contpuc_codigo' => '417040', 'contpuc_descripcion' => 'Entretenimiento y esparcimiento', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4170'],
            ['contpuc_codigo' => '417045', 'contpuc_descripcion' => 'Agencias de noticias', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4170'],
            ['contpuc_codigo' => '417050', 'contpuc_descripcion' => 'Lavanderías y similares', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4170'],
            ['contpuc_codigo' => '417055', 'contpuc_descripcion' => 'Peluquerías y similares', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4170'],
            ['contpuc_codigo' => '417060', 'contpuc_descripcion' => 'Servicios funerarios', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4170'],
            ['contpuc_codigo' => '417065', 'contpuc_descripcion' => 'Zonas francas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4170'],
            ['contpuc_codigo' => '417095', 'contpuc_descripcion' => 'Actividades conexas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4170'],
            ['contpuc_codigo' => '417099', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4170'],
            ['contpuc_codigo' => '417599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4175'],
            ['contpuc_codigo' => '420505', 'contpuc_descripcion' => 'Materia prima', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4205'],
            ['contpuc_codigo' => '420510', 'contpuc_descripcion' => 'Material de desecho', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4205'],
            ['contpuc_codigo' => '420515', 'contpuc_descripcion' => 'Materiales varios', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4205'],
            ['contpuc_codigo' => '420520', 'contpuc_descripcion' => 'Productos de diversificación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4205'],
            ['contpuc_codigo' => '420525', 'contpuc_descripcion' => 'Excedentes de exportación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4205'],
            ['contpuc_codigo' => '420530', 'contpuc_descripcion' => 'Envases y empaques', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4205'],
            ['contpuc_codigo' => '420535', 'contpuc_descripcion' => 'Productos agrícolas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4205'],
            ['contpuc_codigo' => '420540', 'contpuc_descripcion' => 'De propaganda', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4205'],
            ['contpuc_codigo' => '420545', 'contpuc_descripcion' => 'Productos en remate', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4205'],
            ['contpuc_codigo' => '420550', 'contpuc_descripcion' => 'Combustibles y lubricantes', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4205'],
            ['contpuc_codigo' => '420599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4205'],
            ['contpuc_codigo' => '421005', 'contpuc_descripcion' => 'Intereses', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4210'],
            ['contpuc_codigo' => '421010', 'contpuc_descripcion' => 'Reajuste monetario-UPAC (hoy UVR)', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4210'],
            ['contpuc_codigo' => '421015', 'contpuc_descripcion' => 'Descuentos amortizados', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4210'],
            ['contpuc_codigo' => '421020', 'contpuc_descripcion' => 'Diferencia en cambio', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4210'],
            ['contpuc_codigo' => '421025', 'contpuc_descripcion' => 'Financiación vehículos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4210'],
            ['contpuc_codigo' => '421030', 'contpuc_descripcion' => 'Financiación sistemas de viajes', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4210'],
            ['contpuc_codigo' => '421035', 'contpuc_descripcion' => 'Aceptaciones bancarias', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4210'],
            ['contpuc_codigo' => '421040', 'contpuc_descripcion' => 'Descuentos comerciales condicionados', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4210'],
            ['contpuc_codigo' => '421045', 'contpuc_descripcion' => 'Descuentos bancarios', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4210'],
            ['contpuc_codigo' => '421050', 'contpuc_descripcion' => 'Comisiones cheques de otras plazas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4210'],
            ['contpuc_codigo' => '421055', 'contpuc_descripcion' => 'Multas y recargos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4210'],
            ['contpuc_codigo' => '421060', 'contpuc_descripcion' => 'Sanciones cheques devueltos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4210'],
            ['contpuc_codigo' => '421095', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4210'],
            ['contpuc_codigo' => '421099', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4210'],
            ['contpuc_codigo' => '421505', 'contpuc_descripcion' => 'De sociedades anónimas y/o asimiladas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4215'],
            ['contpuc_codigo' => '421510', 'contpuc_descripcion' => 'De sociedades limitadas y/o asimiladas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4215'],
            ['contpuc_codigo' => '421599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4215'],
            ['contpuc_codigo' => '421805', 'contpuc_descripcion' => 'De sociedades anónimas y/o asimiladas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4218'],
            ['contpuc_codigo' => '421810', 'contpuc_descripcion' => 'De sociedades limitadas y/o asimiladas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4218'],
            ['contpuc_codigo' => '422005', 'contpuc_descripcion' => 'Terrenos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4220'],
            ['contpuc_codigo' => '422010', 'contpuc_descripcion' => 'Construcciones y edificios', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4220'],
            ['contpuc_codigo' => '422015', 'contpuc_descripcion' => 'Maquinaria y equipo', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4220'],
            ['contpuc_codigo' => '422020', 'contpuc_descripcion' => 'Equipo de oficina', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4220'],
            ['contpuc_codigo' => '422025', 'contpuc_descripcion' => 'Equipo de computación y comunicación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4220'],
            ['contpuc_codigo' => '422030', 'contpuc_descripcion' => 'Equipo médico-científico', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4220'],
            ['contpuc_codigo' => '422035', 'contpuc_descripcion' => 'Equipo de hoteles y restaurantes', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4220'],
            ['contpuc_codigo' => '422040', 'contpuc_descripcion' => 'Flota y equipo de transporte', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4220'],
            ['contpuc_codigo' => '422045', 'contpuc_descripcion' => 'Flota y equipo fluvial y/o marítimo', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4220'],
            ['contpuc_codigo' => '422050', 'contpuc_descripcion' => 'Flota y equipo aéreo', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4220'],
            ['contpuc_codigo' => '422055', 'contpuc_descripcion' => 'Flota y equipo férreo', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4220'],
            ['contpuc_codigo' => '422060', 'contpuc_descripcion' => 'Acueductos, plantas y redes', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4220'],
            ['contpuc_codigo' => '422062', 'contpuc_descripcion' => 'Envases y empaques', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4220'],
            ['contpuc_codigo' => '422065', 'contpuc_descripcion' => 'Plantaciones agrícolas y forestales', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4220'],
            ['contpuc_codigo' => '422070', 'contpuc_descripcion' => 'Aeródromos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4220'],
            ['contpuc_codigo' => '422075', 'contpuc_descripcion' => 'Semovientes', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4220'],
            ['contpuc_codigo' => '422099', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4220'],
            ['contpuc_codigo' => '422505', 'contpuc_descripcion' => 'Sobre inversiones', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4225'],
            ['contpuc_codigo' => '422510', 'contpuc_descripcion' => 'De concesionarios', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4225'],
            ['contpuc_codigo' => '422515', 'contpuc_descripcion' => 'De actividades financieras', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4225'],
            ['contpuc_codigo' => '422520', 'contpuc_descripcion' => 'Por venta de servicios de taller', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4225'],
            ['contpuc_codigo' => '422525', 'contpuc_descripcion' => 'Por venta de seguros', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4225'],
            ['contpuc_codigo' => '422530', 'contpuc_descripcion' => 'Por ingresos para terceros', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4225'],
            ['contpuc_codigo' => '422535', 'contpuc_descripcion' => 'Por distribución de películas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4225'],
            ['contpuc_codigo' => '422540', 'contpuc_descripcion' => 'Derechos de autor', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4225'],
            ['contpuc_codigo' => '422545', 'contpuc_descripcion' => 'Derechos de programación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4225'],
            ['contpuc_codigo' => '422599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4225'],
            ['contpuc_codigo' => '423005', 'contpuc_descripcion' => 'Asesorías', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4230'],
            ['contpuc_codigo' => '423010', 'contpuc_descripcion' => 'Asistencia técnica', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4230'],
            ['contpuc_codigo' => '423015', 'contpuc_descripcion' => 'Administración de vinculadas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4230'],
            ['contpuc_codigo' => '423099', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4230'],
            ['contpuc_codigo' => '423505', 'contpuc_descripcion' => 'De báscula', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4235'],
            ['contpuc_codigo' => '423510', 'contpuc_descripcion' => 'De transporte', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4235'],
            ['contpuc_codigo' => '423515', 'contpuc_descripcion' => 'De prensa', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4235'],
            ['contpuc_codigo' => '423520', 'contpuc_descripcion' => 'Administrativos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4235'],
            ['contpuc_codigo' => '423525', 'contpuc_descripcion' => 'Técnicos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4235'],
            ['contpuc_codigo' => '423530', 'contpuc_descripcion' => 'De computación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4235'],
            ['contpuc_codigo' => '423535', 'contpuc_descripcion' => 'De telefax', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4235'],
            ['contpuc_codigo' => '423540', 'contpuc_descripcion' => 'Taller de vehículos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4235'],
            ['contpuc_codigo' => '423545', 'contpuc_descripcion' => 'De recepción de aeronaves', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4235'],
            ['contpuc_codigo' => '423550', 'contpuc_descripcion' => 'De transporte programa gas natural', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4235'],
            ['contpuc_codigo' => '423555', 'contpuc_descripcion' => 'Por contratos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4235'],
            ['contpuc_codigo' => '423560', 'contpuc_descripcion' => 'De trilla', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4235'],
            ['contpuc_codigo' => '423565', 'contpuc_descripcion' => 'De mantenimiento', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4235'],
            ['contpuc_codigo' => '423570', 'contpuc_descripcion' => 'Al personal', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4235'],
            ['contpuc_codigo' => '423575', 'contpuc_descripcion' => 'De casino', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4235'],
            ['contpuc_codigo' => '423580', 'contpuc_descripcion' => 'Fletes', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4235'],
            ['contpuc_codigo' => '423585', 'contpuc_descripcion' => 'Entre compañías', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4235'],
            ['contpuc_codigo' => '423595', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4235'],
            ['contpuc_codigo' => '423599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4235'],
            ['contpuc_codigo' => '424005', 'contpuc_descripcion' => 'Acciones', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4240'],
            ['contpuc_codigo' => '424010', 'contpuc_descripcion' => 'Cuotas o partes de interés social', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4240'],
            ['contpuc_codigo' => '424015', 'contpuc_descripcion' => 'Bonos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4240'],
            ['contpuc_codigo' => '424020', 'contpuc_descripcion' => 'Cédulas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4240'],
            ['contpuc_codigo' => '424025', 'contpuc_descripcion' => 'Certificados', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4240'],
            ['contpuc_codigo' => '424030', 'contpuc_descripcion' => 'Papeles comerciales', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4240'],
            ['contpuc_codigo' => '424035', 'contpuc_descripcion' => 'Títulos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4240'],
            ['contpuc_codigo' => '424045', 'contpuc_descripcion' => 'Derechos fiduciarios', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4240'],
            ['contpuc_codigo' => '424050', 'contpuc_descripcion' => 'Obligatorias', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4240'],
            ['contpuc_codigo' => '424095', 'contpuc_descripcion' => 'Otras', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4240'],
            ['contpuc_codigo' => '424099', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4240'],
            ['contpuc_codigo' => '424504', 'contpuc_descripcion' => 'Terrenos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4245'],
            ['contpuc_codigo' => '424506', 'contpuc_descripcion' => 'Materiales industria petrolera', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4245'],
            ['contpuc_codigo' => '424508', 'contpuc_descripcion' => 'Construcciones en curso', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4245'],
            ['contpuc_codigo' => '424512', 'contpuc_descripcion' => 'Maquinaria en montaje', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4245'],
            ['contpuc_codigo' => '424516', 'contpuc_descripcion' => 'Construcciones y edificaciones', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4245'],
            ['contpuc_codigo' => '424520', 'contpuc_descripcion' => 'Maquinaria y equipo', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4245'],
            ['contpuc_codigo' => '424524', 'contpuc_descripcion' => 'Equipo de oficina', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4245'],
            ['contpuc_codigo' => '424528', 'contpuc_descripcion' => 'Equipo de computación y comunicación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4245'],
            ['contpuc_codigo' => '424532', 'contpuc_descripcion' => 'Equipo médico-científico', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4245'],
            ['contpuc_codigo' => '424536', 'contpuc_descripcion' => 'Equipo de hoteles y restaurantes', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4245'],
            ['contpuc_codigo' => '424540', 'contpuc_descripcion' => 'Flota y equipo de transporte', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4245'],
            ['contpuc_codigo' => '424544', 'contpuc_descripcion' => 'Flota y equipo fluvial y/o marítimo', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4245'],
            ['contpuc_codigo' => '424548', 'contpuc_descripcion' => 'Flota y equipo aéreo', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4245'],
            ['contpuc_codigo' => '424552', 'contpuc_descripcion' => 'Flota y equipo férreo', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4245'],
            ['contpuc_codigo' => '424556', 'contpuc_descripcion' => 'Acueductos, plantas y redes', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4245'],
            ['contpuc_codigo' => '424560', 'contpuc_descripcion' => 'Armamento de vigilancia', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4245'],
            ['contpuc_codigo' => '424562', 'contpuc_descripcion' => 'Envases y empaques', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4245'],
            ['contpuc_codigo' => '424564', 'contpuc_descripcion' => 'Plantaciones agrícolas y forestales', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4245'],
            ['contpuc_codigo' => '424568', 'contpuc_descripcion' => 'Vías de comunicación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4245'],
            ['contpuc_codigo' => '424572', 'contpuc_descripcion' => 'Minas y Canteras', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4245'],
            ['contpuc_codigo' => '424580', 'contpuc_descripcion' => 'Pozos artesianos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4245'],
            ['contpuc_codigo' => '424584', 'contpuc_descripcion' => 'Yacimientos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4245'],
            ['contpuc_codigo' => '424588', 'contpuc_descripcion' => 'Semovientes', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4245'],
            ['contpuc_codigo' => '424599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4245'],
            ['contpuc_codigo' => '424805', 'contpuc_descripcion' => 'Intangibles', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4248'],
            ['contpuc_codigo' => '424810', 'contpuc_descripcion' => 'Otros activos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4248'],
            ['contpuc_codigo' => '424899', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4248'],
            ['contpuc_codigo' => '425005', 'contpuc_descripcion' => 'Deudas malas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4250'],
            ['contpuc_codigo' => '425010', 'contpuc_descripcion' => 'Seguros', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4250'],
            ['contpuc_codigo' => '425015', 'contpuc_descripcion' => 'Reclamos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4250'],
            ['contpuc_codigo' => '425020', 'contpuc_descripcion' => 'Reintegro por personal en comisión', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4250'],
            ['contpuc_codigo' => '425025', 'contpuc_descripcion' => 'Reintegro garantías', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4250'],
            ['contpuc_codigo' => '425030', 'contpuc_descripcion' => 'Descuentos concedidos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4250'],
            ['contpuc_codigo' => '425035', 'contpuc_descripcion' => 'De  provisiones', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4250'],
            ['contpuc_codigo' => '425040', 'contpuc_descripcion' => 'Gastos bancarios', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4250'],
            ['contpuc_codigo' => '425045', 'contpuc_descripcion' => 'De depreciación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4250'],
            ['contpuc_codigo' => '425050', 'contpuc_descripcion' => 'Reintegro de otros costos y gastos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4250'],
            ['contpuc_codigo' => '425099', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4250'],
            ['contpuc_codigo' => '425505', 'contpuc_descripcion' => 'Por siniestro', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4255'],
            ['contpuc_codigo' => '425510', 'contpuc_descripcion' => 'Por suministros', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4255'],
            ['contpuc_codigo' => '425515', 'contpuc_descripcion' => 'Lucro cesante compañías de seguros', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4255'],
            ['contpuc_codigo' => '425520', 'contpuc_descripcion' => 'Daño emergente compañías de seguros', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4255'],
            ['contpuc_codigo' => '425525', 'contpuc_descripcion' => 'Por pérdida de mercancía', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4255'],
            ['contpuc_codigo' => '425530', 'contpuc_descripcion' => 'Por incumplimiento de contratos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4255'],
            ['contpuc_codigo' => '425535', 'contpuc_descripcion' => 'De terceros', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4255'],
            ['contpuc_codigo' => '425540', 'contpuc_descripcion' => 'Por incapacidades ISS', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4255'],
            ['contpuc_codigo' => '425595', 'contpuc_descripcion' => 'Otras', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4255'],
            ['contpuc_codigo' => '425599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4255'],
            ['contpuc_codigo' => '426099', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4260'],
            ['contpuc_codigo' => '426599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4265'],
            ['contpuc_codigo' => '427599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4275'],
            ['contpuc_codigo' => '429503', 'contpuc_descripcion' => 'CERT', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4295'],
            ['contpuc_codigo' => '429505', 'contpuc_descripcion' => 'Aprovechamientos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4295'],
            ['contpuc_codigo' => '429507', 'contpuc_descripcion' => 'Auxilios', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4295'],
            ['contpuc_codigo' => '429509', 'contpuc_descripcion' => 'Subvenciones', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4295'],
            ['contpuc_codigo' => '429511', 'contpuc_descripcion' => 'Ingresos por investigación y desarrollo', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4295'],
            ['contpuc_codigo' => '429513', 'contpuc_descripcion' => 'Por trabajos ejecutados', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4295'],
            ['contpuc_codigo' => '429515', 'contpuc_descripcion' => 'Regalías', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4295'],
            ['contpuc_codigo' => '429517', 'contpuc_descripcion' => 'Derivados de las exportaciones', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4295'],
            ['contpuc_codigo' => '429519', 'contpuc_descripcion' => 'Otros ingresos de explotación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4295'],
            ['contpuc_codigo' => '429521', 'contpuc_descripcion' => 'De la actividad ganadera', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4295'],
            ['contpuc_codigo' => '429525', 'contpuc_descripcion' => 'Derechos y licitaciones', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4295'],
            ['contpuc_codigo' => '429530', 'contpuc_descripcion' => 'Ingresos por elementos perdidos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4295'],
            ['contpuc_codigo' => '429533', 'contpuc_descripcion' => 'Multas y recargos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4295'],
            ['contpuc_codigo' => '429535', 'contpuc_descripcion' => 'Preavisos descontados', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4295'],
            ['contpuc_codigo' => '429537', 'contpuc_descripcion' => 'Reclamos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4295'],
            ['contpuc_codigo' => '429540', 'contpuc_descripcion' => 'Recobro de daños', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4295'],
            ['contpuc_codigo' => '429543', 'contpuc_descripcion' => 'Premios', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4295'],
            ['contpuc_codigo' => '429545', 'contpuc_descripcion' => 'Bonificaciones', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4295'],
            ['contpuc_codigo' => '429547', 'contpuc_descripcion' => 'Productos descontados', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4295'],
            ['contpuc_codigo' => '429549', 'contpuc_descripcion' => 'Reconocimientos ISS', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4295'],
            ['contpuc_codigo' => '429551', 'contpuc_descripcion' => 'Excedentes', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4295'],
            ['contpuc_codigo' => '429553', 'contpuc_descripcion' => 'Sobrantes de caja', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4295'],
            ['contpuc_codigo' => '429555', 'contpuc_descripcion' => 'Sobrantes en liquidación fletes', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4295'],
            ['contpuc_codigo' => '429557', 'contpuc_descripcion' => 'Subsidios estatales', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4295'],
            ['contpuc_codigo' => '429559', 'contpuc_descripcion' => 'Capacitación distribuidores', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4295'],
            ['contpuc_codigo' => '429561', 'contpuc_descripcion' => 'De escrituración', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4295'],
            ['contpuc_codigo' => '429563', 'contpuc_descripcion' => 'Registro promesas de venta', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4295'],
            ['contpuc_codigo' => '429567', 'contpuc_descripcion' => 'Útiles, papelería y fotocopias', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4295'],
            ['contpuc_codigo' => '429571', 'contpuc_descripcion' => 'Resultados, matrículas y traspasos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4295'],
            ['contpuc_codigo' => '429573', 'contpuc_descripcion' => 'Decoraciones', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4295'],
            ['contpuc_codigo' => '429575', 'contpuc_descripcion' => 'Manejo de carga', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4295'],
            ['contpuc_codigo' => '429579', 'contpuc_descripcion' => 'Historia clínica', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4295'],
            ['contpuc_codigo' => '429581', 'contpuc_descripcion' => 'Ajuste al peso', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4295'],
            ['contpuc_codigo' => '429583', 'contpuc_descripcion' => 'Llamadas telefónicas', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4295'],
            ['contpuc_codigo' => '429595', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4295'],
            ['contpuc_codigo' => '429599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4295'],
            ['contpuc_codigo' => '470505', 'contpuc_descripcion' => 'Inversiones (CR)', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4705'],
            ['contpuc_codigo' => '470510', 'contpuc_descripcion' => 'Inventarios (CR)', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4705'],
            ['contpuc_codigo' => '470515', 'contpuc_descripcion' => 'Propiedades, planta y equipo (CR)', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4705'],
            ['contpuc_codigo' => '470520', 'contpuc_descripcion' => 'Intangibles (CR)', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4705'],
            ['contpuc_codigo' => '470525', 'contpuc_descripcion' => 'Activos diferidos', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4705'],
            ['contpuc_codigo' => '470530', 'contpuc_descripcion' => 'Otros activos (CR)', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4705'],
            ['contpuc_codigo' => '470535', 'contpuc_descripcion' => 'Pasivos sujetos de ajuste', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4705'],
            ['contpuc_codigo' => '470540', 'contpuc_descripcion' => 'Patrimonio', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4705'],
            ['contpuc_codigo' => '470545', 'contpuc_descripcion' => 'Depreciación acumulada (DB)', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4705'],
            ['contpuc_codigo' => '470550', 'contpuc_descripcion' => 'Depreciación diferida (CR)', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4705'],
            ['contpuc_codigo' => '470555', 'contpuc_descripcion' => 'Agotamiento acumulado (DB)', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4705'],
            ['contpuc_codigo' => '470560', 'contpuc_descripcion' => 'Amortización acumulada (DB)', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4705'],
            ['contpuc_codigo' => '470565', 'contpuc_descripcion' => 'Ingresos operacionales  (DB)', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4705'],
            ['contpuc_codigo' => '470568', 'contpuc_descripcion' => 'Devoluciones en ventas (CR)', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4705'],
            ['contpuc_codigo' => '470570', 'contpuc_descripcion' => 'Ingresos no operacionales (DB)', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4705'],
            ['contpuc_codigo' => '470575', 'contpuc_descripcion' => 'Gastos operacionales de administración (CR)', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4705'],
            ['contpuc_codigo' => '470580', 'contpuc_descripcion' => 'Gastos operacionales de ventas (CR)', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4705'],
            ['contpuc_codigo' => '470585', 'contpuc_descripcion' => 'Gastos no operacionales (CR)', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4705'],
            ['contpuc_codigo' => '470590', 'contpuc_descripcion' => 'Compras (CR)', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4705'],
            ['contpuc_codigo' => '470591', 'contpuc_descripcion' => 'Devoluciones en compras (DB)', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4705'],
            ['contpuc_codigo' => '470592', 'contpuc_descripcion' => 'Costo de ventas (CR)', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4705'],
            ['contpuc_codigo' => '470594', 'contpuc_descripcion' => 'Costos de producción o de operación (CR)', 'contpuc_tipo' => 'Ingreso', 'parent_puc_codigo' => '4705'],
        ];

        $fecha = Carbon::now();

        foreach ($cuentasContrapartida as $cuenta) {
            $parentPUC = PUC::where('puc_codigo', $cuenta['parent_puc_codigo'])->first();

            if (!$parentPUC) {
                Log::warning("Parent PUC with code " . $cuenta['parent_puc_codigo'] . " not found for contrapartida " . $cuenta['contpuc_codigo'] . ". Skipping.");
                $this->command->error("Parent PUC with code " . $cuenta['parent_puc_codigo'] . " not found for contrapartida " . $cuenta['contpuc_codigo'] . ". Skipping.");
                continue;
            }

            ContrapartidaPUC::firstOrCreate(
                ['contpuc_codigo' => $cuenta['contpuc_codigo']], // Check if already exists
                [
                    'contpuc_descripcion' => $cuenta['contpuc_descripcion'],
                    'contpuc_tipo' => $cuenta['contpuc_tipo'],
                    'puc_idpuc' => $parentPUC->idpuc,
                    'estado' => 'Activo',
                    'fecha_registro' => $fecha,
                ]
            );
        }
        
        $this->command->info('ContrapartidaPUC Seeder for Ingresos (Class 4) ran successfully!');
    }
}
