<?php

namespace Database\Seeders;

use App\Models\ContrapartidaPUC;
use App\Models\PUC; // To lookup parent PUC ID
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\Log; // For logging if parent PUC not found

class ContrapartidaPUCPasivoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cuentasContrapartida = [
            ['contpuc_codigo' => '210505', 'contpuc_descripcion' => 'Sobregiros', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2105'],
            ['contpuc_codigo' => '210510', 'contpuc_descripcion' => 'Pagarés', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2105'],
            ['contpuc_codigo' => '210515', 'contpuc_descripcion' => 'Cartas de crédito', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2105'],
            ['contpuc_codigo' => '210520', 'contpuc_descripcion' => 'Aceptaciones bancarias', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2105'],
            ['contpuc_codigo' => '211005', 'contpuc_descripcion' => 'Sobregiros', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2110'],
            ['contpuc_codigo' => '211010', 'contpuc_descripcion' => 'Pagarés', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2110'],
            ['contpuc_codigo' => '211015', 'contpuc_descripcion' => 'Cartas de crédito', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2110'],
            ['contpuc_codigo' => '211020', 'contpuc_descripcion' => 'Aceptaciones bancarias', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2110'],
            ['contpuc_codigo' => '211505', 'contpuc_descripcion' => 'Pagarés', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2115'],
            ['contpuc_codigo' => '211510', 'contpuc_descripcion' => 'Aceptaciones financieras', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2115'],
            ['contpuc_codigo' => '211515', 'contpuc_descripcion' => 'Cartas de crédito', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2115'],
            ['contpuc_codigo' => '211520', 'contpuc_descripcion' => 'Contratos de arrendamiento financiero (leasing)', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2115'],
            ['contpuc_codigo' => '212005', 'contpuc_descripcion' => 'Pagarés', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2120'],
            ['contpuc_codigo' => '212010', 'contpuc_descripcion' => 'Aceptaciones financieras', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2120'],
            ['contpuc_codigo' => '212020', 'contpuc_descripcion' => 'Contratos de arrendamiento financiero (leasing)', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2120'],
            ['contpuc_codigo' => '212505', 'contpuc_descripcion' => 'Sobregiros', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2125'],
            ['contpuc_codigo' => '212510', 'contpuc_descripcion' => 'Pagarés', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2125'],
            ['contpuc_codigo' => '212515', 'contpuc_descripcion' => 'Hipotecarias', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2125'],
            ['contpuc_codigo' => '213505', 'contpuc_descripcion' => 'Acciones', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2135'],
            ['contpuc_codigo' => '213510', 'contpuc_descripcion' => 'Cuotas o partes de interés social', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2135'],
            ['contpuc_codigo' => '213515', 'contpuc_descripcion' => 'Bonos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2135'],
            ['contpuc_codigo' => '213520', 'contpuc_descripcion' => 'Cédulas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2135'],
            ['contpuc_codigo' => '213525', 'contpuc_descripcion' => 'Certificados', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2135'],
            ['contpuc_codigo' => '213530', 'contpuc_descripcion' => 'Papeles comerciales', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2135'],
            ['contpuc_codigo' => '213535', 'contpuc_descripcion' => 'Títulos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2135'],
            ['contpuc_codigo' => '213540', 'contpuc_descripcion' => 'Aceptaciones bancarias o financieras', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2135'],
            ['contpuc_codigo' => '213595', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2135'],
            ['contpuc_codigo' => '214505', 'contpuc_descripcion' => 'Gobierno Nacional', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2145'],
            ['contpuc_codigo' => '214510', 'contpuc_descripcion' => 'Entidades oficiales', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2145'],
            ['contpuc_codigo' => '219505', 'contpuc_descripcion' => 'Particulares', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2195'],
            ['contpuc_codigo' => '219510', 'contpuc_descripcion' => 'Compañías vinculadas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2195'],
            ['contpuc_codigo' => '219515', 'contpuc_descripcion' => 'Casa matriz', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2195'],
            ['contpuc_codigo' => '219520', 'contpuc_descripcion' => 'Socios o accionistas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2195'],
            ['contpuc_codigo' => '219525', 'contpuc_descripcion' => 'Fondos y cooperativas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2195'],
            ['contpuc_codigo' => '219530', 'contpuc_descripcion' => 'Directores', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2195'],
            ['contpuc_codigo' => '219595', 'contpuc_descripcion' => 'Otras', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2195'],
            ['contpuc_codigo' => '233505', 'contpuc_descripcion' => 'Gastos financieros', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2335'],
            ['contpuc_codigo' => '233510', 'contpuc_descripcion' => 'Gastos legales', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2335'],
            ['contpuc_codigo' => '233515', 'contpuc_descripcion' => 'Libros, suscripciones, periódicos y revistas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2335'],
            ['contpuc_codigo' => '233520', 'contpuc_descripcion' => 'Comisiones', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2335'],
            ['contpuc_codigo' => '233525', 'contpuc_descripcion' => 'Honorarios', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2335'],
            ['contpuc_codigo' => '233530', 'contpuc_descripcion' => 'Servicios técnicos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2335'],
            ['contpuc_codigo' => '233535', 'contpuc_descripcion' => 'Servicios de mantenimiento', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2335'],
            ['contpuc_codigo' => '233540', 'contpuc_descripcion' => 'Arrendamientos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2335'],
            ['contpuc_codigo' => '233545', 'contpuc_descripcion' => 'Transportes, fletes y acarreos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2335'],
            ['contpuc_codigo' => '233550', 'contpuc_descripcion' => 'Servicios públicos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2335'],
            ['contpuc_codigo' => '233555', 'contpuc_descripcion' => 'Seguros', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2335'],
            ['contpuc_codigo' => '233560', 'contpuc_descripcion' => 'Gastos de viaje', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2335'],
            ['contpuc_codigo' => '233565', 'contpuc_descripcion' => 'Gastos de representación y relaciones públicas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2335'],
            ['contpuc_codigo' => '233570', 'contpuc_descripcion' => 'Servicios aduaneros', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2335'],
            ['contpuc_codigo' => '233595', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2335'],
            ['contpuc_codigo' => '235505', 'contpuc_descripcion' => 'Accionistas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2355'],
            ['contpuc_codigo' => '235510', 'contpuc_descripcion' => 'Socios', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2355'],
            ['contpuc_codigo' => '236005', 'contpuc_descripcion' => 'Dividendos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2360'],
            ['contpuc_codigo' => '236010', 'contpuc_descripcion' => 'Participaciones', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2360'],
            ['contpuc_codigo' => '236505', 'contpuc_descripcion' => 'Salarios y pagos laborales', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2365'],
            ['contpuc_codigo' => '236510', 'contpuc_descripcion' => 'Dividendos y/o participaciones', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2365'],
            ['contpuc_codigo' => '236515', 'contpuc_descripcion' => 'Honorarios', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2365'],
            ['contpuc_codigo' => '236520', 'contpuc_descripcion' => 'Comisiones', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2365'],
            ['contpuc_codigo' => '236525', 'contpuc_descripcion' => 'Servicios', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2365'],
            ['contpuc_codigo' => '236530', 'contpuc_descripcion' => 'Arrendamientos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2365'],
            ['contpuc_codigo' => '236535', 'contpuc_descripcion' => 'Rendimientos financieros', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2365'],
            ['contpuc_codigo' => '236540', 'contpuc_descripcion' => 'Compras', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2365'],
            ['contpuc_codigo' => '236545', 'contpuc_descripcion' => 'Loterías, rifas, apuestas y similares', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2365'],
            ['contpuc_codigo' => '236550', 'contpuc_descripcion' => 'Por pagos al exterior', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2365'],
            ['contpuc_codigo' => '236555', 'contpuc_descripcion' => 'Por ingresos obtenidos en el exterior', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2365'],
            ['contpuc_codigo' => '236560', 'contpuc_descripcion' => 'Enajenación propiedades planta y equipo, personas naturales', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2365'],
            ['contpuc_codigo' => '236565', 'contpuc_descripcion' => 'Por impuesto de timbre', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2365'],
            ['contpuc_codigo' => '236570', 'contpuc_descripcion' => 'Otras retenciones y patrimonio', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2365'],
            ['contpuc_codigo' => '236575', 'contpuc_descripcion' => 'Autorretenciones', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2365'],
            ['contpuc_codigo' => '237005', 'contpuc_descripcion' => 'Aportes a entidades promotoras de salud, EPS', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2370'],
            ['contpuc_codigo' => '237006', 'contpuc_descripcion' => 'Aportes a administradoras de riesgos profesionales, ARP', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2370'],
            ['contpuc_codigo' => '237010', 'contpuc_descripcion' => 'Aportes al ICBF, SENA y cajas de compensación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2370'],
            ['contpuc_codigo' => '237015', 'contpuc_descripcion' => 'Aportes al FIC', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2370'],
            ['contpuc_codigo' => '237025', 'contpuc_descripcion' => 'Embargos judiciales', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2370'],
            ['contpuc_codigo' => '237030', 'contpuc_descripcion' => 'Libranzas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2370'],
            ['contpuc_codigo' => '237035', 'contpuc_descripcion' => 'Sindicatos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2370'],
            ['contpuc_codigo' => '237040', 'contpuc_descripcion' => 'Cooperativas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2370'],
            ['contpuc_codigo' => '237045', 'contpuc_descripcion' => 'Fondos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2370'],
            ['contpuc_codigo' => '237095', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2370'],
            ['contpuc_codigo' => '238005', 'contpuc_descripcion' => 'Depositarios', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2380'],
            ['contpuc_codigo' => '238010', 'contpuc_descripcion' => 'Comisionistas de bolsas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2380'],
            ['contpuc_codigo' => '238015', 'contpuc_descripcion' => 'Sociedad administradora-Fondos de inversión', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2380'],
            ['contpuc_codigo' => '238020', 'contpuc_descripcion' => 'Reintegros por pagar', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2380'],
            ['contpuc_codigo' => '238025', 'contpuc_descripcion' => 'Fondo de perseverancia', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2380'],
            ['contpuc_codigo' => '238030', 'contpuc_descripcion' => 'Fondos de cesantías y/o pensiones', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2380'],
            ['contpuc_codigo' => '238035', 'contpuc_descripcion' => 'Donaciones asignadas por pagar', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2380'],
            ['contpuc_codigo' => '238095', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2380'],
            ['contpuc_codigo' => '240405', 'contpuc_descripcion' => 'Vigencia fiscal corriente', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2404'],
            ['contpuc_codigo' => '240410', 'contpuc_descripcion' => 'Vigencias fiscales anteriores', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2404'],
            ['contpuc_codigo' => '241205', 'contpuc_descripcion' => 'Vigencia fiscal corriente', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2412'],
            ['contpuc_codigo' => '241210', 'contpuc_descripcion' => 'Vigencias fiscales anteriores', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2412'],
            ['contpuc_codigo' => '242405', 'contpuc_descripcion' => 'Vigencia fiscal corriente', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2424'],
            ['contpuc_codigo' => '242410', 'contpuc_descripcion' => 'Vigencias fiscales anteriores', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2424'],
            ['contpuc_codigo' => '243605', 'contpuc_descripcion' => 'Vigencia fiscal corriente', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2436'],
            ['contpuc_codigo' => '243610', 'contpuc_descripcion' => 'Vigencias fiscales anteriores', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2436'],
            ['contpuc_codigo' => '244405', 'contpuc_descripcion' => 'De hidrocarburos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2444'],
            ['contpuc_codigo' => '244410', 'contpuc_descripcion' => 'De minas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2444'],
            ['contpuc_codigo' => '246405', 'contpuc_descripcion' => 'De licores', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2464'],
            ['contpuc_codigo' => '246410', 'contpuc_descripcion' => 'De cervezas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2464'],
            ['contpuc_codigo' => '246415', 'contpuc_descripcion' => 'De cigarrillos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2464'],
            ['contpuc_codigo' => '251005', 'contpuc_descripcion' => 'Ley laboral anterior', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2510'],
            ['contpuc_codigo' => '251010', 'contpuc_descripcion' => 'Ley 50 de 1990 y normas posteriores', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2510'],
            ['contpuc_codigo' => '253005', 'contpuc_descripcion' => 'Primas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2530'],
            ['contpuc_codigo' => '253010', 'contpuc_descripcion' => 'Auxilios', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2530'],
            ['contpuc_codigo' => '253015', 'contpuc_descripcion' => 'Dotación y suministro a trabajadores', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2530'],
            ['contpuc_codigo' => '253020', 'contpuc_descripcion' => 'Bonificaciones', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2530'],
            ['contpuc_codigo' => '253025', 'contpuc_descripcion' => 'Seguros', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2530'],
            ['contpuc_codigo' => '253095', 'contpuc_descripcion' => 'Otras', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2530'],
            ['contpuc_codigo' => '260505', 'contpuc_descripcion' => 'Intereses', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2605'],
            ['contpuc_codigo' => '260510', 'contpuc_descripcion' => 'Comisiones', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2605'],
            ['contpuc_codigo' => '260515', 'contpuc_descripcion' => 'Honorarios', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2605'],
            ['contpuc_codigo' => '260520', 'contpuc_descripcion' => 'Servicios técnicos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2605'],
            ['contpuc_codigo' => '260525', 'contpuc_descripcion' => 'Transportes, fletes y acarreos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2605'],
            ['contpuc_codigo' => '260530', 'contpuc_descripcion' => 'Gastos de viaje', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2605'],
            ['contpuc_codigo' => '260535', 'contpuc_descripcion' => 'Servicios públicos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2605'],
            ['contpuc_codigo' => '260540', 'contpuc_descripcion' => 'Regalías', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2605'],
            ['contpuc_codigo' => '260545', 'contpuc_descripcion' => 'Garantías', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2605'],
            ['contpuc_codigo' => '260550', 'contpuc_descripcion' => 'Materiales y repuestos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2605'],
            ['contpuc_codigo' => '260595', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2605'],
            ['contpuc_codigo' => '261005', 'contpuc_descripcion' => 'Cesantías', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2610'],
            ['contpuc_codigo' => '261010', 'contpuc_descripcion' => 'Intereses sobre cesantías', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2610'],
            ['contpuc_codigo' => '261015', 'contpuc_descripcion' => 'Vacaciones', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2610'],
            ['contpuc_codigo' => '261020', 'contpuc_descripcion' => 'Prima de servicios', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2610'],
            ['contpuc_codigo' => '261025', 'contpuc_descripcion' => 'Prestaciones extralegales', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2610'],
            ['contpuc_codigo' => '261030', 'contpuc_descripcion' => 'Viáticos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2610'],
            ['contpuc_codigo' => '261095', 'contpuc_descripcion' => 'Otras', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2610'],
            ['contpuc_codigo' => '261505', 'contpuc_descripcion' => 'De renta y complementarios', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2615'],
            ['contpuc_codigo' => '261510', 'contpuc_descripcion' => 'De industria y comercio', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2615'],
            ['contpuc_codigo' => '261515', 'contpuc_descripcion' => 'Tasa por utilización de puertos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2615'],
            ['contpuc_codigo' => '261520', 'contpuc_descripcion' => 'De vehículos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2615'],
            ['contpuc_codigo' => '261525', 'contpuc_descripcion' => 'De hidrocarburos y minas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2615'],
            ['contpuc_codigo' => '261595', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2615'],
            ['contpuc_codigo' => '262005', 'contpuc_descripcion' => 'Cálculo actuarial pensiones de jubilación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2620'],
            ['contpuc_codigo' => '262010', 'contpuc_descripcion' => 'Pensiones de jubilación por amortizar (DB)', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2620'],
            ['contpuc_codigo' => '262505', 'contpuc_descripcion' => 'Acueducto y alcantarillado', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2625'],
            ['contpuc_codigo' => '262510', 'contpuc_descripcion' => 'Energía eléctrica', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2625'],
            ['contpuc_codigo' => '262515', 'contpuc_descripcion' => 'Teléfonos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2625'],
            ['contpuc_codigo' => '262595', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2625'],
            ['contpuc_codigo' => '263005', 'contpuc_descripcion' => 'Terrenos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2630'],
            ['contpuc_codigo' => '263010', 'contpuc_descripcion' => 'Construcciones y edificaciones', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2630'],
            ['contpuc_codigo' => '263015', 'contpuc_descripcion' => 'Maquinaria y equipo', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2630'],
            ['contpuc_codigo' => '263020', 'contpuc_descripcion' => 'Equipo de oficina', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2630'],
            ['contpuc_codigo' => '263025', 'contpuc_descripcion' => 'Equipo de computación y comunicación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2630'],
            ['contpuc_codigo' => '263030', 'contpuc_descripcion' => 'Equipo médico-científico', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2630'],
            ['contpuc_codigo' => '263035', 'contpuc_descripcion' => 'Equipo de hoteles y restaurantes', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2630'],
            ['contpuc_codigo' => '263040', 'contpuc_descripcion' => 'Flota y equipo de transporte', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2630'],
            ['contpuc_codigo' => '263045', 'contpuc_descripcion' => 'Flota y equipo fluvial y/o marítimo', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2630'],
            ['contpuc_codigo' => '263050', 'contpuc_descripcion' => 'Flota y equipo aéreo', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2630'],
            ['contpuc_codigo' => '263055', 'contpuc_descripcion' => 'Flota y equipo férreo', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2630'],
            ['contpuc_codigo' => '263060', 'contpuc_descripcion' => 'Acueductos, plantas y redes', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2630'],
            ['contpuc_codigo' => '263065', 'contpuc_descripcion' => 'Armamento de vigilancia', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2630'],
            ['contpuc_codigo' => '263070', 'contpuc_descripcion' => 'Envases y empaques', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2630'],
            ['contpuc_codigo' => '263075', 'contpuc_descripcion' => 'Plantaciones agrícolas y forestales', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2630'],
            ['contpuc_codigo' => '263080', 'contpuc_descripcion' => 'Vías de comunicación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2630'],
            ['contpuc_codigo' => '263085', 'contpuc_descripcion' => 'Pozos artesianos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2630'],
            ['contpuc_codigo' => '263095', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2630'],
            ['contpuc_codigo' => '263505', 'contpuc_descripcion' => 'Multas y sanciones autoridades administrativas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2635'],
            ['contpuc_codigo' => '263510', 'contpuc_descripcion' => 'Intereses por multas y sanciones', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2635'],
            ['contpuc_codigo' => '263515', 'contpuc_descripcion' => 'Reclamos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2635'],
            ['contpuc_codigo' => '263520', 'contpuc_descripcion' => 'Laborales', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2635'],
            ['contpuc_codigo' => '263525', 'contpuc_descripcion' => 'Civiles', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2635'],
            ['contpuc_codigo' => '263530', 'contpuc_descripcion' => 'Penales', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2635'],
            ['contpuc_codigo' => '263535', 'contpuc_descripcion' => 'Administrativos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2635'],
            ['contpuc_codigo' => '263540', 'contpuc_descripcion' => 'Comerciales', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2635'],
            ['contpuc_codigo' => '263595', 'contpuc_descripcion' => 'Otras', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2635'],
            ['contpuc_codigo' => '269505', 'contpuc_descripcion' => 'Para beneficencia', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2695'],
            ['contpuc_codigo' => '269510', 'contpuc_descripcion' => 'Para comunicaciones', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2695'],
            ['contpuc_codigo' => '269515', 'contpuc_descripcion' => 'Para pérdida en transporte', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2695'],
            ['contpuc_codigo' => '269520', 'contpuc_descripcion' => 'Para operación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2695'],
            ['contpuc_codigo' => '269525', 'contpuc_descripcion' => 'Para protección de bienes agotables', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2695'],
            ['contpuc_codigo' => '269530', 'contpuc_descripcion' => 'Para ajustes en redención de unidades', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2695'],
            ['contpuc_codigo' => '269535', 'contpuc_descripcion' => 'Autoseguro', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2695'],
            ['contpuc_codigo' => '269540', 'contpuc_descripcion' => 'Planes y programas de reforestación y electrificación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2695'],
            ['contpuc_codigo' => '269595', 'contpuc_descripcion' => 'Otras', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2695'],
            ['contpuc_codigo' => '270505', 'contpuc_descripcion' => 'Intereses', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2705'],
            ['contpuc_codigo' => '270510', 'contpuc_descripcion' => 'Comisiones', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2705'],
            ['contpuc_codigo' => '270515', 'contpuc_descripcion' => 'Arrendamientos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2705'],
            ['contpuc_codigo' => '270520', 'contpuc_descripcion' => 'Honorarios', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2705'],
            ['contpuc_codigo' => '270525', 'contpuc_descripcion' => 'Servicios técnicos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2705'],
            ['contpuc_codigo' => '270530', 'contpuc_descripcion' => 'De suscriptores', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2705'],
            ['contpuc_codigo' => '270535', 'contpuc_descripcion' => 'Transportes, fletes y acarreos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2705'],
            ['contpuc_codigo' => '270540', 'contpuc_descripcion' => 'Mercancía en tránsito ya vendida', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2705'],
            ['contpuc_codigo' => '270545', 'contpuc_descripcion' => 'Matrículas y pensiones', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2705'],
            ['contpuc_codigo' => '270550', 'contpuc_descripcion' => 'Cuotas de administración', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2705'],
            ['contpuc_codigo' => '270595', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2705'],
            ['contpuc_codigo' => '271005', 'contpuc_descripcion' => 'Reajuste del sistema', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2710'],
            ['contpuc_codigo' => '272505', 'contpuc_descripcion' => 'Por depreciación flexible', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2725'],
            ['contpuc_codigo' => '272595', 'contpuc_descripcion' => 'Diversos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2725'],
            ['contpuc_codigo' => '272599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2725'],
            ['contpuc_codigo' => '280505', 'contpuc_descripcion' => 'De clientes', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2805'],
            ['contpuc_codigo' => '280510', 'contpuc_descripcion' => 'Sobre contratos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2805'],
            ['contpuc_codigo' => '280515', 'contpuc_descripcion' => 'Para obras en proceso', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2805'],
            ['contpuc_codigo' => '280595', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2805'],
            ['contpuc_codigo' => '281005', 'contpuc_descripcion' => 'Para futura suscripción de acciones', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2810'],
            ['contpuc_codigo' => '281010', 'contpuc_descripcion' => 'Para futuro pago de cuotas o derechos sociales', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2810'],
            ['contpuc_codigo' => '281015', 'contpuc_descripcion' => 'Para garantía en la prestación de servicios', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2810'],
            ['contpuc_codigo' => '281020', 'contpuc_descripcion' => 'Para garantía de contratos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2810'],
            ['contpuc_codigo' => '281025', 'contpuc_descripcion' => 'De licitaciones', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2810'],
            ['contpuc_codigo' => '281030', 'contpuc_descripcion' => 'De manejo de bienes', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2810'],
            ['contpuc_codigo' => '281035', 'contpuc_descripcion' => 'Fondo de reserva', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2810'],
            ['contpuc_codigo' => '281095', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2810'],
            ['contpuc_codigo' => '281505', 'contpuc_descripcion' => 'Valores recibidos para terceros', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2815'],
            ['contpuc_codigo' => '281510', 'contpuc_descripcion' => 'Venta por cuenta de terceros', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2815'],
            ['contpuc_codigo' => '282505', 'contpuc_descripcion' => 'Cumplimiento obligaciones laborales', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2825'],
            ['contpuc_codigo' => '282510', 'contpuc_descripcion' => 'Para estabilidad de obra', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2825'],
            ['contpuc_codigo' => '282515', 'contpuc_descripcion' => 'Garantía cumplimiento de contratos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2825'],
            ['contpuc_codigo' => '283005', 'contpuc_descripcion' => 'Indemnizaciones', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2830'],
            ['contpuc_codigo' => '283010', 'contpuc_descripcion' => 'Depósitos judiciales', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2830'],
            ['contpuc_codigo' => '283505', 'contpuc_descripcion' => 'Cuotas netas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2835'],
            ['contpuc_codigo' => '283510', 'contpuc_descripcion' => 'Grupos en formación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2835'],
            ['contpuc_codigo' => '289505', 'contpuc_descripcion' => 'Préstamos de productos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2895'],
            ['contpuc_codigo' => '289510', 'contpuc_descripcion' => 'Reembolso de costos exploratorios', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2895'],
            ['contpuc_codigo' => '289515', 'contpuc_descripcion' => 'Programa de extensión agropecuaria', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2895'],
            ['contpuc_codigo' => '292005', 'contpuc_descripcion' => 'Valor bonos pensionales', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2920'],
            ['contpuc_codigo' => '292010', 'contpuc_descripcion' => 'Bonos pensionales por amortizar (DB)', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2920'],
            ['contpuc_codigo' => '292015', 'contpuc_descripcion' => 'Intereses causados sobre bonos pensionales', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2920'],
            ['contpuc_codigo' => '292505', 'contpuc_descripcion' => 'Valor títulos pensionales', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2925'],
            ['contpuc_codigo' => '292510', 'contpuc_descripcion' => 'Títulos pensionales por amortizar (DB)', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2925'],
            ['contpuc_codigo' => '292515', 'contpuc_descripcion' => 'Intereses causados sobre títulos pensionales', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '2925'],
        ];

        $fecha = Carbon::now();

        foreach ($cuentasContrapartida as $cuenta) {
            $parentPUC = PUC::where('puc_codigo', $cuenta['parent_puc_codigo'])->first();

            if (!$parentPUC) {
                Log::warning("Parent PUC with code " . $cuenta['parent_puc_codigo'] . " not found for contrapartida " . $cuenta['contpuc_codigo'] . ". Skipping.");
                $this->command->error("Parent PUC with code " . $cuenta['parent_puc_codigo'] . " not found for contrapartida " . $cuenta['contpuc_codigo'] . ". Skipping.");
                continue;
            }

            ContrapartidaPUC::firstOrCreate(
                ['contpuc_codigo' => $cuenta['contpuc_codigo']], // Check if already exists
                [
                    'contpuc_descripcion' => $cuenta['contpuc_descripcion'],
                    'contpuc_tipo' => $cuenta['contpuc_tipo'],
                    'puc_idpuc' => $parentPUC->idpuc,
                    'estado' => 'Activo',
                    'fecha_registro' => $fecha,
                ]
            );
        }
        
        $this->command->info('ContrapartidaPUC Seeder for Pasivo (Class 2) ran successfully!');
    }
}
