<?php

namespace Database\Seeders;

use App\Models\ContrapartidaPUC;
use App\Models\PUC; // To lookup parent PUC ID
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\Log; // For logging if parent PUC not found

class ContrapartidaPUCGastosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cuentasContrapartida = [
            ['contpuc_codigo' => '510503', 'contpuc_descripcion' => 'Salario integral', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5105'],
            ['contpuc_codigo' => '510506', 'contpuc_descripcion' => 'Sueldos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5105'],
            ['contpuc_codigo' => '510512', 'contpuc_descripcion' => 'Jornales', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5105'],
            ['contpuc_codigo' => '510515', 'contpuc_descripcion' => 'Horas extras y recargos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5105'],
            ['contpuc_codigo' => '510518', 'contpuc_descripcion' => 'Comisiones', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5105'],
            ['contpuc_codigo' => '510521', 'contpuc_descripcion' => 'Viáticos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5105'],
            ['contpuc_codigo' => '510524', 'contpuc_descripcion' => 'Incapacidades', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5105'],
            ['contpuc_codigo' => '510527', 'contpuc_descripcion' => 'Auxilio de transporte', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5105'],
            ['contpuc_codigo' => '510530', 'contpuc_descripcion' => 'Cesantías', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5105'],
            ['contpuc_codigo' => '510533', 'contpuc_descripcion' => 'Intereses sobre cesantías', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5105'],
            ['contpuc_codigo' => '510536', 'contpuc_descripcion' => 'Prima de servicios', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5105'],
            ['contpuc_codigo' => '510539', 'contpuc_descripcion' => 'Vacaciones', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5105'],
            ['contpuc_codigo' => '510542', 'contpuc_descripcion' => 'Primas extralegales', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5105'],
            ['contpuc_codigo' => '510545', 'contpuc_descripcion' => 'Auxilios', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5105'],
            ['contpuc_codigo' => '510548', 'contpuc_descripcion' => 'Bonificaciones', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5105'],
            ['contpuc_codigo' => '510551', 'contpuc_descripcion' => 'Dotación y suministro a trabajadores', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5105'],
            ['contpuc_codigo' => '510554', 'contpuc_descripcion' => 'Seguros', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5105'],
            ['contpuc_codigo' => '510557', 'contpuc_descripcion' => 'Cuotas partes pensiones de jubilación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5105'],
            ['contpuc_codigo' => '510558', 'contpuc_descripcion' => 'Amortización cálculo actuarial pensiones de jubilación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5105'],
            ['contpuc_codigo' => '510559', 'contpuc_descripcion' => 'Pensiones de jubilación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5105'],
            ['contpuc_codigo' => '510560', 'contpuc_descripcion' => 'Indemnizaciones laborales', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5105'],
            ['contpuc_codigo' => '510561', 'contpuc_descripcion' => 'Amortización bonos pensionales', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5105'],
            ['contpuc_codigo' => '510562', 'contpuc_descripcion' => 'Amortización títulos pensionales', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5105'],
            ['contpuc_codigo' => '510563', 'contpuc_descripcion' => 'Capacitación al personal', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5105'],
            ['contpuc_codigo' => '510566', 'contpuc_descripcion' => 'Gastos deportivos y de recreación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5105'],
            ['contpuc_codigo' => '510568', 'contpuc_descripcion' => 'Aportes a administradoras de riesgos profesionales, ARP', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5105'],
            ['contpuc_codigo' => '510569', 'contpuc_descripcion' => 'Aportes a entidades promotoras de salud, EPS', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5105'],
            ['contpuc_codigo' => '510570', 'contpuc_descripcion' => 'Aportes a fondos de pensiones y/o cesantías', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5105'],
            ['contpuc_codigo' => '510572', 'contpuc_descripcion' => 'Aportes cajas de compensación familiar', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5105'],
            ['contpuc_codigo' => '510575', 'contpuc_descripcion' => 'Aportes ICBF', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5105'],
            ['contpuc_codigo' => '510578', 'contpuc_descripcion' => 'SENA', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5105'],
            ['contpuc_codigo' => '510581', 'contpuc_descripcion' => 'Aportes sindicales', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5105'],
            ['contpuc_codigo' => '510584', 'contpuc_descripcion' => 'Gastos médicos y drogas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5105'],
            ['contpuc_codigo' => '510595', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5105'],
            ['contpuc_codigo' => '510599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5105'],
            ['contpuc_codigo' => '511005', 'contpuc_descripcion' => 'Junta directiva', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5110'],
            ['contpuc_codigo' => '511010', 'contpuc_descripcion' => 'Revisoría fiscal', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5110'],
            ['contpuc_codigo' => '511015', 'contpuc_descripcion' => 'Auditoría externa', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5110'],
            ['contpuc_codigo' => '511020', 'contpuc_descripcion' => 'Avalúos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5110'],
            ['contpuc_codigo' => '511025', 'contpuc_descripcion' => 'Asesoría jurídica', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5110'],
            ['contpuc_codigo' => '511030', 'contpuc_descripcion' => 'Asesoría financiera', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5110'],
            ['contpuc_codigo' => '511035', 'contpuc_descripcion' => 'Asesoría técnica', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5110'],
            ['contpuc_codigo' => '511095', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5110'],
            ['contpuc_codigo' => '511099', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5110'],
            ['contpuc_codigo' => '511505', 'contpuc_descripcion' => 'Industria y comercio', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5115'],
            ['contpuc_codigo' => '511510', 'contpuc_descripcion' => 'De timbres', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5115'],
            ['contpuc_codigo' => '511515', 'contpuc_descripcion' => 'A la propiedad raíz', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5115'],
            ['contpuc_codigo' => '511520', 'contpuc_descripcion' => 'Derechos sobre instrumentos públicos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5115'],
            ['contpuc_codigo' => '511525', 'contpuc_descripcion' => 'De valorización', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5115'],
            ['contpuc_codigo' => '511530', 'contpuc_descripcion' => 'De turismo', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5115'],
            ['contpuc_codigo' => '511535', 'contpuc_descripcion' => 'Tasa por utilización de puertos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5115'],
            ['contpuc_codigo' => '511540', 'contpuc_descripcion' => 'De vehículos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5115'],
            ['contpuc_codigo' => '511545', 'contpuc_descripcion' => 'De espectáculos públicos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5115'],
            ['contpuc_codigo' => '511550', 'contpuc_descripcion' => 'Cuotas de fomento', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5115'],
            ['contpuc_codigo' => '511570', 'contpuc_descripcion' => 'IVA descontable', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5115'],
            ['contpuc_codigo' => '511595', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5115'],
            ['contpuc_codigo' => '511599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5115'],
            ['contpuc_codigo' => '512005', 'contpuc_descripcion' => 'Terrenos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5120'],
            ['contpuc_codigo' => '512010', 'contpuc_descripcion' => 'Construcciones y edificaciones', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5120'],
            ['contpuc_codigo' => '512015', 'contpuc_descripcion' => 'Maquinaria y equipo', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5120'],
            ['contpuc_codigo' => '512020', 'contpuc_descripcion' => 'Equipo de oficina', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5120'],
            ['contpuc_codigo' => '512025', 'contpuc_descripcion' => 'Equipo de computación y comunicación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5120'],
            ['contpuc_codigo' => '512030', 'contpuc_descripcion' => 'Equipo médico-científico', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5120'],
            ['contpuc_codigo' => '512035', 'contpuc_descripcion' => 'Equipo de hoteles y restaurantes', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5120'],
            ['contpuc_codigo' => '512040', 'contpuc_descripcion' => 'Flota y equipo de transporte', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5120'],
            ['contpuc_codigo' => '512045', 'contpuc_descripcion' => 'Flota y equipo fluvial y/o marítimo', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5120'],
            ['contpuc_codigo' => '512050', 'contpuc_descripcion' => 'Flota y equipo aéreo', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5120'],
            ['contpuc_codigo' => '512055', 'contpuc_descripcion' => 'Flota y equipo férreo', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5120'],
            ['contpuc_codigo' => '512060', 'contpuc_descripcion' => 'Acueductos, plantas y redes', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5120'],
            ['contpuc_codigo' => '512065', 'contpuc_descripcion' => 'Aeródromos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5120'],
            ['contpuc_codigo' => '512070', 'contpuc_descripcion' => 'Semovientes', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5120'],
            ['contpuc_codigo' => '512095', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5120'],
            ['contpuc_codigo' => '512099', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5120'],
            ['contpuc_codigo' => '512505', 'contpuc_descripcion' => 'Contribuciones', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5125'],
            ['contpuc_codigo' => '512510', 'contpuc_descripcion' => 'Afiliaciones y sostenimiento', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5125'],
            ['contpuc_codigo' => '512599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5125'],
            ['contpuc_codigo' => '513005', 'contpuc_descripcion' => 'Manejo', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5130'],
            ['contpuc_codigo' => '513010', 'contpuc_descripcion' => 'Cumplimiento', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5130'],
            ['contpuc_codigo' => '513015', 'contpuc_descripcion' => 'Corriente débil', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5130'],
            ['contpuc_codigo' => '513020', 'contpuc_descripcion' => 'Vida colectiva', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5130'],
            ['contpuc_codigo' => '513025', 'contpuc_descripcion' => 'Incendio', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5130'],
            ['contpuc_codigo' => '513030', 'contpuc_descripcion' => 'Terremoto', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5130'],
            ['contpuc_codigo' => '513035', 'contpuc_descripcion' => 'Sustracción y hurto', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5130'],
            ['contpuc_codigo' => '513040', 'contpuc_descripcion' => 'Flota y equipo de transporte', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5130'],
            ['contpuc_codigo' => '513045', 'contpuc_descripcion' => 'Flota y equipo fluvial y/o marítimo', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5130'],
            ['contpuc_codigo' => '513050', 'contpuc_descripcion' => 'Flota y equipo aéreo', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5130'],
            ['contpuc_codigo' => '513055', 'contpuc_descripcion' => 'Flota y equipo férreo', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5130'],
            ['contpuc_codigo' => '513060', 'contpuc_descripcion' => 'Responsabilidad civil y extracontractual', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5130'],
            ['contpuc_codigo' => '513065', 'contpuc_descripcion' => 'Vuelo', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5130'],
            ['contpuc_codigo' => '513070', 'contpuc_descripcion' => 'Rotura de maquinaria', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5130'],
            ['contpuc_codigo' => '513075', 'contpuc_descripcion' => 'Obligatorio accidente de tránsito', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5130'],
            ['contpuc_codigo' => '513080', 'contpuc_descripcion' => 'Lucro cesante', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5130'],
            ['contpuc_codigo' => '513085', 'contpuc_descripcion' => 'Transporte de mercancía', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5130'],
            ['contpuc_codigo' => '513095', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5130'],
            ['contpuc_codigo' => '513099', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5130'],
            ['contpuc_codigo' => '513505', 'contpuc_descripcion' => 'Aseo y vigilancia', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5135'],
            ['contpuc_codigo' => '513510', 'contpuc_descripcion' => 'Temporales', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5135'],
            ['contpuc_codigo' => '513515', 'contpuc_descripcion' => 'Asistencia técnica', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5135'],
            ['contpuc_codigo' => '513520', 'contpuc_descripcion' => 'Procesamiento electrónico de datos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5135'],
            ['contpuc_codigo' => '513525', 'contpuc_descripcion' => 'Acueducto y alcantarillado', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5135'],
            ['contpuc_codigo' => '513530', 'contpuc_descripcion' => 'Energía eléctrica', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5135'],
            ['contpuc_codigo' => '513535', 'contpuc_descripcion' => 'Teléfono', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5135'],
            ['contpuc_codigo' => '513540', 'contpuc_descripcion' => 'Correo, portes y telegramas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5135'],
            ['contpuc_codigo' => '513545', 'contpuc_descripcion' => 'Fax y télex', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5135'],
            ['contpuc_codigo' => '513550', 'contpuc_descripcion' => 'Transporte, fletes y acarreos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5135'],
            ['contpuc_codigo' => '513555', 'contpuc_descripcion' => 'Gas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5135'],
            ['contpuc_codigo' => '513595', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5135'],
            ['contpuc_codigo' => '513599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5135'],
            ['contpuc_codigo' => '514005', 'contpuc_descripcion' => 'Notariales', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5140'],
            ['contpuc_codigo' => '514010', 'contpuc_descripcion' => 'Registro mercantil', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5140'],
            ['contpuc_codigo' => '514015', 'contpuc_descripcion' => 'Trámites y licencias', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5140'],
            ['contpuc_codigo' => '514020', 'contpuc_descripcion' => 'Aduaneros', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5140'],
            ['contpuc_codigo' => '514025', 'contpuc_descripcion' => 'Consulares', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5140'],
            ['contpuc_codigo' => '514095', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5140'],
            ['contpuc_codigo' => '514099', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5140'],
            ['contpuc_codigo' => '514505', 'contpuc_descripcion' => 'Terrenos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5145'],
            ['contpuc_codigo' => '514510', 'contpuc_descripcion' => 'Construcciones y edificaciones', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5145'],
            ['contpuc_codigo' => '514515', 'contpuc_descripcion' => 'Maquinaria y equipo', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5145'],
            ['contpuc_codigo' => '514520', 'contpuc_descripcion' => 'Equipo de oficina', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5145'],
            ['contpuc_codigo' => '514525', 'contpuc_descripcion' => 'Equipo de computación y comunicación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5145'],
            ['contpuc_codigo' => '514530', 'contpuc_descripcion' => 'Equipo médico-científico', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5145'],
            ['contpuc_codigo' => '514535', 'contpuc_descripcion' => 'Equipo de hoteles y restaurantes', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5145'],
            ['contpuc_codigo' => '514540', 'contpuc_descripcion' => 'Flota y equipo de transporte', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5145'],
            ['contpuc_codigo' => '514545', 'contpuc_descripcion' => 'Flota y equipo fluvial y/o marítimo', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5145'],
            ['contpuc_codigo' => '514550', 'contpuc_descripcion' => 'Flota y equipo aéreo', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5145'],
            ['contpuc_codigo' => '514555', 'contpuc_descripcion' => 'Flota y equipo férreo', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5145'],
            ['contpuc_codigo' => '514560', 'contpuc_descripcion' => 'Acueductos, plantas y redes', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5145'],
            ['contpuc_codigo' => '514565', 'contpuc_descripcion' => 'Armamento de vigilancia', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5145'],
            ['contpuc_codigo' => '514570', 'contpuc_descripcion' => 'Vías de comunicación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5145'],
            ['contpuc_codigo' => '514599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5145'],
            ['contpuc_codigo' => '515005', 'contpuc_descripcion' => 'Instalaciones eléctricas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5150'],
            ['contpuc_codigo' => '515010', 'contpuc_descripcion' => 'Arreglos ornamentales', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5150'],
            ['contpuc_codigo' => '515015', 'contpuc_descripcion' => 'Reparaciones locativas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5150'],
            ['contpuc_codigo' => '515095', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5150'],
            ['contpuc_codigo' => '515099', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5150'],
            ['contpuc_codigo' => '515505', 'contpuc_descripcion' => 'Alojamiento y manutención', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5155'],
            ['contpuc_codigo' => '515510', 'contpuc_descripcion' => 'Pasajes fluviales y/o marítimos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5155'],
            ['contpuc_codigo' => '515515', 'contpuc_descripcion' => 'Pasajes aéreos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5155'],
            ['contpuc_codigo' => '515520', 'contpuc_descripcion' => 'Pasajes terrestres', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5155'],
            ['contpuc_codigo' => '515525', 'contpuc_descripcion' => 'Pasajes férreos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5155'],
            ['contpuc_codigo' => '515595', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5155'],
            ['contpuc_codigo' => '515599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5155'],
            ['contpuc_codigo' => '516005', 'contpuc_descripcion' => 'Construcciones y edificaciones', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5160'],
            ['contpuc_codigo' => '516010', 'contpuc_descripcion' => 'Maquinaria y equipo', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5160'],
            ['contpuc_codigo' => '516015', 'contpuc_descripcion' => 'Equipo de oficina', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5160'],
            ['contpuc_codigo' => '516020', 'contpuc_descripcion' => 'Equipo de computación y comunicación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5160'],
            ['contpuc_codigo' => '516025', 'contpuc_descripcion' => 'Equipo médico-científico', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5160'],
            ['contpuc_codigo' => '516030', 'contpuc_descripcion' => 'Equipo de hoteles y restaurantes', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5160'],
            ['contpuc_codigo' => '516035', 'contpuc_descripcion' => 'Flota y equipo de transporte', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5160'],
            ['contpuc_codigo' => '516040', 'contpuc_descripcion' => 'Flota y equipo fluvial y/o marítimo', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5160'],
            ['contpuc_codigo' => '516045', 'contpuc_descripcion' => 'Flota y equipo aéreo', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5160'],
            ['contpuc_codigo' => '516050', 'contpuc_descripcion' => 'Flota y equipo férreo', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5160'],
            ['contpuc_codigo' => '516055', 'contpuc_descripcion' => 'Acueductos, plantas y redes', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5160'],
            ['contpuc_codigo' => '516060', 'contpuc_descripcion' => 'Armamento de vigilancia', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5160'],
            ['contpuc_codigo' => '516099', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5160'],
            ['contpuc_codigo' => '516505', 'contpuc_descripcion' => 'Vías de comunicación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5165'],
            ['contpuc_codigo' => '516510', 'contpuc_descripcion' => 'Intangibles', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5165'],
            ['contpuc_codigo' => '516515', 'contpuc_descripcion' => 'Cargos diferidos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5165'],
            ['contpuc_codigo' => '516595', 'contpuc_descripcion' => 'Otras', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5165'],
            ['contpuc_codigo' => '516599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5165'],
            ['contpuc_codigo' => '519505', 'contpuc_descripcion' => 'Comisiones', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5195'],
            ['contpuc_codigo' => '519510', 'contpuc_descripcion' => 'Libros, suscripciones, periódicos y revistas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5195'],
            ['contpuc_codigo' => '519515', 'contpuc_descripcion' => 'Música ambiental', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5195'],
            ['contpuc_codigo' => '519520', 'contpuc_descripcion' => 'Gastos de representación y relaciones públicas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5195'],
            ['contpuc_codigo' => '519525', 'contpuc_descripcion' => 'Elementos de aseo y cafetería', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5195'],
            ['contpuc_codigo' => '519530', 'contpuc_descripcion' => 'Útiles, papelería y fotocopias', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5195'],
            ['contpuc_codigo' => '519535', 'contpuc_descripcion' => 'Combustibles y lubricantes', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5195'],
            ['contpuc_codigo' => '519540', 'contpuc_descripcion' => 'Envases y empaques', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5195'],
            ['contpuc_codigo' => '519545', 'contpuc_descripcion' => 'Taxis y buses', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5195'],
            ['contpuc_codigo' => '519550', 'contpuc_descripcion' => 'Estampillas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5195'],
            ['contpuc_codigo' => '519555', 'contpuc_descripcion' => 'Microfilmación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5195'],
            ['contpuc_codigo' => '519560', 'contpuc_descripcion' => 'Casino y restaurante', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5195'],
            ['contpuc_codigo' => '519565', 'contpuc_descripcion' => 'Parqueaderos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5195'],
            ['contpuc_codigo' => '519570', 'contpuc_descripcion' => 'Indemnización por daños a terceros', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5195'],
            ['contpuc_codigo' => '519575', 'contpuc_descripcion' => 'Pólvora y similares', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5195'],
            ['contpuc_codigo' => '519595', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5195'],
            ['contpuc_codigo' => '519599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5195'],
            ['contpuc_codigo' => '519905', 'contpuc_descripcion' => 'Inversiones', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5199'],
            ['contpuc_codigo' => '519910', 'contpuc_descripcion' => 'Deudores', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5199'],
            ['contpuc_codigo' => '519915', 'contpuc_descripcion' => 'Propiedades, planta y equipo', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5199'],
            ['contpuc_codigo' => '519995', 'contpuc_descripcion' => 'Otros activos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5199'],
            ['contpuc_codigo' => '519999', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5199'],
            ['contpuc_codigo' => '520503', 'contpuc_descripcion' => 'Salario integral', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5205'],
            ['contpuc_codigo' => '520506', 'contpuc_descripcion' => 'Sueldos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5205'],
            ['contpuc_codigo' => '520512', 'contpuc_descripcion' => 'Jornales', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5205'],
            ['contpuc_codigo' => '520515', 'contpuc_descripcion' => 'Horas extras y recargos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5205'],
            ['contpuc_codigo' => '520518', 'contpuc_descripcion' => 'Comisiones', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5205'],
            ['contpuc_codigo' => '520521', 'contpuc_descripcion' => 'Viáticos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5205'],
            ['contpuc_codigo' => '520524', 'contpuc_descripcion' => 'Incapacidades', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5205'],
            ['contpuc_codigo' => '520527', 'contpuc_descripcion' => 'Auxilio de transporte', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5205'],
            ['contpuc_codigo' => '520530', 'contpuc_descripcion' => 'Cesantías', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5205'],
            ['contpuc_codigo' => '520533', 'contpuc_descripcion' => 'Intereses sobre cesantías', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5205'],
            ['contpuc_codigo' => '520536', 'contpuc_descripcion' => 'Prima de servicios', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5205'],
            ['contpuc_codigo' => '520539', 'contpuc_descripcion' => 'Vacaciones', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5205'],
            ['contpuc_codigo' => '520542', 'contpuc_descripcion' => 'Primas extralegales', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5205'],
            ['contpuc_codigo' => '520545', 'contpuc_descripcion' => 'Auxilios', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5205'],
            ['contpuc_codigo' => '520548', 'contpuc_descripcion' => 'Bonificaciones', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5205'],
            ['contpuc_codigo' => '520551', 'contpuc_descripcion' => 'Dotación y suministro a trabajadores', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5205'],
            ['contpuc_codigo' => '520554', 'contpuc_descripcion' => 'Seguros', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5205'],
            ['contpuc_codigo' => '520557', 'contpuc_descripcion' => 'Cuotas partes pensiones de jubilación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5205'],
            ['contpuc_codigo' => '520558', 'contpuc_descripcion' => 'Amortización cálculo actuarial pensiones de jubilación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5205'],
            ['contpuc_codigo' => '520559', 'contpuc_descripcion' => 'Pensiones de jubilación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5205'],
            ['contpuc_codigo' => '520560', 'contpuc_descripcion' => 'Indemnizaciones laborales', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5205'],
            ['contpuc_codigo' => '520561', 'contpuc_descripcion' => 'Amortización bonos pensionales', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5205'],
            ['contpuc_codigo' => '520562', 'contpuc_descripcion' => 'Amortización títulos pensionales', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5205'],
            ['contpuc_codigo' => '520563', 'contpuc_descripcion' => 'Capacitación al personal', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5205'],
            ['contpuc_codigo' => '520566', 'contpuc_descripcion' => 'Gastos deportivos y de recreación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5205'],
            ['contpuc_codigo' => '520568', 'contpuc_descripcion' => 'Aportes a administradoras de riesgos profesionales, ARP', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5205'],
            ['contpuc_codigo' => '520569', 'contpuc_descripcion' => 'Aportes a entidades promotoras de salud, EPS', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5205'],
            ['contpuc_codigo' => '520570', 'contpuc_descripcion' => 'Aportes a fondos de pensiones y/o cesantías', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5205'],
            ['contpuc_codigo' => '520572', 'contpuc_descripcion' => 'Aportes cajas de compensación familiar', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5205'],
            ['contpuc_codigo' => '520575', 'contpuc_descripcion' => 'Aportes ICBF', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5205'],
            ['contpuc_codigo' => '520578', 'contpuc_descripcion' => 'SENA', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5205'],
            ['contpuc_codigo' => '520581', 'contpuc_descripcion' => 'Aportes sindicales', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5205'],
            ['contpuc_codigo' => '520584', 'contpuc_descripcion' => 'Gastos médicos y drogas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5205'],
            ['contpuc_codigo' => '520595', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5205'],
            ['contpuc_codigo' => '520599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5205'],
            ['contpuc_codigo' => '521005', 'contpuc_descripcion' => 'Junta directiva', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5210'],
            ['contpuc_codigo' => '521010', 'contpuc_descripcion' => 'Revisoría fiscal', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5210'],
            ['contpuc_codigo' => '521015', 'contpuc_descripcion' => 'Auditoría externa', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5210'],
            ['contpuc_codigo' => '521020', 'contpuc_descripcion' => 'Avalúos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5210'],
            ['contpuc_codigo' => '521025', 'contpuc_descripcion' => 'Asesoría jurídica', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5210'],
            ['contpuc_codigo' => '521030', 'contpuc_descripcion' => 'Asesoría financiera', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5210'],
            ['contpuc_codigo' => '521035', 'contpuc_descripcion' => 'Asesoría técnica', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5210'],
            ['contpuc_codigo' => '521095', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5210'],
            ['contpuc_codigo' => '521099', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5210'],
            ['contpuc_codigo' => '521505', 'contpuc_descripcion' => 'Industria y comercio', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5215'],
            ['contpuc_codigo' => '521510', 'contpuc_descripcion' => 'De timbres', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5215'],
            ['contpuc_codigo' => '521515', 'contpuc_descripcion' => 'A la propiedad raíz', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5215'],
            ['contpuc_codigo' => '521520', 'contpuc_descripcion' => 'Derechos sobre instrumentos públicos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5215'],
            ['contpuc_codigo' => '521525', 'contpuc_descripcion' => 'De valorización', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5215'],
            ['contpuc_codigo' => '521530', 'contpuc_descripcion' => 'De turismo', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5215'],
            ['contpuc_codigo' => '521535', 'contpuc_descripcion' => 'Tasa por utilización de puertos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5215'],
            ['contpuc_codigo' => '521540', 'contpuc_descripcion' => 'De vehículos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5215'],
            ['contpuc_codigo' => '521545', 'contpuc_descripcion' => 'De espectáculos públicos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5215'],
            ['contpuc_codigo' => '521550', 'contpuc_descripcion' => 'Cuotas de fomento', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5215'],
            ['contpuc_codigo' => '521555', 'contpuc_descripcion' => 'Licores', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5215'],
            ['contpuc_codigo' => '521560', 'contpuc_descripcion' => 'Cervezas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5215'],
            ['contpuc_codigo' => '521565', 'contpuc_descripcion' => 'Cigarrillos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5215'],
            ['contpuc_codigo' => '521570', 'contpuc_descripcion' => 'IVA descontable', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5215'],
            ['contpuc_codigo' => '521595', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5215'],
            ['contpuc_codigo' => '521599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5215'],
            ['contpuc_codigo' => '522005', 'contpuc_descripcion' => 'Terrenos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5220'],
            ['contpuc_codigo' => '522010', 'contpuc_descripcion' => 'Construcciones y edificaciones', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5220'],
            ['contpuc_codigo' => '522015', 'contpuc_descripcion' => 'Maquinaria y equipo', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5220'],
            ['contpuc_codigo' => '522020', 'contpuc_descripcion' => 'Equipo de oficina', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5220'],
            ['contpuc_codigo' => '522025', 'contpuc_descripcion' => 'Equipo de computación y comunicación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5220'],
            ['contpuc_codigo' => '522030', 'contpuc_descripcion' => 'Equipo médico-científico', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5220'],
            ['contpuc_codigo' => '522035', 'contpuc_descripcion' => 'Equipo de hoteles y restaurantes', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5220'],
            ['contpuc_codigo' => '522040', 'contpuc_descripcion' => 'Flota y equipo de transporte', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5220'],
            ['contpuc_codigo' => '522045', 'contpuc_descripcion' => 'Flota y equipo fluvial y/o marítimo', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5220'],
            ['contpuc_codigo' => '522050', 'contpuc_descripcion' => 'Flota y equipo aéreo', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5220'],
            ['contpuc_codigo' => '522055', 'contpuc_descripcion' => 'Flota y equipo férreo', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5220'],
            ['contpuc_codigo' => '522060', 'contpuc_descripcion' => 'Acueductos, plantas y redes', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5220'],
            ['contpuc_codigo' => '522065', 'contpuc_descripcion' => 'Aeródromos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5220'],
            ['contpuc_codigo' => '522070', 'contpuc_descripcion' => 'Semovientes', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5220'],
            ['contpuc_codigo' => '522095', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5220'],
            ['contpuc_codigo' => '522099', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5220'],
            ['contpuc_codigo' => '522505', 'contpuc_descripcion' => 'Contribuciones', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5225'],
            ['contpuc_codigo' => '522510', 'contpuc_descripcion' => 'Afiliaciones y sostenimiento', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5225'],
            ['contpuc_codigo' => '522599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5225'],
            ['contpuc_codigo' => '523005', 'contpuc_descripcion' => 'Manejo', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5230'],
            ['contpuc_codigo' => '523010', 'contpuc_descripcion' => 'Cumplimiento', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5230'],
            ['contpuc_codigo' => '523015', 'contpuc_descripcion' => 'Corriente débil', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5230'],
            ['contpuc_codigo' => '523020', 'contpuc_descripcion' => 'Vida colectiva', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5230'],
            ['contpuc_codigo' => '523025', 'contpuc_descripcion' => 'Incendio', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5230'],
            ['contpuc_codigo' => '523030', 'contpuc_descripcion' => 'Terremoto', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5230'],
            ['contpuc_codigo' => '523035', 'contpuc_descripcion' => 'Sustracción y hurto', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5230'],
            ['contpuc_codigo' => '523040', 'contpuc_descripcion' => 'Flota y equipo de transporte', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5230'],
            ['contpuc_codigo' => '523045', 'contpuc_descripcion' => 'Flota y equipo fluvial y/o marítimo', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5230'],
            ['contpuc_codigo' => '523050', 'contpuc_descripcion' => 'Flota y equipo aéreo', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5230'],
            ['contpuc_codigo' => '523055', 'contpuc_descripcion' => 'Flota y equipo férreo', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5230'],
            ['contpuc_codigo' => '523060', 'contpuc_descripcion' => 'Responsabilidad civil y extracontractual', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5230'],
            ['contpuc_codigo' => '523065', 'contpuc_descripcion' => 'Vuelo', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5230'],
            ['contpuc_codigo' => '523070', 'contpuc_descripcion' => 'Rotura de maquinaria', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5230'],
            ['contpuc_codigo' => '523075', 'contpuc_descripcion' => 'Obligatorio accidente de tránsito', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5230'],
            ['contpuc_codigo' => '523080', 'contpuc_descripcion' => 'Lucro cesante', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5230'],
            ['contpuc_codigo' => '523095', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5230'],
            ['contpuc_codigo' => '523099', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5230'],
            ['contpuc_codigo' => '523505', 'contpuc_descripcion' => 'Aseo y vigilancia', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5235'],
            ['contpuc_codigo' => '523510', 'contpuc_descripcion' => 'Temporales', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5235'],
            ['contpuc_codigo' => '523515', 'contpuc_descripcion' => 'Asistencia técnica', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5235'],
            ['contpuc_codigo' => '523520', 'contpuc_descripcion' => 'Procesamiento electrónico de datos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5235'],
            ['contpuc_codigo' => '523525', 'contpuc_descripcion' => 'Acueducto y alcantarillado', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5235'],
            ['contpuc_codigo' => '523530', 'contpuc_descripcion' => 'Energía eléctrica', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5235'],
            ['contpuc_codigo' => '523535', 'contpuc_descripcion' => 'Teléfono', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5235'],
            ['contpuc_codigo' => '523540', 'contpuc_descripcion' => 'Correo, portes y telegramas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5235'],
            ['contpuc_codigo' => '523545', 'contpuc_descripcion' => 'Fax y télex', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5235'],
            ['contpuc_codigo' => '523550', 'contpuc_descripcion' => 'Transporte, fletes y acarreos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5235'],
            ['contpuc_codigo' => '523555', 'contpuc_descripcion' => 'Gas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5235'],
            ['contpuc_codigo' => '523560', 'contpuc_descripcion' => 'Publicidad, propaganda y promoción', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5235'],
            ['contpuc_codigo' => '523595', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5235'],
            ['contpuc_codigo' => '523599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5235'],
            ['contpuc_codigo' => '524005', 'contpuc_descripcion' => 'Notariales', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5240'],
            ['contpuc_codigo' => '524010', 'contpuc_descripcion' => 'Registro mercantil', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5240'],
            ['contpuc_codigo' => '524015', 'contpuc_descripcion' => 'Trámites y licencias', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5240'],
            ['contpuc_codigo' => '524020', 'contpuc_descripcion' => 'Aduaneros', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5240'],
            ['contpuc_codigo' => '524025', 'contpuc_descripcion' => 'Consulares', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5240'],
            ['contpuc_codigo' => '524095', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5240'],
            ['contpuc_codigo' => '524099', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5240'],
            ['contpuc_codigo' => '524505', 'contpuc_descripcion' => 'Terrenos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5245'],
            ['contpuc_codigo' => '524510', 'contpuc_descripcion' => 'Construcciones y edificaciones', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5245'],
            ['contpuc_codigo' => '524515', 'contpuc_descripcion' => 'Maquinaria y equipo', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5245'],
            ['contpuc_codigo' => '524520', 'contpuc_descripcion' => 'Equipo de oficina', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5245'],
            ['contpuc_codigo' => '524525', 'contpuc_descripcion' => 'Equipo de computación y comunicación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5245'],
            ['contpuc_codigo' => '524530', 'contpuc_descripcion' => 'Equipo médico-científico', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5245'],
            ['contpuc_codigo' => '524535', 'contpuc_descripcion' => 'Equipo de hoteles y restaurantes', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5245'],
            ['contpuc_codigo' => '524540', 'contpuc_descripcion' => 'Flota y equipo de transporte', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5245'],
            ['contpuc_codigo' => '524545', 'contpuc_descripcion' => 'Flota y equipo fluvial y/o marítimo', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5245'],
            ['contpuc_codigo' => '524550', 'contpuc_descripcion' => 'Flota y equipo aéreo', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5245'],
            ['contpuc_codigo' => '524555', 'contpuc_descripcion' => 'Flota y equipo férreo', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5245'],
            ['contpuc_codigo' => '524560', 'contpuc_descripcion' => 'Acueductos, plantas y redes', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5245'],
            ['contpuc_codigo' => '524565', 'contpuc_descripcion' => 'Armamento de vigilancia', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5245'],
            ['contpuc_codigo' => '524570', 'contpuc_descripcion' => 'Vías de comunicación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5245'],
            ['contpuc_codigo' => '524599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5245'],
            ['contpuc_codigo' => '525005', 'contpuc_descripcion' => 'Instalaciones eléctricas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5250'],
            ['contpuc_codigo' => '525010', 'contpuc_descripcion' => 'Arreglos ornamentales', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5250'],
            ['contpuc_codigo' => '525015', 'contpuc_descripcion' => 'Reparaciones locativas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5250'],
            ['contpuc_codigo' => '525095', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5250'],
            ['contpuc_codigo' => '525099', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5250'],
            ['contpuc_codigo' => '525505', 'contpuc_descripcion' => 'Alojamiento y manutención', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5255'],
            ['contpuc_codigo' => '525510', 'contpuc_descripcion' => 'Pasajes fluviales y/o marítimos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5255'],
            ['contpuc_codigo' => '525515', 'contpuc_descripcion' => 'Pasajes aéreos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5255'],
            ['contpuc_codigo' => '525520', 'contpuc_descripcion' => 'Pasajes terrestres', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5255'],
            ['contpuc_codigo' => '525525', 'contpuc_descripcion' => 'Pasajes férreos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5255'],
            ['contpuc_codigo' => '525595', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5255'],
            ['contpuc_codigo' => '525599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5255'],
            ['contpuc_codigo' => '526005', 'contpuc_descripcion' => 'Construcciones y edificaciones', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5260'],
            ['contpuc_codigo' => '526010', 'contpuc_descripcion' => 'Maquinaria y equipo', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5260'],
            ['contpuc_codigo' => '526015', 'contpuc_descripcion' => 'Equipo de oficina', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5260'],
            ['contpuc_codigo' => '526020', 'contpuc_descripcion' => 'Equipo de computación y comunicación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5260'],
            ['contpuc_codigo' => '526025', 'contpuc_descripcion' => 'Equipo médico-científico', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5260'],
            ['contpuc_codigo' => '526030', 'contpuc_descripcion' => 'Equipo de hoteles y restaurantes', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5260'],
            ['contpuc_codigo' => '526035', 'contpuc_descripcion' => 'Flota y equipo de transporte', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5260'],
            ['contpuc_codigo' => '526040', 'contpuc_descripcion' => 'Flota y equipo fluvial y/o marítimo', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5260'],
            ['contpuc_codigo' => '526045', 'contpuc_descripcion' => 'Flota y equipo aéreo', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5260'],
            ['contpuc_codigo' => '526050', 'contpuc_descripcion' => 'Flota y equipo férreo', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5260'],
            ['contpuc_codigo' => '526055', 'contpuc_descripcion' => 'Acueductos, plantas y redes', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5260'],
            ['contpuc_codigo' => '526060', 'contpuc_descripcion' => 'Armamento de vigilancia', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5260'],
            ['contpuc_codigo' => '526065', 'contpuc_descripcion' => 'Envases y empaques', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5260'],
            ['contpuc_codigo' => '526099', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5260'],
            ['contpuc_codigo' => '526505', 'contpuc_descripcion' => 'Vías de comunicación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5265'],
            ['contpuc_codigo' => '526510', 'contpuc_descripcion' => 'Intangibles', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5265'],
            ['contpuc_codigo' => '526515', 'contpuc_descripcion' => 'Cargos diferidos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5265'],
            ['contpuc_codigo' => '526595', 'contpuc_descripcion' => 'Otras', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5265'],
            ['contpuc_codigo' => '526599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5265'],
            ['contpuc_codigo' => '527099', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5270'],
            ['contpuc_codigo' => '527505', 'contpuc_descripcion' => 'De sociedades anónimas y/o asimiladas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5275'],
            ['contpuc_codigo' => '527510', 'contpuc_descripcion' => 'De sociedades limitadas y/o asimiladas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5275'],
            ['contpuc_codigo' => '529505', 'contpuc_descripcion' => 'Comisiones', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5295'],
            ['contpuc_codigo' => '529510', 'contpuc_descripcion' => 'Libros, suscripciones, periódicos y revistas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5295'],
            ['contpuc_codigo' => '529515', 'contpuc_descripcion' => 'Música ambiental', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5295'],
            ['contpuc_codigo' => '529520', 'contpuc_descripcion' => 'Gastos de representación y relaciones públicas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5295'],
            ['contpuc_codigo' => '529525', 'contpuc_descripcion' => 'Elementos de aseo y cafetería', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5295'],
            ['contpuc_codigo' => '529530', 'contpuc_descripcion' => 'Útiles, papelería y fotocopias', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5295'],
            ['contpuc_codigo' => '529535', 'contpuc_descripcion' => 'Combustibles y lubricantes', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5295'],
            ['contpuc_codigo' => '529540', 'contpuc_descripcion' => 'Envases y empaques', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5295'],
            ['contpuc_codigo' => '529545', 'contpuc_descripcion' => 'Taxis y buses', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5295'],
            ['contpuc_codigo' => '529550', 'contpuc_descripcion' => 'Estampillas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5295'],
            ['contpuc_codigo' => '529555', 'contpuc_descripcion' => 'Microfilmación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5295'],
            ['contpuc_codigo' => '529560', 'contpuc_descripcion' => 'Casino y restaurante', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5295'],
            ['contpuc_codigo' => '529565', 'contpuc_descripcion' => 'Parqueaderos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5295'],
            ['contpuc_codigo' => '529570', 'contpuc_descripcion' => 'Indemnización por daños a terceros', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5295'],
            ['contpuc_codigo' => '529575', 'contpuc_descripcion' => 'Pólvora y similares', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5295'],
            ['contpuc_codigo' => '529595', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5295'],
            ['contpuc_codigo' => '529599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5295'],
            ['contpuc_codigo' => '529905', 'contpuc_descripcion' => 'Inversiones', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5299'],
            ['contpuc_codigo' => '529910', 'contpuc_descripcion' => 'Deudores', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5299'],
            ['contpuc_codigo' => '529915', 'contpuc_descripcion' => 'Inventarios', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5299'],
            ['contpuc_codigo' => '529920', 'contpuc_descripcion' => 'Propiedades, planta y equipo', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5299'],
            ['contpuc_codigo' => '529995', 'contpuc_descripcion' => 'Otros activos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5299'],
            ['contpuc_codigo' => '529999', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5299'],
            ['contpuc_codigo' => '530505', 'contpuc_descripcion' => 'Gastos bancarios', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5305'],
            ['contpuc_codigo' => '530510', 'contpuc_descripcion' => 'Reajuste monetario-UPAC (hoy UVR)', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5305'],
            ['contpuc_codigo' => '530515', 'contpuc_descripcion' => 'Comisiones', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5305'],
            ['contpuc_codigo' => '530520', 'contpuc_descripcion' => 'Intereses', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5305'],
            ['contpuc_codigo' => '530525', 'contpuc_descripcion' => 'Diferencia en cambio', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5305'],
            ['contpuc_codigo' => '530530', 'contpuc_descripcion' => 'Gastos en negociación certificados de cambio', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5305'],
            ['contpuc_codigo' => '530535', 'contpuc_descripcion' => 'Descuentos comerciales condicionados', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5305'],
            ['contpuc_codigo' => '530540', 'contpuc_descripcion' => 'Gastos manejo y emisión de bonos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5305'],
            ['contpuc_codigo' => '530545', 'contpuc_descripcion' => 'Prima amortizada', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5305'],
            ['contpuc_codigo' => '530595', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5305'],
            ['contpuc_codigo' => '530599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5305'],
            ['contpuc_codigo' => '531005', 'contpuc_descripcion' => 'Venta de inversiones', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5310'],
            ['contpuc_codigo' => '531010', 'contpuc_descripcion' => 'Venta de cartera', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5310'],
            ['contpuc_codigo' => '531015', 'contpuc_descripcion' => 'Venta de propiedades, planta y equipo', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5310'],
            ['contpuc_codigo' => '531020', 'contpuc_descripcion' => 'Venta de intangibles', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5310'],
            ['contpuc_codigo' => '531025', 'contpuc_descripcion' => 'Venta de otros activos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5310'],
            ['contpuc_codigo' => '531030', 'contpuc_descripcion' => 'Retiro de propiedades, planta y equipo', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5310'],
            ['contpuc_codigo' => '531035', 'contpuc_descripcion' => 'Retiro de otros activos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5310'],
            ['contpuc_codigo' => '531040', 'contpuc_descripcion' => 'Pérdidas por siniestros', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5310'],
            ['contpuc_codigo' => '531095', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5310'],
            ['contpuc_codigo' => '531099', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5310'],
            ['contpuc_codigo' => '531305', 'contpuc_descripcion' => 'De sociedades anónimas y/o asimiladas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5313'],
            ['contpuc_codigo' => '531310', 'contpuc_descripcion' => 'De sociedades limitadas y/o asimiladas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5313'],
            ['contpuc_codigo' => '531505', 'contpuc_descripcion' => 'Costas y procesos judiciales', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5315'],
            ['contpuc_codigo' => '531510', 'contpuc_descripcion' => 'Actividades culturales y cívicas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5315'],
            ['contpuc_codigo' => '531515', 'contpuc_descripcion' => 'Costos y gastos de ejercicios anteriores', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5315'],
            ['contpuc_codigo' => '531520', 'contpuc_descripcion' => 'Impuestos asumidos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5315'],
            ['contpuc_codigo' => '531595', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5315'],
            ['contpuc_codigo' => '531599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5315'],
            ['contpuc_codigo' => '539505', 'contpuc_descripcion' => 'Demandas laborales', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5395'],
            ['contpuc_codigo' => '539510', 'contpuc_descripcion' => 'Demandas por incumplimiento de contratos', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5395'],
            ['contpuc_codigo' => '539515', 'contpuc_descripcion' => 'Indemnizaciones', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5395'],
            ['contpuc_codigo' => '539520', 'contpuc_descripcion' => 'Multas, sanciones y litigios', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5395'],
            ['contpuc_codigo' => '539525', 'contpuc_descripcion' => 'Donaciones', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5395'],
            ['contpuc_codigo' => '539530', 'contpuc_descripcion' => 'Constitución de garantías', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5395'],
            ['contpuc_codigo' => '539535', 'contpuc_descripcion' => 'Amortización de bienes entregados en comodato', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5395'],
            ['contpuc_codigo' => '539595', 'contpuc_descripcion' => 'Otros', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5395'],
            ['contpuc_codigo' => '539599', 'contpuc_descripcion' => 'Ajustes por inflación', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5395'],
            ['contpuc_codigo' => '540505', 'contpuc_descripcion' => 'Impuesto de renta y complementarios', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5405'],
            ['contpuc_codigo' => '590505', 'contpuc_descripcion' => 'Ganancias y pérdidas', 'contpuc_tipo' => 'Egreso', 'parent_puc_codigo' => '5905'],
        ];

        $fecha = Carbon::now();

        foreach ($cuentasContrapartida as $cuenta) {
            $parentPUC = PUC::where('puc_codigo', $cuenta['parent_puc_codigo'])->first();

            if (!$parentPUC) {
                Log::warning("Parent PUC with code " . $cuenta['parent_puc_codigo'] . " not found for contrapartida " . $cuenta['contpuc_codigo'] . ". Skipping.");
                $this->command->error("Parent PUC with code " . $cuenta['parent_puc_codigo'] . " not found for contrapartida " . $cuenta['contpuc_codigo'] . ". Skipping.");
                continue;
            }

            ContrapartidaPUC::firstOrCreate(
                ['contpuc_codigo' => $cuenta['contpuc_codigo']], // Check if already exists
                [
                    'contpuc_descripcion' => $cuenta['contpuc_descripcion'],
                    'contpuc_tipo' => $cuenta['contpuc_tipo'],
                    'puc_idpuc' => $parentPUC->idpuc,
                    'estado' => 'Activo',
                    'fecha_registro' => $fecha,
                ]
            );
        }
        
        $this->command->info('ContrapartidaPUC Seeder for Gastos (Class 5) ran successfully!');
    }
}
