services:
    app:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: sgfinanzas_app
        restart: unless-stopped
        volumes:
            - .:/var/www/html
        networks:
            - sail
        environment:
            - "DB_CONNECTION=${DB_CONNECTION}"
            - "DB_HOST=${DB_HOST}"
            - "DB_PORT=${DB_PORT}"
            - "DB_DATABASE=${DB_DATABASE}"
            - "DB_USERNAME=${DB_USERNAME}"
            - "DB_PASSWORD=${DB_PASSWORD}"
            - "REDIS_HOST=redis"
            - "REDIS_PASSWORD=null"
            - "REDIS_PORT=6379"
            - "CACHE_STORE=redis"
            - "SESSION_DRIVER=redis"
            - "QUEUE_CONNECTION=redis"
            - "APP_ENV=production"
            - "APP_DEBUG=false"
        depends_on:
            - redis
            
    nginx:
        image: nginx:stable-alpine
        container_name: sgfinanzas_nginx
        restart: unless-stopped
        ports:
            - "${APP_PORT:-80}:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - sail
        depends_on:
            - app
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6378}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
networks:
    sail:
        driver: bridge
volumes:
    sail-redis:
        driver: local
